### ISSUE TITLE
Undefined property: Corcel\Post::$meta

### ISSUE THREAD

**Issue by carlospalacin** [jgrossi/corcel#1]
Hi!!
I am trying to install the package but I get this error:

```
Undefined property: Corcel\Post::$meta
********
public function __get($key)
    {
        if (!isset($this->$key)) {
          -->ERROR IS HERE?  return $this->meta->$key;    
        }
********
```

Can you guide me where can be the error?

I have this code:

```
$params = array(
            'database'  => 'syscover-wp',
            'username'  => 'carlos',
            'password'  => '33527667Sb',
        );
        \Corcel\Database::connect($this->params);
        $post = Post::published()->get();
```

thanks!!

**Comment by phuongit0301** [comment]
Hi, jgrossi. 
I checking the "dev" branch but the error still Undefined property: App\Post::$meta. Can you help me, please? Thanks.

**Comment by jgrossi** [comment]
Hi @phuongit0301. Can you send us your `App\Post` class in a gist?

**Comment by jgrossi** [comment]
@phuongit0301 are you using Laravel v5.2.32? Let me know, please. Regards.

**Comment by philsown** [comment]
@jgrossi - I'm using 5.3.2 and I'm encountering this bug... Here's [a gist](https://gist.github.com/philsown/6f9d41cd7faade8de337d3a0c628da1e) with my routes and model file. My database connection is as described in your readme. Should be all that's needed to replicate, I hope. If not, let me know what else I can do. I'll try to dig around on my end and see what I can find... I'm very grateful for your software and excited to get up and running with it!

**Comment by philsown** [comment]
I think this is a bug in Laravel, maybe? Model.php line 3467 is...

`if (method_exists($this, $key) && $this->$key && isset($this->relations[$key])) {`

Seems like those should be ORs, that is:

`if (method_exists($this, $key) || $this->$key || isset($this->relations[$key])) {`

**Comment by philsown** [comment]
I made [a pull request](https://github.com/laravel/framework/pull/13617) to at least call their attention to it.

**Comment by jgrossi** [comment]
Hi @philsown. Using Corcel with Laravel using a version before than `5.2.32` you'll have no problems. It seems something has changed since that version. Let's wait the Laravel response first. If not to change we create a bugfix inside Corcel, ok? Thanks

**Comment by jgrossi** [comment]
@philsown: you're trying to get `$post->meta->name`, right? Does it work using `$post->meta()->get()->name`?

**Comment by jgrossi** [comment]
Ok, I'm starting a test here with version 5.2.32 and let you know. Best

**Comment by philsown** [comment]
in `src\Post.php` line 198...

        if (!isset($this->$key)) {
            if (isset($this->meta->$key)) {
                return $this->meta->$key;
            }
        } else ...

It's looking for `$this->meta` to be set already.

**Comment by philsown** [comment]
If I add: `$this->getAttribute('meta');` right before the `isset($this->meta->$key)` test, it works.

**Comment by jgrossi** [comment]
@philsown I updated the `dev` branch. Can you check if it's working, please?

**Comment by philsown** [comment]
Yeah, that works

**Comment by jgrossi** [comment]
@philsown are you using version `5.3` right? So, it's working on `5.2.32` and `5.3`?

**Comment by philsown** [comment]
I'm on Laravel 5.2.32. not 5.3

**Comment by philsown** [comment]
Looks like a similar issue in Post.php around line 426. I changed:
        $taxonomies = $this->taxonomies;
to
        $taxonomies = $this->taxonomies()->get();

**Comment by jgrossi** [comment]
@philsown Yes, but it's not a property problem. We get errors to `thumbnails()` too, and any relationship. This is a problem inside `__get()` I'm trying to fix.

**Comment by philsown** [comment]
Cool ok.

**Comment by jgrossi** [comment]
Please @philsown can you test again with `dev` branch?

**Comment by philsown** [comment]
Checked out dev - seems to work. Thanks!

**Comment by jgrossi** [comment]
I'm gonna let this issue opened. If there are no more errors I'll close it. Thanks @philsown for helping.

**Comment by jgrossi** [comment]
I'm closing this topic because the same subject is being discussed in #151. Please, go there :-)
