### ISSUE TITLE
Test assertions increase each time the tests are run

### ISSUE THREAD

**Issue by mattKendon** [jgrossi/corcel#104]
They increase by 8 each time the full suite of tests is run. I think I've found the test that has an increasing number of assertions in it. 

```
public function testPostOrderBy()
    {
        $posts = Post::orderBy('post_date', 'asc')->get();

        $lastDate = null;
        foreach ($posts as $post) {
            if (!is_null($lastDate)) {
                $this->assertGreaterThanOrEqual(0, strcmp($post->post_date, $lastDate));
            }
            $lastDate = $post->post_date;
        }

        $posts = Post::orderBy('post_date', 'desc')->get();

        $lastDate = null;
        foreach ($posts as $post) {
            if (!is_null($lastDate)) {
                $this->assertLessThanOrEqual(0, strcmp($post->post_date, $lastDate));
            }
            $lastDate = $post->post_date;
        }
    }
```

Here is an example where the number of rows in the database is definitely being affected

```
public function testCommentEnforceConnection()
    {
        $comment = new Comment;
        $comment->setConnection('no_prefix');
        $comment->comment_content = 'Test content';
        $comment->comment_author = 1;
        $comment->comment_post_ID = 2;
        $comment->save();

        $post = new Post;
        $post->post_content = 'Test';
        $post->save();

        $comment->post()->associate($post);
        $comment->save();

        $this->assertEquals('no_prefix', $comment->getConnectionName());
        $this->assertEquals('no_prefix', $comment->post->getConnectionName());
    }
```

**Comment by jgrossi** [comment]
Yes, I checked! I think this is not a "problem", but maybe after run tests we can set a rollback, for example.

**Comment by mattKendon** [comment]
An easy fix to stop the number of assertions increasing is just to take only a subset of posts in this test (say 10) and run the test only on those. 

@jgrossi I agree that it is not a problem, however it does make it more difficult to compare test results if the database is not the same. 

Resetting the database would definitely be the thing to do.

**Comment by josec89** [comment]
There a ways to include all the database modifications inside a test inside a transaction which is rolled back when the test finishes. I used this in laravel but I guess this can be done here as it's eloquent thing

**Comment by jgrossi** [comment]
Both ideas as great (subset and rollback). What do you think? //cc @mattKendon @josec89

**Comment by mattKendon** [comment]
I use the Laravel DatabaseTransactions trait in my tests all the time as well. Love it! Rollback would be perfect for any tests that write to the database. Never done it outside of a Laravel project though, so I'm not sure how to approach it here.

**Comment by jgrossi** [comment]
The Laravel DatabaseTransactions trait cannot be used with Capsule I think. I'm trying to figure out how I can do that. I've extended tests classes to a `BaseTest` class, where I have `setUp()` and `tearDown()` methods, and I'm calling `beginTransaction()` and `rollBack()`, but it's not working yet :-(

**Comment by jgrossi** [comment]
I merge the PR #105 taking only 5 records to be tested. This make the assertions counter to 126, fixed. 
This is not what we'd like but I'm working in another branch (`issue-104`) to make the `rollBack()` work. Any suggestion just tell me or contribute to this new branch.

Any suggestion is welcome :-) Cheers
