### ISSUE TITLE
Eagerloading post-thumbnails/featured-images

### ISSUE THREAD

**Issue by kriskbx** [jgrossi/corcel#107]
The attachment ID of a post-thumbnail/featured-image gets stored in post meta. The current method to get the image looks like this:

```
public function getImageAttribute()
{
    if (!is_null($this->meta->_thumbnail_id)) {
        $image = Attachment::find($this->meta->_thumbnail_id);

        if (!is_null($image)) {
            return $image->guid;
        }
    }
}
```

This triggers a DB request for every image. This is unacceptable on larger sites: I've got up to 400 queries on one of my newest projects. I figured out how we can eager load this images to minimize the query count. It's kinda dirty that's why I openend a ticket to discuss it before implementing it. ;)

We could do something like this:

```
public function thumbnail() {
	return $this->hasOne( 'Corcel\ThumbnailMeta', 'post_id' )->where( 'meta_key', '_thumbnail_id' );
}

public function getImageAttribute() {
 	if ( !isset( $this->thumbnail ) ) {
		return false;
	}

	return $this->thumbnail->attachment;
}
```

And the ThumbnailMeta class could look like this:

```
class ThumbnailMeta extends PostMeta {
	protected $with = [ 'attachment' ];

	public function attachment() {
		return $this->belongsTo( 'Corcel\Attachment', 'meta_value' );
	}
}
```

In the end you can eagerload the thumbnails with `Post::with('thumbnail')->first()`. This triggers two additional DB requests instead of one for each post/image when using the solution that is implemented right now.

What do you think about this? Should we give it a shot? :D

**Comment by josec89** [comment]
Hey you approach looks great! Can you add a PR with docblock + tests? :D

**Comment by jgrossi** [comment]
Very nice @kriskbx! Go ahed and create a PR like @josec89 said ;-) Thanks again for the support.

**Comment by jgrossi** [comment]
Any update about this issue? Many thanks

**Comment by kriskbx** [comment]
I'm very busy with some client projects right now. :(
I will do my best to submit a PR within the next two weeks.

**Comment by jgrossi** [comment]
No problem @kriskbx! When possible send us the PR ;-) Cheers, and good luck.

**Comment by jgrossi** [comment]
@ChristianGiupponi it, this is a very big problem... one database query for each image.
I'm gonna try to fix that in the next hours and let you know

**Comment by jgrossi** [comment]
@ChristianGiupponi I made the changes, wrote a new test and I think everything is ok. Can you make a final test? I've created the `fix/issue-107` branch. Can you test it inside your app?

**Comment by ChristianGiupponi** [comment]
@jgrossi now the query are just a few:

<img width="942" alt="schermata 2016-04-29 alle 20 39 51" src="https://cloud.githubusercontent.com/assets/1614796/14926054/96891fee-0e4a-11e6-98c1-3789feb34b80.png">


 but I do not get the image url.

    Testimonial::published()->with('attachment')->orderBy(DB::raw('RAND()'))->take(3)->get();

and 
    `<img src="{{ $testimonial->image }}" alt="{{ $testimonial->title }}">`

`$testimonial->image` is empty

**Comment by jgrossi** [comment]
Nice! About the `->image` try again. I've updated the `Corcel\Post` class. Let me know, please.

**Comment by ChristianGiupponi** [comment]
Just pasted the zip content, `composer dump-autoload` and now I get:

~~~
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'testsite.postmeta' doesn't exist (SQL: select * from `postmeta` where `postmeta`.`post_id` = 56 and `postmeta`.`post_id` is not null and `meta_key` = _thumbnail_id limit 1)
~~~

**Comment by jgrossi** [comment]
Humm I know why. Give me a sec.

**Comment by jgrossi** [comment]
Can you check again @ChristianGiupponi? I missed the `hasOne()` method in the `Corcel\Model`, but now it should work. Let me know.

**Comment by ChristianGiupponi** [comment]
Ok, now the images shows up!  
But the number of query increased a bit ( but less then the first time )

- First time 30 queries ( images works )
- Second time 6 queries but images doesn't work
- Third time 14 queris and images works

<img width="1183" alt="schermata 2016-04-29 alle 20 59 21" src="https://cloud.githubusercontent.com/assets/1614796/14926645/699fc5fc-0e4d-11e6-9ca0-230645689f95.png">

**Comment by jgrossi** [comment]
Well, it's more than 50% hehe! Thanks for the help @ChristianGiupponi. I'm gonna merge that!

**Comment by ChristianGiupponi** [comment]
Sure, it's a good result right now!
