### ISSUE TITLE
Should post_type be fillable on Post model

### ISSUE THREAD

**Issue by mattKendon** [jgrossi/corcel#108]
Currently the only fillable attributes for a Post are `post_content`, `post_title`, `post_excerpt`, `to_ping`, `pinged`, and `post_content_filtered`. At the moment if I want to create a new Page using `Page::create($attributes)` I have to manually set the `post_type` separately and resave the post, or have the post saved with a `post_type` of 'post' as default. 

Should `post_type` therefore be fillable, or is that considered dangerous?

Any thoughts?

**Comment by jgrossi** [comment]
I don't think it's dangerous. Post type must be `post` by default. But I think there is no problem. Can you make a PR?

**Comment by mattKendon** [comment]
HI @jgrossi 

I've just created a pr for this #112 

Cheers!

**Comment by jgrossi** [comment]
Merged #112 ;-) Thanks
