### ISSUE TITLE
Categories & Taxonomies not implemented

### ISSUE THREAD

**Issue by masix** [jgrossi/corcel#109]
Hello,

You've mentioned how to use categories and taxonomies in Readme but it's not implemented:

Categories & Taxonomies
Get a category or taxonomy or load posts from a certain category. There are multiple ways to achieve it.

```
// all categories
$cat = Taxonomy::category()->slug('uncategorized')->posts()->first();
echo "<pre>"; print_r($cat->name); echo "</pre>";


// only all categories and posts connected with it
$cat = Taxonomy::where('taxonomy', 'category')->with('posts')->get();
$cat->each(function($category) {
    echo $category->name;
});

// clean and simple all posts from a category
$cat = Category::slug('uncategorized')->posts()->first();
$cat->posts->each(function($post) {
    echo $post->post_title;
});
```

**Comment by jgrossi** [comment]
Hi @masix! Let me check that for you, but all tests are passing. What error are you getting? Thanks

**Comment by masix** [comment]
Hi @jgrossi, the test is not either implemented for Taxonomy and Category classes.

**Comment by jgrossi** [comment]
Hummmm that's true. Give me a sec and I tell you @masix

**Comment by jgrossi** [comment]
We have indeed no Taxonomy neither Category classes. Sorry about that. I'm gonna remove that from README and create them ASAP @masix ;-)

**Comment by masix** [comment]
Thanks.

**Comment by jgrossi** [comment]
@masix I created some tests to the classes `Taxonomy` and `Category` in #111. Theses classes already exists but they are inside the `models` dir and are auto loaded by default by composer. All tests passed. 

Can you tell me what error message are you getting? Thanks

**Comment by masix** [comment]
I didn't checked the models folder, Its working and the tests passed.

Thank you very much.

**Comment by jgrossi** [comment]
You're welcome @masix. Just remember that the `models` folder is inside the default namespace, and the `src` folder is the classes under `Corcel` namespace. Any question just ask ;-)
