### ISSUE TITLE
Assigning connection for Relationships has broken non-wordpress model relationships

### ISSUE THREAD

**Issue by mattKendon** [jgrossi/corcel#113]
The project that I'm using Corcel on has a mix of `corcel` models and `eloquent` models. The `eloquent` models use a different `connection` to the `corcel` models, because the `corcel` connection has a `wp_` prefix. 

However, with the recent changes to Relationship methods on the `Model` class, relationships across connections (but on the same database) are no longer possible. The `hasMany` method applies the connection of the `corcel` model to the related `eloquent` model so that the related model now looks for a table with a prefix of `wp_`. 

By altering the connection in this way, we've made `corcel` models cut off from other parts of Laravel, which reduces the effectiveness of this library. 

A simple fix (but breaking backwards compatibility) would be to have new relationship methods for the `Corcel\Model` class, instead of overriding the `Eloquent\Model` classes `hasMany` method (and others). 

An alternative might be to update the `hasMany` method so that the boolean flag could be set altering the behaviour of applying the `connection` to the related model or not. 

```
public function hasMany($related, $foreignKey = null, $localKey = null. $applyConnection = true)
    {
        $foreignKey = $foreignKey ?: $this->getForeignKey();

        $instance = new $related();

        if ($applyConnection) {
            $instance->setConnection($this->getConnection()->getName());
        }

        $localKey = $localKey ?: $this->getKeyName();

        return new HasMany($instance->newQuery(), $this, $foreignKey, $localKey);
    }
```

What do people think?

**Comment by jgrossi** [comment]
@mattKendon what you need is a relationship between a Corcel model and a custom model (using Eloquent) created by you, and they are using different connections, right?

**Comment by mattKendon** [comment]
Exactly. My use case is that I have a following code:

```
class Show extends \Corcel\Post {
    protected $connection = 'wpdb'; //same as mysql, but with a 'wp_' prefix

    public function performances()
    {
        return $this->hasMany('Performance', 'id');
    }
}

class Performance extends \Eloquent\Model {
    protected $connection = 'mysql';

    public function show()
    {
        return $this->belongsTo('Show', 'ID')
    }
}
```

But the `hasMany` method on the Show class will set the Performance instance to have a connection of `wpdb` and so it's table name will be `wp_performances` rather than `performances`.

**Comment by jgrossi** [comment]
I gotcha... In my opinion we have some options:

1 - create a new `HasMany` classe like you said, and a new method like `hasManyAndStopConnection()`. This way we'll have to create `hasOne()`, `belongsTo()` and `hasManyAndBelongsTo()` methods and classes too.

2 - make this configurable in the class, like setting a class variable like `$followConnection = false` to disable that. The bad news is that this will apply to all relationships  inside that class.

3 - modify `HasMany` and all relationship classes (inside Corcel namespace) to return a different instance, which we'll create a method like `persistConnection($persist = false)` so we can use `return $this->hasMany(/*...*/)->persistConnection(false);`

I **really** don't know what to do hehe. Maybe we can wait a little to get more opinion about the others contributors or think in a better and easier idea ;-)

Any suggestion just let me know...

**Comment by jgrossi** [comment]
Any ideas @josec89 @rundef?

**Comment by jgrossi** [comment]
@mattKendon or:

4 - create a method inside `Model` class to disable that, but so you need to make this by hand like `Show::find(1)->disablePersistenceFor('Performance')->performances` (I really didn't like that hehe)

5 - you can stop the propagation of the connection inside your own `hasMany()` method too, like `Show::find(1)->performances($disableConnection = false)->get()` and inside that method develop the logic to set the connection you want to be used. (a very good option too)

And thinking :-)

**Comment by mattKendon** [comment]
@jgrossi, option 2 would not fix the problem that I have, which is that some but not all of my connections for the `Show` model will be to `Eloquent` models. 

Option 5 wouldn't work as there are no cases that I can think of where I would want to do the following:

```
//performances from the performances table
Show::find(1)->performances(true)->get();

//performances from the wp_performances table
Show::find(1)->performances(false)->get()
```

It would be better if that was just defined in the `performances` method, like:

```
public function performances()
{
    return $this->hasMany('Performance', 'id', 'ID, true);
}
```

Option 5, therefore is the suggestion that I made in my first post, I think. 

```
public function hasMany($related, $foreignKey = null, $localKey = null. $applyConnection = true)
    {
        $foreignKey = $foreignKey ?: $this->getForeignKey();

        $instance = new $related();

        if ($applyConnection) {
            $instance->setConnection($this->getConnection()->getName());
        }

        $localKey = $localKey ?: $this->getKeyName();

        return new HasMany($instance->newQuery(), $this, $foreignKey, $localKey);
    }
```

Unfortunately, I don't think that updates to the `Relation` models will help. The issue is with the `Eloquent\Builder` that is passed through and generated from the `$instance->newQuery()` Unfortunately, this `Eloquent\Builder` model doesn't allow the change of the `connection` after it has been generated, so the `Relation` model couldn't be made to update it internally.

Therefore I think that option 1 and option 3 wouldn't work.

**Comment by jgrossi** [comment]
Ok, no problem. Let's wait for more suggestions :-)

**Comment by mattKendon** [comment]
I've just created a pull-request with my suggestion on how non-corcel relationships would work. See #114 for more details. 

Its ready to be merged, but I would definitely appreciate feedback on it, as it may not be the best option.

**Comment by jgrossi** [comment]
Ok @mattKendon thanks ;-) Let's wait a little to more opinions and I'll merge that. Thanks again

**Comment by mattKendon** [comment]
After further development, I don't think this is the way to go. 

Having models that communicate across connections is not really feasible with Eloquent. The issue I came up against just now was creating a custom scope where I needed to join with the `Performances` table. However, when writing this on the `Show` model, which uses `corcel`, the connection used to join the `performances` table auto-prefixes the table with `wp_`. Something like this:

```
    public function scopeOrderByPerformanceDate($query, $direction = 'asc')
    {
        return $query->join('performances', 'posts.ID', '=', 'performances.show_id')
            ->groupBy('performances.show_id')
            ->orderBy('performance_time', $direction);
    }
```

won't work because the `$query` will try to add a join to a `wp_performances` table. 

This suggests that having `corcel` models and `eloquent` models using different connections (one prefixed with `wp_` and the other not) will always limit any relationships between the two. 

My suggestion would be to add support prefixing `corcel` tables within the model itself. something like this:

```
namespace Corcel;

class Model extends Eloquent {
    protected $prefix = false;

    
    /**
     * Get the table associated with the model.
     *
     * @return string
     */
    public function getTable()
    {
        $table = parent::getTable();
        if ($this->prefix) {
            $table = $this->prefix . $table;
        }

        return $table;
    }

}

`corcel` can now (but doesn't have to) prefix it's tables from within the model, and so can share a connection with `eloquent` models that aren't similarly prefixed.

**Comment by jgrossi** [comment]
Hi @mattKendon. I think you can set the connection to the `$query` variable: `$query->setConnection('...')`.

I don't think this last approach is better. The prefix must be a connection problem, not a model problem.

**Comment by mattKendon** [comment]
I think I'll just have to prefix all my tables, regardless of whether or not they are part of wordpress.

I agree that prefixes should be part of the connection and not part of the model.

**Comment by mattKendon** [comment]
I've gone with removing the prefix from the wordpress tables instead. That feels cleaner for me. 

This issue can be closed as the problem is one that cannot be resolved by Corcel, that in eloquent joins cannot be made between models on different connections.
