### ISSUE TITLE
help pls

### ISSUE THREAD

**Issue by DeeJaVu** [jgrossi/corcel#115]
hello how am i supposed to render

`[video width="380" height="286" webm="video.webm" loop="true" autoplay="true" preload="auto"][/video]` ?

**Comment by josec89** [comment]
You are taking the information directly from the DB not the *compiled* HTML that WP offers... For this you will have to process the information yourself and render it in the frontend

**Comment by DeeJaVu** [comment]
im using `$posts = Post::published()->get();`

can you tell me a example how i should do it instead pls im trying to learn this

**Comment by josec89** [comment]
I suggest using *Advanced Custom Fields* to add extra fields to you posts, videos for example. 
Then you get the needed information from the post (from *meta*s probably) and render it with te html *video* tag

**Comment by jgrossi** [comment]
Hi @DeeJaVu! Corcel gets the data directy from the database. If you store the HTML video tag in post content you can do something like `echo $post->content` or if you are using custom field like advanced custom fields like @josec89 said you can do `$post->meta->video` for example.

**Comment by jgrossi** [comment]
Closing this issue. Any question just ask again. Thanks @DeeJaVu and @josec89
