### ISSUE TITLE
Post meta data array stored as serialized string are not unserializing on access

### ISSUE THREAD

**Issue by jedrzejchalubek** [jgrossi/corcel#119]
I've storing custom post meta as single record and serialized array:

```php
["toggle" => false]
```
```
wp_postmeta

meta_id |  post_id  |  meta_key  |  meta_value
==================================================================
6       |  6        |  info      |  a:1:{s:6:"toggle";s:5:"false";}
```

Accessing single post meta in loop returns unserialized value. There is any way to make it return array without manual unserializing?

```php
$books = Post::type('book')->status('publish')->get();

@foreach ($books as $book)
	// returns "string 'a:1:{s:6:"toggle";s:4:"true";}'"
	{{ var_dump($book->meta->info) }}
@endforeach
```

Did I missed something?

**Comment by jgrossi** [comment]
Hi @jedrzejchalubek sorry about the late answer. About your question, yes and this is already implemented. I'm gonna check that for you and I give you an answer in a couple of hours, ok? Thanks

**Comment by jedrzejchalubek** [comment]
Thanks. I've make my own research. We need to add accessor in PostMeta class.

`
public function getMetaValueAttribute($value)
    {
        try {
            return unserialize($value);
        } catch (Exception $e) {
            return $value;
        }
    }
`

Existing `getValueAttribute` method confused me and I was thinking this is already implemented :)

**Comment by jgrossi** [comment]
Hi @jedrzejchalubek It's already implemented. I'm finishing the PR ;-)

**Comment by jgrossi** [comment]
Done @jedrzejchalubek #126

**Comment by jedrzejchalubek** [comment]
Great. Thanks 👍
