### ISSUE TITLE
Call to undefined method Illuminate\Database\Query\Builder::hasMeta()

### ISSUE THREAD

**Issue by ndarupurnomo** [jgrossi/corcel#120]
Hi,

The package were tested on localhost and it's OK.

But when deployed to my website, it gives error message:

ErrorException in Builder.php line 2251:
Call to undefined method Illuminate\Database\Query\Builder::hasMeta()

I checked config/database.php and made necessary changes.

Please help.

**Comment by ndarupurnomo** [comment]
Looks like something to do with Laravel's Auth, the one I added with 'php artisan make:auth'. 

Solved problem temporarily by logging out.

**Comment by jgrossi** [comment]
Ok @ndarupurnomo thanks for the feedback. If the problem continues please tell us. Thanks!
