### ISSUE TITLE
Validate users passwords againt saved passwords by wordpress

### ISSUE THREAD

**Issue by masix** [jgrossi/corcel#121]
Hi,

I've implemented the users authentication but it seems that the check is not working with users passwords but the tests are working. So i dig into the password service provider, and i found that you use BcryptHasher to check the password if it's not an MD5, then made a little test:

- I've create a user in "wp admin" using "admin" as username and "admin" as password.
- Then i've checked the database to get the hashed password : $P$BrYiES.08ardK6pQme0LdlmQ0idrIe/
- It's not an MD5, so i've used BcryptHasher to check it:

$hasher = new BcryptHasher();
dd($hasher->check('admin', '$P$BrYiES.08ardK6pQme0LdlmQ0idrIe/'));

And the result is false.

**Comment by jgrossi** [comment]
Hi @masix! Did you create the user using the WP Admin Panel or by hand?

**Comment by masix** [comment]
Hi @jgrossi, i've created the account by wordpress panel, i've tried 3 account with 3 different password, and no one of them is working.

**Comment by jgrossi** [comment]
If you want to check for the password use:

```
$checker = new Corcel\Password\PasswordService;
$hash = $checker->wp_hash_password('$P$BrYiES.08ardK6pQme0LdlmQ0idrIe/');
var_dump($checker->wp_check_password('$P$BrYiES.08ardK6pQme0LdlmQ0idrIe/', $hash));
```

If it fails please tell me! Cheers ;-)

**Comment by masix** [comment]
Hi @jgrossi , yes it fails.

**Comment by jgrossi** [comment]
I've updated the methods name. Did you use them correctly? Check the changes:

```
$checker = new Corcel\Password\PasswordService;
$hash = $checker->makeHash('$P$BrYiES.08ardK6pQme0LdlmQ0idrIe/');
var_dump($checker->check('$P$BrYiES.08ardK6pQme0LdlmQ0idrIe/', $hash));
```

If you still getting errors message please let me know them to help you. Thanks.

**Comment by masix** [comment]
hi @jgrossi , it works, because you made the hash using makeHash(). you must add a user from wordpress panel copy the password from the database and try to check it with the plain password, i've tried it with a fresh installation of wordpress and it doesn't work. it same that the way wordpress is hashing passwords is different.

```
$checker = new Corcel\Password\PasswordService;
$password = 'admin';
var_dump($checker->check('$P$BrYiES.08ardK6pQme0LdlmQ0idrIe/', $password));
```

**Comment by jgrossi** [comment]
Hi @masix! The `check()` method check if a hash is equal another one, not comparing plain texts. Please, check this line:

```
var_dump($checker->check('$P$BrYiES.08ardK6pQme0LdlmQ0idrIe/', $password));
```

It must be:

```
var_dump($checker->check('admin', '$P$BrYiES.08ardK6pQme0LdlmQ0idrIe/')); // OR
var_dump($checker->check('admin', $checker->makeHash('admin'));
```

Now you're comparing hash to hash. Ok?

**Comment by rundef** [comment]
Hey @masix , I tested and you were right. 
@jgrossi The current algorithm that we use doesn't match the one in WordPress.

I tested with [phpass](https://github.com/hautelook/phpass) and it worked just fine (this is exactly the package that WordPress uses), but it's the package that require a higher version of PHP.

The current hasher we use [is this one](https://github.com/laravel/framework/blob/5.2/src/Illuminate/Hashing/BcryptHasher.php).

But the password encryption is implemented differently in WordPress :
[wp_hash_password](https://github.com/WordPress/WordPress/blob/a311bea6d11bceabfff96ed03a9908ff7ba10505/wp-includes/pluggable.php#L2005-2015)
[wp_check_password](https://github.com/WordPress/WordPress/blob/a311bea6d11bceabfff96ed03a9908ff7ba10505/wp-includes/pluggable.php#L2041-2078)
[PasswordHash](https://github.com/WordPress/WordPress/blob/a311bea6d11bceabfff96ed03a9908ff7ba10505/wp-includes/class-phpass.php)

Also, if you generate a hash for the same password multiple times, the hash will never be the same, so you can't compare hash-to-hash.
```php
$checker = new PasswordService;
$hashFoundInDb = '$P$BrYiES.08ardK6pQme0LdlmQ0idrIe/';
$hash = $checker->makeHash('admin'); 
var_dump($hash); // should not matches the hash found in db
var_dump($checker->check('admin', $hashFoundInDb)); // should be true
var_dump($checker->check('admin', $hash)); // should be true
```

**Comment by jgrossi** [comment]
@rundef Yes, you're right. `illuminate/hashing` generates a new salt every `make()` call. But also `phpass` does that. I've tested here 50 iterations using `hautelook/phpass` and each hash is different...

**Comment by masix** [comment]
@rundef @jgrossi , you can't compare the two hashes, this is for MD5 but for the new hash the algorithm generate new hash each time, and to check if the password is correct, I guess that the algorithm crypt the password with the hash and the result must be the same hash or the same password, this is how the algorithm checks if the password is correct os wrong.

**Comment by jgrossi** [comment]
Understood @masix... The problem here is not the hash algorithm but how to verify this without WordPress, using our own code. @rundef this `phpass` version WP uses is older than that that requires PHP >= 5.6? I could not find it through composer.

**Comment by rundef** [comment]
[phpass 0.3.4](https://packagist.org/packages/hautelook/phpass#0.3.4) requires only php>=5.3.3, maybe we should use that version.

**Comment by jgrossi** [comment]
@rundef ok, I've tested with version 0.3.4 of phpass, but as all password hashing libraries each hash is different...

**Comment by masix** [comment]
@rundef , i've just tested it:
- PHP5.6 => works
- PHP5.5 => not working
- PHP5.4 => not working

I've check the code and it seems using the php function hash_equals() which is available just in (PHP 5 >= 5.6.0, PHP 7). So it requires PHP5.6 or Above.

**Comment by jgrossi** [comment]
I'm running PHP 7 and it's not working...

**Comment by masix** [comment]
@jgrossi , i've just tested with PHP7.0.1 and it works fine.

```php
use Hautelook\Phpass\PasswordHash;

require_once(__DIR__ . "/vendor/autoload.php");

$passwordHasher = new PasswordHash(8,false);

$passwordMatch = $passwordHasher->CheckPassword('admin', '$P$BrYiES.08ardK6pQme0LdlmQ0idrIe/');
var_dump($passwordMatch);
```

**Comment by jgrossi** [comment]
It's working now :-) I'm gonna make the changes to use version 0.3.4 in Corcel.

**Comment by masix** [comment]
@jgrossi , by the way, you used hash_equals() php function in password service to compare the MD5 hash. This function "hash_equals()" require PHP5.6 or above, and in Packagist you mentioned that the library require PHP5.4 in which this function doesn't exists.

You have to change the required version of PHP to 5.6 OR replace the function hash_equals() to a simple string comparing in PHP.

**Comment by jgrossi** [comment]
Thanks @masix very good observation. I'm unable to create the pull request right now, can you do that?

**Comment by masix** [comment]
OK, i will send it

**Comment by jgrossi** [comment]
Thanks @masix

**Comment by jgrossi** [comment]
I'm closing this issue. Any question or suggestion just let me know ok? Many thanks @masix and @rundef for helping.
