### ISSUE TITLE
How to paginate?

### ISSUE THREAD

**Issue by ChristianGiupponi** [jgrossi/corcel#128]
I tried to paginate results by using `paged` instead of `paginate` and I'm able to retrieve the first results:

`Testimonial::published()->paged(5)`

But when I try to print the pagination with:

`$testimonials->render()` 

I get:

~~~
Call to undefined method Illuminate\Database\Query\Builder::render() 
~~~

How should I use it?

**Comment by jgrossi** [comment]
Hi @ChristianGiupponi! Thanks for the message. I'm gonna check what's happening and I tell you, but this should be working. Thanks!

**Comment by ChristianGiupponi** [comment]
Thanks @jgrossi, right now I have implemented a custom `Paginator`

**Comment by jgrossi** [comment]
@ChristianGiupponi there's no `render` method using the `paged` method. We have to implement that yet (will be a nice contribution) but using `paginate` (Laravel default) should work. Can you try that?

**Comment by jgrossi** [comment]
@ChristianGiupponi We were having some problems with pagination in the past so we created the `paged` method, but I think this issue was fixed.

**Comment by rundef** [comment]
[Eloquent's builder paginate function](https://github.com/laravel/framework/blob/30f3ce73ae9c4d2fcaf7da1d2447375694d97852/src/Illuminate/Database/Eloquent/Builder.php#L456-471) returns an instance of `LengthAwarePaginator`, which contains the [`render` method](https://github.com/laravel/framework/blob/2a38acf7ee2882d831a3b9a1361a710e70ffa31e/src/Illuminate/Pagination/LengthAwarePaginator.php#L128-137) @ChristianGiupponi is talking about.

There's [no such thing in Corcel](https://github.com/jgrossi/corcel/blob/a86484567c059b1d5562fbc2fff3e4b1c83e699d/src/PostBuilder.php#L85-90). It might be a good idea to implement it.

**Comment by jgrossi** [comment]
Yes! I'll be very good @rundef let's think about that! Thanks for answering.

**Comment by rundef** [comment]
@ChristianGiupponi you can also use Laravel's paginate method directly :

```php
$testimonials = Testimonial::published()->paginate(5);
$testimonials->render();
```

**Comment by jgrossi** [comment]
@ChristianGiupponi can we close this issue?
