### ISSUE TITLE
Add CI to tests + code style check

### ISSUE THREAD

**Issue by luizpedone** [jgrossi/corcel#135]
Hi,

I think it would be nice to have a CI tool running the tests and checking the code style. I think it would help the reviewing process and make developers aware of their mistakes before any review.

I think [Travis CI](https://travis-ci.com/plans) and [Style CI](https://styleci.io/) would do the trick.

I can help making it work if you guys like the idea. ;)

Thanks for the project!  :)

**Comment by jgrossi** [comment]
You're welcome @luizpedone. That sounds awesome! Of course this is a great idea. Go ahead.

**Comment by luizpedone** [comment]
@jgrossi Great!

I can do the configuration, but you (or anyone with repository's admin privileges, I guess) must enable the Travis CI account there. If I'm not mistaken, all you need to do is enable [Travis CI for this repo on their website](https://travis-ci.org/).

I think it's the same thing you need to do at [Style CI website](https://styleci.io/).

If you need any help, let me know. =)

**Comment by jgrossi** [comment]
@luizpedone Travis CI and Style CI already enabled for the Corcel repo. Thanks!
