### ISSUE TITLE
Code examples for custom post type are wrong

### ISSUE THREAD

**Issue by Eworm** [jgrossi/corcel#137]
I tried using the code examples for the custom post type, but couldn't get them to work. Then I changed
```
$videos = Post
```
to
```
$videos = App\Post
```
and it worked! Are the code examples missing something or am I just doing it wrong?

**Comment by jgrossi** [comment]
Hi @Eworm! If you're using the default connection just use `Post::method()` and everything will work. If you are using another connection, so you had to create your own `App\Post` class, setting the `protected $connection = 'name'; `, so you should use `App\Post::method()`.

Any question just ask. Thanks for contributing.

**Comment by Eworm** [comment]
Thanks for the explanation. Maybe you could add this short explanation to the readme? Might save someone else some time.

**Comment by jgrossi** [comment]
That's a very good ideia. I'm gonna do that. Thanks!
