### ISSUE TITLE
How to convert shortcode into the  content

### ISSUE THREAD

**Issue by alanhr** [jgrossi/corcel#144]
Hi,guy
I have a little problem, I need convert the shortcode that came with the content.
Do you have some method that do this ?

**Comment by rundef** [comment]
Hello,

No there is nothing to convert shortcodes within corcel.
I guess one could simply override the **Post::getContentAttribute** method to find and replace shortcodes.

But I think, it would be cool to be able to [add shortcodes](https://codex.wordpress.org/Shortcode_API) from within Corcel. 

By the way, you're free to contribute if you have ideas on how to implement this - check out the **Contributing** section of the readme :smiley: 
Thanks

**Comment by alanhr** [comment]
I found this [repository](https://github.com/thunderer/Shortcode)  that has a similar implementation shortcode.
If we use this repository, It would not be a good start?

**Comment by jgrossi** [comment]
Hi @alanhr! Thanks for the suggestion. Is this repository working great? Maybe is possible you can try it and tell us the results, and so we can implement it inside Corcel.  What do you think?

**Comment by alanhr** [comment]
Ok, no problem. Tomorrow I'll try to do something with this lib and send for you @jsgroddi the repository with the test.

**Comment by jgrossi** [comment]
Ok @alanhr thanks for contributing with Corcel.

**Comment by thunderer** [comment]
@jgrossi Hi, I'm the author of that Shortcode library. Should you have any questions or ideas, let me know, I'll be more than happy to discuss them. It's used in production for more than year now and I'm still supporting it, so no worries, it's reliable.

**Comment by jgrossi** [comment]
Hi @thunderer thanks for the support. We're thinking to use your Shortcode Library inside Corcel. Any problems for you? Thanks

**Comment by thunderer** [comment]
I don't see any problems, I'll be really happy to see (and possibly help) integrating Shortcode into Corcel. :)

**Comment by jgrossi** [comment]
Thanks @thunderer! Any help we'll contact you. Best regards.

**Comment by alanhr** [comment]
@jgrossi sorry guy , I didn't have time for  to do the test with shortcode , but I'm so happy with integragion the Corsel and ShortCode

**Comment by jgrossi** [comment]
Hi @alanhr, no problem. I'm already working on it. Maybe we'll have some good news soon. Valeus!

**Comment by jgrossi** [comment]
Hi @alanhr, no problem. I'm already working on it. Maybe we'll have some good news soon. Valeus!

**Comment by webwizo** [comment]
I have just create a shortcode with Laravel 5.x.
Maybe it will be helpful with Corcel. I will also need to use Shortcodes for my project while Corcel is very helpful for me.

[Laravel Shortcodes](https://github.com/webwizo/laravel-shortcodes)

Thanks,

**Comment by jgrossi** [comment]
HI guys! @rundef did the `shortcodes` integration in Corcel. You can check that in `v1.1.0`. Thanks
And thanks @rundef for helping.
