### ISSUE TITLE
require autoload gives fatal error

### ISSUE THREAD

**Issue by Grezvany13** [jgrossi/corcel#146]
In /jgrossi/corcel/src/Password/PasswordService.php at line 7 is a (left-over) require_once to the /vendor/autoload.php, which breaks since the path to the file does not exist.

I've added PR #145 to solve this issue (and added the error and reason with it).

**Comment by Grezvany13** [comment]
Has been fixed in PR #148 in dev-branch (now waiting for release ;) )

**Comment by jgrossi** [comment]
Thanks @Grezvany13 ;-)

**Comment by jgrossi** [comment]
Release at `v.1.0.8` @Grezvany13 thanks!
