### ISSUE TITLE
why not just go on and drop the wordpress backend and build ours 

### ISSUE THREAD

**Issue by mohamedsharaf** [jgrossi/corcel#150]
why not just go on and drop the wordpress backend and build ours

**Comment by josec89** [comment]
Wordpress is a very reliable CMS with tons of plugins, and many clients are more fond to use a product that is already known such as Wordpress.

I think the idea of Corcel is to use Wordpress in a beautiful easy way for the developers. 

- Clients happy using a well known and ultra-easy, user-friendly CMS
- Developers are happy making great things taking the information from the CMS

But that's only my opinion :)

**Comment by mohamedsharaf** [comment]
i see and i have a look at what u made is really amazing

but not all clients love wordpress 

also not all developer like wordpress 

why not you make options i think most developer will like yours instead of wp

**Comment by josec89** [comment]
I think that would be a really good project - making a whole CMS very dev-friendly. But I don't thing this project can become what you are suggesting: the purpose of this project is to make easy the integration with WP and beautify the field names.

Wait to see what @jgrossi has to say :)

**Comment by mohamedsharaf** [comment]
i think it can make competition one day with wordpress 

developer will love it i am sure

**Comment by ramon-villain** [comment]
@mohamedsharaf you have a bunch of options actually. PyroCMS, Statamic, OctoberCMS, AnchorCMS… I'm pretty sure this is not the propose of this repository, make another CMS.

**Comment by jgrossi** [comment]
Hi @mohamedsharaf! As @josec89 said before, the goal of Corcel is to allow you to use WordPress backend with any PHP application you have. You have a lot of CMS's you can choose, like @ramon-villain said, but the Corcel project cover only WordPress, allowing you to still using WP but choosing the PHP framework you want to use in the front end.

And as @josec89 said, the purpose of Corcel is not to replace WP. You cannot replace a project like that. What Corcel is doing here is to integrate the CMS with others PHP projects, like a Wrapper.

Any question just ask. Thanks for the comment.
