### ISSUE TITLE
Post excerpt

### ISSUE THREAD

**Issue by EdisonLV** [jgrossi/corcel#161]
~~~~~
    public function getExcerptAttribute()
    {
        return $this->post_excerpt;
    }
~~~~~

it looks like it does not return anything...

**Comment by jgrossi** [comment]
Hi @EdisonLV! Welcome! About your question, others method, like `getTitleAttribute()` are working? Or is only this one returning nothing? Thanks

**Comment by rundef** [comment]
Hi,

I did add a new unit test on the dev branch (to test the accessors), and everything is working as expected.
Could you paste your code if you're still experiencing problems?
Thanks

**Comment by EdisonLV** [comment]
Hi and thanks for the reply. 
~~~~~
getTitleAttribute()
~~~~~
does work, but 
~~~~~
getExcerptAttribute()
~~~~~
returns *NULL*

**Comment by josec89** [comment]
You shouldn't call those methods directly, they are used by *Eloquent* to fill some fields in the model

You should call something like:

```
$post = Post::find(5); // Get a post 
echo $post->title; // Should show the title of the post
echo $post->excerpt; // Should show the excerpt of the post
```

if you are getting `null` in your excerpt it must be because your post didn't fill the `post_excerpt` field in the database => Check if that value appears in the DB. https://codex.wordpress.org/Excerpt

Hope it helped

**Comment by EdisonLV** [comment]
I did not know that it needs excerpt value to be stored manually, Thank you everyone for the replies.

**Comment by jgrossi** [comment]
Hi @EdisonLV! You're welcome. Any question just ask. Best.

**Comment by kovalski** [comment]
```
use Corcel\Post;

class WpPost extends Post
{
    /**
     * Gets the excerpt attribute.
     *
     * @return string
     */
    public function getExcerptAttribute()
    {
        $excerpt = trim(parent::getExcerptAttribute());

        if (empty($excerpt)) {
            $content = preg_split('/<!--more(.*?)?-->/', $this->content);

            if (count($content) > 1) {
                return current($content);
            }
        }

        return $this->title;
    }
}
```

**Comment by jgrossi** [comment]
Hi @kovalski can you include this into a PR? Thanks.
