### ISSUE TITLE
All post queries appear to have unnecessary postmeta query

### ISSUE THREAD

**Issue by QWp6t** [jgrossi/corcel#162]
I noticed that even doing something as simple as the following...
```php
Page::slug('home')->first();
```

will result in the following 3 queries:
```sql
select * from "wp_postmeta" where "post_id" is null and "post_id" is not null
select * from "wp_posts" where "post_type" = ? and "post_name" = ? limit 1
select * from "wp_postmeta" where "post_id" in (?)
```
(I didn't bother including the bindings since they're inconsequential)

The following query is unnecessary and costly:
```sql
select * from "wp_postmeta" where "post_id" is null and "post_id" is not null
```

If you're using Laravel 5.2, you can find this yourself by listening to query executed event, i.e...
```php
\Event::listen('Illuminate\Database\Events\QueryExecuted', function ($query) {
    var_dump($query->sql);
});
```

**Comment by jgrossi** [comment]
Hi :-) This is because `protected $with = ['meta'];` inside `Post` class. It loads by default any meta data related to the current post. In a simple case like yours you'll have one more empty query, but in cases where you have to get multiple meta data you'll have only one query to do that too. Removing this you will have one new query per meta data.

If you are using your own `Post` class, for example, you can set `protected $with = [];` to remove this extra load, but after, to get meta data using only one query, you'll have to do something like `Post::with('meta')->find(3);`.

Thanks ;-)

**Comment by QWp6t** [comment]
That makes sense for the 3rd query in the the set above, but I don't think that makes sense for the 1st query. It's hitting the postmeta table before it ever hits the posts table. This seems like a mistake; it can't know the post_id prior to looking up the post itself.

In short, this query will never return anything:
```sql
select * from "wp_postmeta" where "post_id" is null and "post_id" is not null
```

Expected behavior here should be to look up the posts in the posts table, grab the post IDs, and then query the postmeta table with the set of IDs ... which is what you're describing and what is in the 2nd and 3rd queries above:
```sql
select * from "wp_posts" where "post_type" = ? and "post_name" = ? limit 1
select * from "wp_postmeta" where "post_id" in (?)
```

Those two queries make sense, but I don't see how the 1st query can ever do anything useful. I think there should be a guard in place to prevent it, but I don't know enough about the inner working of eloquent / query builder to do it myself.

**Comment by jgrossi** [comment]
Hi @QWp6t. The point is that `with` is made by Eloquent. Maybe we could try to call `->with()` in the relationship, like in `meta()` method. Can you do that and tell us the results? Test with no meta data and 2 or more to see the difference. Thanks.

**Comment by QWp6t** [comment]
Is this what you're looking for?

```php
var_dump('test 1: page by slug');
Page::slug('home')->first();

var_dump('test 2: page with meta, limit 1');
Page::with('meta')->first();

var_dump('test 3: pages with meta, limit 3');
Page::with('meta')->find(3);
```

**test 1: page by slug**
```sql
select * from "wp_postmeta" where "post_id" is null and "post_id" is not null
select * from "wp_posts" where "post_type" = ? and "post_name" = ? limit 1
select * from "wp_postmeta" where "post_id" in (?)
```


**test 2: page with meta, limit 1**
```sql
select * from "wp_postmeta" where "post_id" is null and "post_id" is not null
select * from "wp_posts" where "post_type" = ? limit 1
select * from "wp_postmeta" where "post_id" in (?)
```

**test 3: pages with meta, limit 3**
```sql
select * from "wp_postmeta" where "post_id" is null and "post_id" is not null
select * from "wp_posts" where "post_type" = ? and "wp_posts"."ID" = ? limit 1
```


As you can see, each one still begins with unnecessary query:
```sql
select * from "wp_postmeta" where "post_id" is null and "post_id" is not null
```

**Comment by rundef** [comment]
Hey @QWp6t ,
Can you try with the **dev** branch ?
The extra query shouldn't be there anymore.

Thanks

**Comment by QWp6t** [comment]
Yeah, that's perfect.

Thanks.
