### ISSUE TITLE
Undefined property: App\Models\Wp::$meta

### ISSUE THREAD

**Issue by tanteng** [jgrossi/corcel#170]
ErrorException in compiled.php line 11580: Undefined property: App\Models\Wp::$meta

It's broken after running command: php artisan optimize.

How?

**Comment by jgrossi** [comment]
Hi @tanteng welcome! What's is the content of `Wp.php`?

**Comment by tanteng** [comment]
The class Wp extends the Corcel.

```
<?php
namespace App\Models;

use Corcel\Post as Corcel;

class Wp extends Corcel
{
    protected $connection = 'wordpress';
    protected $domain = 'http://blog.tanteng.me/';

    //重写获取wordpress文章url方法
    public function getUrlAttribute()
    {
        return $this->domain.date('Y/m/',strtotime($this->post_date)).$this->slug.'/';
    }
}
```

**Comment by jgrossi** [comment]
Weird. Which version of Corcel are you using?

**Comment by tanteng** [comment]
[http://www.tanteng.me/blog](url)

**Comment by tanteng** [comment]
"jgrossi/corcel": "^1.0",

**Comment by jgrossi** [comment]
Change to `"jgrossi/corcel": "^1.1.0"` and `composer update`, please.

**Comment by tanteng** [comment]
- Removing jgrossi/corcel (v1.0.7)
  - Installing jgrossi/corcel (v1.1.0)
    Downloading: 100%  

Now is OK. Thanks a million.

Welcome to visit [http://www.tanteng.me/blog](url)

**Comment by jgrossi** [comment]
You're welcome @tanteng. And thanks for using Corcel.
