### ISSUE TITLE
Creating WP_Post

### ISSUE THREAD

**Issue by Tomasseee** [jgrossi/corcel#171]
How can i create new wordpress post within laravel?
I have one custom field too.

Thank you.

**Comment by jgrossi** [comment]
Hi @Tomasseee thanks for the message. As you can see in the project documentation you can create a new post using:

```
$post = new Post;
$post->save();

$post->meta->username = 'juniorgrossi';
$post->meta->url = 'http://grossi.io';
$post->save();
```

Best regards.

**Comment by jgrossi** [comment]
Hi @Tomasseee. Did that fix your problem? Please let me know any issues. Best.

**Comment by Tomasseee** [comment]
I have error:
Class 'App\Http\Controllers\App\Post' not found

However i have Post.php in App folder. Which contains:
```
<?php // File: app/Post.php

namespace App;

use Corcel\Post as Corcel;

class Post extends Corcel
{
    protected $connection = 'wordpress';
}
```

One controller where i call $posts = App\Post::all(); from:
`<?php

namespace App\Http\Controllers;

use App\Http\Controllers\Controller;
use App\Post;

class TestController extends Controller
{

	public function posts()
	{
		$posts = App\Post::all();
		var_dump($posts);
	}

}`

And thats all, what could be the problem?

**Comment by Tomasseee** [comment]
Okay, it works like this:
$posts = Post::all();

**Comment by jgrossi** [comment]
Hi @Tomasseee no problem. Did you say when saving the post it does not set the `post_type`? It should work :)

**Comment by Tomasseee** [comment]
It saves, when i define, but when undefined no default, and the posts were not saved.
$post->post_type = 'post';
It is not insert without this.

**Comment by Tomasseee** [comment]
``
