### ISSUE TITLE
WooCommerce 

### ISSUE THREAD

**Issue by devmsh** [jgrossi/corcel#172]
Is there any plan or current implementation for WooCommerce post types?

**Comment by jgrossi** [comment]
Hi @devmsh. Not for now :(
But you can still use Corcel with WooCommerce, just mapping the products table with custom models extending Corcel. And, of course, you can contribute sharing your mapping feature too :) Thanks and best regards.

**Comment by devmsh** [comment]
Thanks for your quick response, I will discuss the idea with my team, and surly we will contribute with the WooCommerce if we decide to developed them.

**Comment by devmsh** [comment]
I think we need to support two different type of models, the WooCommerce post-types, and the installed extra tables mentioned here: https://github.com/woothemes/woocommerce/wiki/Database-Description

If you have any initial ideas, consideration, or suggestion, please let me know.

**Comment by jgrossi** [comment]
You're welcome. I think we do not need everything from WooCommerce for now, but start the initial support. We can store everything under the `WooCommerce` namespace, so we'll have `WooCommerce\Order` mapping the `woocommerce_order_items` table, for example. The post type Corcel already has support to that, so it will be ease for now.

Any question just ask, please. Cheers.

**Comment by jgrossi** [comment]
Hi @devmsh. Can we close this issue? Any question?
