### ISSUE TITLE
How to get Parent sub categories ?

### ISSUE THREAD

**Issue by mansouralex** [jgrossi/corcel#174]
Is it possible to retrieve sub categories of a single Parent Category ?

**Comment by jgrossi** [comment]
Hey @mansouralex! Yes it it:

```
$cat = Taxonomy::where('taxonomy', 'category')->get();
$cat->each(function($category) {
    echo $category->parentTerm()->name;
});
```

**Comment by mansouralex** [comment]
@jgrossi thanks. It look like it's not working.

`$category->parentTerm()->first()` and `$category->parentTerm` returns null.

Is there anything wrong ?

**Comment by jgrossi** [comment]
@mansouralex does your category has a parent id? This method only returns a new `TermTaxonomy` instance according the `parent` column on `term_taxonomy` table, so if the parent is 0 it will be null. Please, make sure the category you are looking has a `parent > 0`.

**Comment by mansouralex** [comment]
Thank you @jgrossi working. I just had to make a check as not all categories has parent.

**Comment by jgrossi** [comment]
You're welcome @mansouralex!
