### ISSUE TITLE
Corcel with UserFrosting

### ISSUE THREAD

**Issue by bsoner** [jgrossi/corcel#175]
i couldn't make Corcel work with UserFrosting.I am sure i am making a simple mistake because i am a newbie for php.
I couldn't find any documents.
I need just an example, thats all.
how can i add second connection for wordpress in Slim Framework(UserFrosting uses Slim)?
i can share ftp/db/wordpress credentials if necessary.

**Comment by jgrossi** [comment]
Hi @bsoner can you send us part of your code? About adding another connection you can use the `addConnection()` method:

```
$conn = Corcel\Database::connect(array(
    'database'  => 'database_name',
    'username'  => 'username',
    'password'  => 'pa$$word',
    'prefix'    => 'wp_',
));
$conn->addConnection(/* others params */);
```

**Comment by bsoner** [comment]
@jgrossi thank you for such a quick replay.
I have no code at all now.I tried to connect my Wordpress Database for hours and i just gave up and wrote here.
now i have UserFrosting (https://github.com/userfrosting/UserFrosting/) and Corcel.
Like i said i am not a php guy but all i need is an example.
I already add some other pages(nothing about Wordpress or Corcell)
now all what i want to do is to connect my Wordpress(on another server) and get categories,post something new etc and i have no idea how to do that :(

`use Illuminate\Database\Capsule\Manager as Capsule;

$capsule = new Capsule;

$dbx = $app->config('db');
$capsule->addConnection([
    'driver'    => 'mysql',
    'host'      => $dbx['db_host'],
    'database'  => $dbx['db_name'],
    'username'  => $dbx['db_user'],
    'password'  => $dbx['db_pass'],
    'charset'   => 'utf8',
    'collation' => 'utf8_unicode_ci',
    'prefix'    => ''
],);
// Register as global connection
$capsule->setAsGlobal();

// Start Eloquent
$capsule->bootEloquent();
`
this is how UserFrosting adds his own database.
My Goal is : 
I need to add a new connection(Wordpress) on runtime and the connection can be on different server for each users.
like i have my domain (mydomain.com) and there is wordpress.so i will able to connect that wordpress over userfrosting and post something or another user have another domain (anotherdomain.com) when he logged in he can post to his wordpress.

and sorry for my english.i hope you got the point.
I have already forms/pages for userfrosting and i am inserting to userfrosting database but i want to post articles to related wordpress to when i insert them to userforsting.

**Comment by jgrossi** [comment]
Change it to:

```
$capsule->addConnection([
    'driver'    => 'mysql',
    'host'      => $dbx['db_host'],
    'database'  => $dbx['db_name'],
    'username'  => $dbx['db_user'],
    'password'  => $dbx['db_pass'],
    'charset'   => 'utf8',
    'collation' => 'utf8_unicode_ci',
    'prefix'    => ''
], 'one_connection');
$capsule->addConnection([
    'driver'    => 'mysql',
    'host'      => $dbx['db_host'],
    'database'  => $dbx['db_name'],
    'username'  => $dbx['db_user'],
    'password'  => $dbx['db_pass'],
    'charset'   => 'utf8',
    'collation' => 'utf8_unicode_ci',
    'prefix'    => ''
], 'another_connection');
```

**Comment by bsoner** [comment]
```
use Illuminate\Database\Capsule\Manager as Capsule;
$capsule = new Capsule;
$dbx = $app->config('db');
$capsule->addConnection([
'driver' => 'mysql',
'host' => $dbx['db_host'],
'database' => $dbx['db_name'],
'username' => $dbx['db_user'],
'password' => $dbx['db_pass'],
'charset' => 'utf8',
'collation' => 'utf8_unicode_ci',
'prefix' => ''
],'default');
$capsule->addConnection([
'driver' => 'mysql',
'host'=>'107...',
'database' => 'i**',
'username' => 'username',
'password' => 'pass',
'prefix' => 'wp_',
'charset' => 'utf8',
'collation' => 'utf8_unicode_ci',
],'wordpress');
// Register as global connection
$capsule->setAsGlobal();
// Start Eloquent
$capsule->bootEloquent();
```

i did that before and didnt work

**Comment by jgrossi** [comment]
Your Controller has nothing with the Corcel, you should **use** Corcel inside `getCategories()` for example:

`$posts = Corcel\Post::all();`

To connect to Corcel you might create another connection using Capsule. Corcel uses Capsule, so no problem. Or you use Corcel database classe to connect. The Controller stuff is from your framework, not Corcel, ok?

**Comment by bsoner** [comment]
```
<?php

namespace UserFrosting;
use Corcel;
class WordpressController extends \UserFrosting\BaseController {
    

    public function __construct($app){

        $this->_app = $app;

    }

    public function getCategories(){
        //Connect to Wordpress
        /* Code to Connect  */
        $params = array(
            'driver'    => 'mysql',
            'host'=>'107.xxxxx',
            'database'  => 'xxx',
            'username'  => 'xxx',
            'password'  => 'xxx',
            'prefix' => 'wp_',
            'charset'   => 'utf8',
            'collation' => 'utf8_unicode_ci'
        );
        Corcel\Database::connect($params);

        //Get Categories
        /* Code to Get Categories */
        $posts = Corcel\Post::all();
        //Return
        Return $posts;
    }

}
?>
```

or 

```
<?php

namespace UserFrosting;
use Corcel;
use Illuminate\Database\Capsule\Manager as Capsule;
class WordpressController extends \UserFrosting\BaseController {


    public function __construct($app){

        $this->_app = $app;

    }

    public function getCategories(){
        //Connect to Wordpress
        /* Code to Connect  */
            $capsule = new Capsule;
        $capsule->addConnection([
            'driver'    => 'mysql',
            'host'=>'107.***9',
            'database'  => '***',
            'username'  => '***',
            'password'  => '***',
            'prefix' => 'wp_',
            'charset'   => 'utf8',
            'collation' => 'utf8_unicode_ci',
        ],'wordpress');
// Register as global connection
        $capsule->setAsGlobal();

// Start Eloquent
        $capsule->bootEloquent();
        //Get Categories
        /* Code to Get Categories */
        $posts = Corcel\Post::all();
        //Return
        Return $posts;
    }

}
?>
```

i am having same error : 
```
Slim Application Error
The application could not run because of the following error:

Details

Type: InvalidArgumentException
Message: Database [default] not configured.
File: /home/gameofth/public_html/deniyorum.com/content/userfrosting/vendor/illuminate/database/DatabaseManager.php
Line: 246
```

**Comment by jgrossi** [comment]
`Message: Database [default] not configured.` you need a `default` connection, so remote the `wordpress` connection name.

**Comment by alexweissman** [comment]
I'm not sure if @bsoner realizes this, but UserFrosting does not use the full Laravel framework.  Instead, we use the [Capsule](https://github.com/illuminate/database) manager as a standalone component.  Just thought it would be worth mentioning!

**Comment by jgrossi** [comment]
Hi @alexweissman, welcome! Sure thing. What I told is to include the Corcel connection in the same place you're including the UserFrosting. Using `Corcel\Database::connect()` you're using another Capsule instance, so it requires the `default` connection. If you just `->addConnection($params);` to the previous Capsule instance Corcel you get it.

**Comment by jgrossi** [comment]
@alexweissman Corcel also uses Capsule. It does not use the entire Laravel framework. So if you're already using Capsule just add another connection called `wordpress` - for example - to it. After that just call Corcel classes.

**Comment by bsoner** [comment]
@jgrossi @alexweissman guys thank you for your time but it doesnt work for me.I need to find an alternative.

**Comment by jgrossi** [comment]
@bsoner as @alexweissman told, UserFrosting uses Capsule too. You have to add another connection to it, just that. Where UserFrosting is calling Capsule? Which file? Just add another connection there. If you cannot do that uses `Capsule::addConnection()` somewhere and Corcel will use the same Capsule instance, so you will have the `default` instance from UserFrosting and the `wordpress` one from Corcel.

**Comment by jgrossi** [comment]
@bsoner @alexweissman I saw the UserFrosting code but it does not allow you to include another connection. In the `userfrosting/initialize.php` file it call Capsule but there's no way to get its instance. The solution is to add the Corcel database config on the fly, but **with** the same instance (it's global).

```
public function getCategories(){
        //Connect to Wordpress
        /* Code to Connect  */
       $params = array(
            'driver'    => 'mysql',
            'host'=>'107.****',
            'database'  => '***_***',
            'username'  => '***_***',
            'password'  => '***',
            'prefix' => 'wp_',
            'charset'   => 'utf8',
            'collation' => 'utf8_unicode_ci'
        );
        Capsule::addConnection($params); // Change this line to use the UserFrosting Capsule instance

        //Get Categories
        /* Code to Get Categories */
        $posts = Corcel\Post::all();
        //Return
        Return $posts;
    }

**Comment by alexweissman** [comment]
@jgrossi So right now, I am having people modify `initialize.php` directly when they need additional connections.  Does Corcel actually need to access the `Capsule` instance?  I was under the impression that the `->setAsGlobal` method would allow the instance to be accessed through the `Capsule` facade.

**Comment by jgrossi** [comment]
@alexweissman Corcel uses Capsule, but `new Capsule` so another instance is created. In your case just use Capsule directly `Capsule::addConnection()` and Corcel will work.

Maybe I can change the Corcel config to allow previous versions of Capsule, but I think it's not necessary, just adding a new connection on Capsule it will work.

**Comment by alexweissman** [comment]
Maybe he can modify his [`initialize.php`](https://github.com/userfrosting/UserFrosting/blob/master/userfrosting/initialize.php#L36-L57) to something like this?

```
// Eloquent Query Builder
use Illuminate\Database\Capsule\Manager as Capsule;

$capsule = new Capsule;

$dbx = $app->config('db');

$capsule->addConnection([
    'driver'    => 'mysql',
    'host'      => $dbx['db_host'],
    'database'  => $dbx['db_name'],
    'username'  => $dbx['db_user'],
    'password'  => $dbx['db_pass'],
    'charset'   => 'utf8',
    'collation' => 'utf8_unicode_ci',
    'prefix'    => ''
]);

// Register as global connection
$capsule->setAsGlobal();

// Start Eloquent
$capsule->bootEloquent();

$dbx = $app->config('db_wordpress');

Capsule::addConnection([
    'driver'    => 'mysql',
    'host'      => $dbx['db_host'],
    'database'  => $dbx['db_name'],
    'username'  => $dbx['db_user'],
    'password'  => $dbx['db_pass'],
    'charset'   => 'utf8',
    'collation' => 'utf8_unicode_ci',
    'prefix'    => ''
], 'wordpress');
```

**Comment by jgrossi** [comment]
Sure @alexweissman it will work, or `$capsule->addConnection()` once your are in the same file.

**Comment by bsoner** [comment]
@alexweissman 
Capsule::addConnection(....  didn't work
```
use Illuminate\Database\Capsule\Manager as Capsule;

$capsule = new Capsule;

$dbx = $app->config('db');
$capsule->addConnection([
    'driver'    => 'mysql',
    'host'      => $dbx['db_host'],
    'database'  => $dbx['db_name'],
    'username'  => $dbx['db_user'],
    'password'  => $dbx['db_pass'],
    'charset'   => 'utf8',
    'collation' => 'utf8_unicode_ci',
    'prefix'    => ''
]);

$capsule->setAsGlobal();

// Start Eloquent
$capsule->bootEloquent();

Capsule::addConnection([
    'driver'    => 'mysql',
    'host'=>'107.**.**.**',
    'database'  => '***',
    'username'  => '**',
    'password'  => '**',
    'prefix' => 'wp_',
    'charset'   => 'utf8',
    'collation' => 'utf8_unicode_ci'
], 'wordpress');

```
Error : 
`Strict Standards: Non-static method Illuminate\Database\Capsule\Manager::addConnection() should not be called statically in /home/gameofth/public_html/deniyorum.com/content/userfrosting/initialize.php on line 68`

@jgrossi 
$capsule->addConnection([ .... worked but Corcel still try to connect the default database

Error : 

`Message: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'gameofth_cont.posts' doesn't exist (SQL: select * from `posts`)`

**Comment by Netrilix** [comment]
Would he need to edit Corcel to use the named connection for wordpress each time it's called, instead of the default connection?

**Comment by alexweissman** [comment]
It looks like the connection is specified in the relevant models, no?

**Comment by Netrilix** [comment]
Wait, why isn't the error including the prefix "wp_" on the table not found error? Is that normal?

**Comment by jgrossi** [comment]
Corcel by default uses the `default` connection. Once you're using `wordpress` as connection name so create your own class, like `Post` extending `Corcel\Post` setting the `$connection` var:

```
class Post extends Corcel\Post 
{
    protected $connection = 'wordpress';
}
```

And after that use your class `$posts = Post::all();`.

You can also do is `Post::connection('wordpress')->all()` this should work too.

**Comment by jgrossi** [comment]
@alexweissman I will never advise you to change any package/library file, once you change it, if this package is updated your application stop working and you'll have all the problems back.

**Comment by jgrossi** [comment]
@alexweissman sorry it's `Post::on('wordpress')->all()`

**Comment by jgrossi** [comment]
@Netrilix the correct table prefix is set in the `wordpress` connection, so he might set the connection he's using to Corcel, and it will get data from the correct table with the correct prefix.

**Comment by Netrilix** [comment]
Ah, I see it now. He didn't use a prefix for the UserFrosting connection, which is the connection it was running. Thanks for clarifying!

**Comment by jgrossi** [comment]
Yes @Netrilix UserFrosting is using the `default` connection (Corcel by default uses it too). So he created another connection and added it to Capsule (`wordpress`) and now just tell Corcel to use it `Corcel\Post::on('wordpress')->all()`.

**Comment by bsoner** [comment]
Thank you all but nothing worked for me.

**Comment by jgrossi** [comment]
@bsoner you're welcome. If you want you can send your code to me privately and I can help you and @alexweissman. Thanks for using Corcel :)
