### ISSUE TITLE
Can't select specific columns from DB

### ISSUE THREAD

**Issue by jgbneatdesign** [jgrossi/corcel#176]
Hello there! Congratulations for this awesome package. I love it. I'm currently developing a single page app with AngularJS and Lumen for the front-end and WordPress for the back-end.

I'm having some issues. When I do Post:all() I get all the posts, which is fine. But it's too much unnecessary data. I want index to have a subset of the data of each post like the title, the excerpt, featured image... But I can't select which columns I want using get([array, of, columns]) or paginate(10,

**Comment by rundef** [comment]
Hi,

make sure to include the **post_type** column : 
```php 
$posts = Post::get(['post_name', 'post_type']); 
```

**Comment by jgbneatdesign** [comment]
Thanks! will try this out.

**Comment by jgb-solutions** [comment]
It seems to work but I'm still getting some null columns. I think they're
are the custom attributes set by the package. Do you know any way around
this. Thanks!

**Comment by jgb-solutions** [comment]
And also the returned columns are double up. It gives post_title and title,
post_name and slug and so on. The issue is still there. Please help.

**Comment by rundef** [comment]
Hi, they're not in double, the short names are just [eloquent accessors](https://laravel.com/docs/5.1/eloquent-mutators#accessors-and-mutators)

**Comment by jgbneatdesign** [comment]
Okay but they are still outputted. Having a big post_content and its twin
content is a huge bandwidth issue I think. What about getting array of
columns like ['title', 'content', ...]? Isn't that possible, for now?

On Jul 19, 2016 1:39 PM, "Mickael Burguet" <notifications@github.com> wrote:

Hi, they're not in double, the short names are just eloquent accessors
<https://laravel.com/docs/5.1/eloquent-mutators#accessors-and-mutators>

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/jgrossi/corcel/issues/176#issuecomment-233726627>, or mute
the thread

**Comment by rundef** [comment]
Have a look at the [eloquent models serialization](https://laravel.com/docs/5.2/eloquent-serialization) methods

**Comment by jgbneatdesign** [comment]
Thanks a lot Mickael! You saved me the day. Thanks again mate!

By the way do you any way to pull different featured image size? For now I
got one image but it's kind of big.

**Comment by jgrossi** [comment]
@jgbneatdesign Can you give us an update about your problem? Is it solved?
