### ISSUE TITLE
Eloquent orderBy not working.

### ISSUE THREAD

**Issue by austenpayan** [jgrossi/corcel#18]
Am I just missing something or is orderBy not supported by corcel?

I am trying to arrange some custom post types from oldest to newest, but the normal eloquent orderBy seems to have no effect on the order of the outputted posts.

**Comment by threesquared** [comment]
The orderBy seems to be set in the Post model on [line 102](https://github.com/jgrossi/corcel/blob/master/src/Corcel/Post.php#L102). I would suggest this is unnecessary and breaks if you want to order by anything else.

**Comment by threesquared** [comment]
For a super hacky temp fix you can get the Query object and just unset the order:

```php
$posts = Post::published();
$query = $posts->getQuery();
unset($query->orders[0]);
$posts->setQuery($query);
$posts = $posts->orderBy('post_date', 'asc')->get();
```

**Comment by rundef** [comment]
Also, you might want to have a look at the dev branch... it has already been fixed there

**Comment by jgrossi** [comment]
Hey guys! Thanks for the support. We're fixing these bugs and it will be merged soon to the master branch. Wait for good news for Corcel :-)
