### ISSUE TITLE
Laravel 5 - can select the users, can't authenticate, all using the second connection

### ISSUE THREAD

**Issue by iMPR3SSiON** [jgrossi/corcel#181]
Hi, 

I am having this little issue last few days. I want to use Corcel to authenticate my users against the WordPress table. It has to be done like this. 

So, I've created a `App\CorcelUser` class, extending \Corcel\User, with my WordPress connection defined, like so:
```
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class CorcelUser extends \Corcel\User
{
    protected $connection 	= 'wordpress';
}
```
I've set Corcel as the user provider in accordance with the tutorial:
```
'providers' => [
        'users' => [
            'driver' => 'corcel',
            'model'  => \App\CorcelUser::class,
        ],
    ],
```
The user Model is set to my newly created class with the $connection set to 'wordpress'.

I've made some generic login and dashboard views using 
`php artisan make:auth`
and tried to log in. It didn't work, returning this:
`Base table or view not found`
Obviously, it looks for the users in the wrong database, the default Laravel database, for some reason.

So, I've checked out the source, and when I added
`protected $connection = 'wordpress';`
to the `\Corcel\User class`, it just worked.

Selecting users, on the other hand, works just fine:
```
public function testWpUsers() {
	$wpUsers 		= \App\CorcelUser::find(1);

	return $wpUsers;
}
```

I'd like to know, it there is a way to override the conntection correctly, without modifying base package. If not, it probably needs to be fixed.

As a last note: Thank you to all the contributors to Corcel, it's so freaking awesome!

**Comment by rundef** [comment]
Hi,

You're absolutely right: Corcel's authentication service provider [uses the Corcel User model rather than the model specified in the config](https://github.com/jgrossi/corcel/blob/master/src/Providers/AuthUserProvider.php#L35) - it's a bug. I'll send a fix for this later today.

Thanks for using Corcel ! :)

**Comment by iMPR3SSiON** [comment]
I really appreciate the response, very fast and constructive! Thank you!
One more thing: when you fix that, how long before it is published on Packagist and accessible through Composer? 

Thanks again!

**Comment by iMPR3SSiON** [comment]
As a side note: I also feel the fact, that Corcel can authenticate against a WordPress user database, has to be "sold" a bit more :) When I was looking for the authorization against WordPress, only some, let's say, inferior, package from hampel kept poping up :) Nevertheless, I'm glad I've found Corcel!

**Comment by rundef** [comment]
I just created a pull request with the fix.
It will be on packagist when @jgrossi will merge and publish a new version.
In the meantime you can point your corcel installation to my Corcel's fork dev branch.

**Comment by jgrossi** [comment]
Doing that now @rundef

**Comment by iMPR3SSiON** [comment]
Thank you, guys!

I've tested it and it works perfectly!
