### ISSUE TITLE
Get different featured image sizes

### ISSUE THREAD

**Issue by jgbneatdesign** [jgrossi/corcel#184]
Hello there! How could I get the different featured image sizes set in the WordPress backend or the functions.php file with the add_image_size function?

- Regards

**Comment by jgrossi** [comment]
Hi @jgbneatdesign! I'm not at computer right now but you can get what you need with `$post->attachment` or `$post->thumbnail->attachment` I think.

**Comment by jgbneatdesign** [comment]
Hello @jgrossi thanks for responding quickly! When I return $post->attachment or $post->thumbnail->attachment I got just one image. The original one that was uploaded. But when I use $post->with('attachment') or protected $with = 'attachment' on the model I got all the featured image sizes like I wanted. But  this returned object has a lot of properties that I don't need. I only want the attachment->meta[1]->value property which has the original image size and link plus a sizes array/object which holds all the other sizes and file name that I need. Is it possivle to just get this data with Eloquent? If yes, how?

Even though I would still need to figure out the full url for these different image sizes.

- Regards! I love your package.

**Comment by jgbneatdesign** [comment]
I tried using an accessor  on the model like:

getImagesAttribute = return $this->attachment[0]->meta[1]-value;

And adding it to the appends array like this
protected $appends = ['images'].

It doesn't appear on the returned post object, unless I called it on the $post object like this: $post->images. 

I manage to get exactly what I want through manipulating the object $post in the controller
$post->images = $post->attachment[0]->meta[1]-value;

But still I got some issues with the different image sizes returned because I only see their name. Which I think I could manage to sort out by preventing WordPress from arranging the unloaded images by yeah/month. 

I don't know what you think. If there's something I'm doing wrong please let me know.

**Comment by jgbneatdesign** [comment]
As an update, I managed to get the different featured image sizes but I had to make some modifications to get the url right. Under settings - media I deactivated the upload images by yeah/month option. 

Now I'm seeing an issue that is WordPress related. When I upload an image on the media page the different image sizes are not generated. Which gives an error on the lumen side trying to output value from null property. The only way to generate them is by setting the image through the set featured image option. I tried using the regenerate thumbnails plugin but with no luck. I googled the issue and in the past people had some similar issues with WordPress. But I'm guessing if I were using WordPress directly, instead of pulling data from the DB with Corcel, then one images would get generated. 

I wanted to share the issues I'm getting with this SPA. Hope someone will find this useful. And if there's a better solution for this let me know please. 

- Regards

**Comment by jgrossi** [comment]
Hi @jgbneatdesign. Did that solve your problem? Can you give us an update about that? Thanks

**Comment by jgbneatdesign** [comment]
I ended up hacking around to fix the issues I've faced. And I've written
some long explanations about them. See above.

**Comment by jgrossi** [comment]
Ok thanks. If you want you can create a PR to the `dev` branch and contribute with Corce. I'm gonna close this issue and anything you need just open it again. Many thanks.

**Comment by jgbneatdesign** [comment]
Alright. I'll think about it. Thanks!
