### ISSUE TITLE
Pagination override, why?

### ISSUE THREAD

**Issue by DeanWard** [jgrossi/corcel#19]
this code prevents the default laravel pagination from working, why is this done?

    /**
     * Overrides the paginate() method to a custom and simple way.
     * 
     * @param int $perPage
     * @param int $currentPage
     * @return \Illuminate\Database\Eloquent\Collection
     */
    public function paginate($perPage = 10, $currentPage = 1)
    {
        $skip = $currentPage * $perPage - $perPage;
        return $this->skip($skip)->take($perPage)->get();
    }

**Comment by jgrossi** [comment]
Hi @DeanWard!

As we've changed the default query the default Laravel pagination method was not working. Corcel was developed using Laravel 4 so maybe there are some functions not working well in Laravel 5.

If you can try and remove the method please tell me the result and writing a simple test to check we can remove the method.

Thanks for the comment.

**Comment by DeanWard** [comment]
Ah that makes sense - I'm still running L4.2 at the moment so just commenting out the code made pagination work again. Is there a separate branch or version for L4.2?

**Comment by jgrossi** [comment]
@DeanWard no, there is no custom version for Eloquent 4.2. Can you send a pull request removing the made paginate method?

**Comment by DeanWard** [comment]
Sure, I'm not great with unit testing but I'll give it a go - thats what prevented me from finishing up with the menu builder  mod I made

**Comment by jgrossi** [comment]
No problem! Just follow the tests we have on the package and make yours. It's a good opportunity to try :-)

**Comment by vishalmote** [comment]
public function paginate($perPage = 10, $currentPage = 1)
    {
        $skip = $currentPage * $perPage - $perPage;
        return parent::where('tanent_id','=',Config::get('themes.theme'))->skip($skip)->take($perPage)>get();
    }

...
In controller

$components = Components::paginate(10);

does return all the records.


I have added this method to my model.
Used that eloquent model and then called paginate() method, but this is not overriding original paginate() method.


Still getting all the records from out of  this where('tanent_id','=',Config::get('themes.theme')) condtion.
Even tried adding in that method. it clearly shows that paginate method is not getting override.

**Comment by jgrossi** [comment]
Hi @vishalmote. Can you send me your code in a gist to check what's happening? thanks ;-)

**Comment by vishalmote** [comment]
Hey jgrossi I dont have idea about gist option in git. cant you just understand my problem and tell me reason behind the overriding.

**Comment by jgrossi** [comment]
@vishalmote if the `paginate` method is inside your `Components` class you can set the method as `static` and it will be called. If this not work I ask you to send me a gist with all your codes to check (https://gist.github.com).

**Comment by jgrossi** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fix Post pagination issues](https://trello.com/c/ZE2qVG8P/20-fix-post-pagination-issues)

**Comment by thaiscristine** [comment]
Yes, we are getting an instance of "LengthAwarePaginator". The problem is happening in the "$ posts->render()".
