### ISSUE TITLE
Missing argument 1 for Corcel\Providers\AuthUserProvider

### ISSUE THREAD

**Issue by johnhalsey** [jgrossi/corcel#190]
I have installed this package into Laravel, and tried to implement the authentication so that a user can login via the wordpress credentials.

However in the `AuthServiceProvider` class, the `construct()` takes a `$config` variable, but it's not mentioned in the ReadMe under Authentication, and I'm not sure what is supposed to be passed in.

Can you help?

**Comment by rundef** [comment]
Hi,

If you are using Laravel, you don't need to instantiate the `AuthUserProvider` class. Just define the Authentication provider and the User provider like it's done in the documentation ; Then, Laravel's built-in authentication system will be using thoses providers to authenticate users in your app.

But if you do have to instantiate `AuthUserProvider` for some reason, you can just pass `null`.

**Comment by johnhalsey** [comment]
Ah I see where I went wrong there.

But after amending the config/app.php and config/auth.php files as advised, when attempting to login, my laravel app is still looking for my laravel users table, instead of the wordpress users.  

I thought I might need to create a User model that has a `protected $connection` pointing to the wordpress data, but still no joy.

**Comment by QWp6t** [comment]
Pretty sure your issue was fixed here: https://github.com/jgrossi/corcel/pull/182

You using the latest version?

**Comment by johnhalsey** [comment]
Yes, I have the latest version.

**Comment by johnhalsey** [comment]
OK, I figured it out.  I had to change the default connection in Laravel to the wordpress connection.  Then it worked.
