### ISSUE TITLE
Incorrect use of guid for attachments and images

### ISSUE THREAD

**Issue by cjke** [jgrossi/corcel#191]
The use of the guid for attachments and images seems to be the wrong approach (in my opinion). Guid's, including within Wordpress, is intended to give a unique id, across space and time, to a post - it just coincidentally happens to be the url through to the attachment, but only at the point when it uploaded. 

By relying on the guid, it makes it impossible to migrate a local install of Wordpress to a production or staging environment (as the guid is pointing to the the local site - say mysite.dev). Typically, tools such as [Wordmove](https://github.com/welaika/wordmove)  will update site config urls (automatically updating mysite.dev -> mysite.com), but they don't alter the guid (by design, as it Wordpress recommends against it). 

A more stable/scalable approach would be to mimic Wordpress' built in get_attachment_url method , found [here](https://core.trac.wordpress.org/browser/tags/4.5.3/src/wp-includes/post.php#L5005)

In corcel, I am guessing it would look something like: 

                $imageUrlRecord = DB::connection($this->getConnection()->getName())
                    ->table('postmeta')
                    ->where('post_id', $value)
                    ->where('meta_key', '_wp_attached_file')
                    ->first();

The above snippet is ignoring any path manipulation - to not introduce a breaking change (and to align to the current guid approach) you would probably need to prepend the site url as well. Possible reading from the options table. 

This obviously introduces a) a possible breaking change, and b) a extra trip to the db. 

**Edit** 

It's actually two steps to get the correct url, and meta data along with it:

        $thumbnailId = DB::connection($this->getConnection()->getName())
                ->table('postmeta')
                ->where('post_id', $postId)
                ->where('meta_key', '_thumbnail_id')
                ->first()
                ->meta_value;

        return unserialize(
                    DB::connection($this->getConnection()->getName())
                        ->table('postmeta')
                        ->where('post_id', $thumbnailId)
                        ->where('meta_key', '_wp_attachment_metadata')
                        ->first()
                        ->meta_value
                );

This will yield (the focus being - "file"):

```
array(4) {
  ["width"] => int(500)
  ["height"] => int(500)
  ["file"] => string(17) "2016/07/osake.png"
  ["image_meta"] => Array(12) {
    ["aperture"] => string(1) "0"
    ["credit"] => string(0) ""
    ["camera"] => string(0) ""
    ["caption"] => string(0) ""
    ["created_timestamp"] => string(1) "0"
    ["copyright"] => string(0) ""
    ["focal_length"] => string(1) "0"
    ["iso"] => string(1) "0"
    ["shutter_speed"] => string(1) "0"
    ["title"] => string(0) ""
    ["orientation"] => string(1) "0"
    ["keywords"] => array(0) {}
  }
}
```

**Comment by rundef** [comment]
To save the extra trip to the DB, we can use [URL helper functions](https://laravel.com/docs/5.0/helpers#urls) to generate an absolute url from a relative url (it reads the `APP_URL` variable from the .env file)

Does this give you the URL you are looking for ? 

```php
url($attachment->meta->_wp_attached_file->value)
```

You can attempt a pull request if you'd like !
Thanks :)

**Comment by cjke** [comment]
Happy to do a PR. I have a few in mind (that I will keep as seperate PRs, the other being support for ACFs - namely the repeater element). 

I think it will end up being at least one extra requests regardless (because we have to return to the posts table for _wp_attachment_metadata or _wp_attached_file - which has a different post_id to the actual post being looked up. 

My only hesitation around a PR is that its a potentially breaking change. 

One question before getting stuck in - should we reading the APP_URL from the .env? If you have WP installed at admin.mysite.com and the main application at mysite.com, the url generated should be relative to the admin.mysite.com (which wouldn't be in .env). I think?

**Comment by QWp6t** [comment]
You can run into the same problem with grabbing siteurl or homeurl from wp db. Both of those can be overridden with `define()`, which would make it difficult to snag them from outside of wordpress (never mind the potential nightmare of dealing with various multisite setups). so i'd say to just pick a way of grabbing it, but make it configurable so developers can easily override it.

**Comment by rundef** [comment]
I agree but I don't think Corcel should return absolute URLs. Instead, we could offer helper functions that returns the siteurl and homeurl. That way, the developers could use thoses or just a custom way of generating absolute path.

**Comment by jgrossi** [comment]
@rundef is right! Maybe creating some helpers like `URL::home()` and `URL::siteUrl()` would be better than returning absolute URLs.

**Comment by cjke** [comment]
That's fair - I know absolute url's are frowned upon. My suggestion was based on mirroring Wordpress and about flagging that using guid's is risky as it is merely a lucky coincidence that they happen to be the correct urls at that point in time (though shouldn't be relied on). 

Side note, absolute urls are often used on larger applications for static assets as they can be served from behind a cdn, or simply distributed better. For example, all images I upload to my wordpress sites are caught by a filter and stored on s3 instead. 

Again, not pushing absolute url's (because I'm not :) ), and they tend to be a dirty word in the web world, but it ultimately depends on your project goals and it's underlying ethos - mirroring wordpress functionality, or more about a stepping stone towards laravel. 

Honestly happy with either, just wanted to raise it - cheers for listening

**Comment by jgrossi** [comment]
Hi @cjke did you solve your problem? If you have anything I can help you, just let me know. And if you want to send a PR with custom feature be welcome! Cheers!

**Comment by cjke** [comment]
Keen to do a PR. Of the different approaches above, which lines up to the goals of Corcel the most? I will work to line up to that.

**Comment by cjke** [comment]
Our team abandoned the project utilising Corcel (not Corcel itself). So closing this issue as no longer have an active reference. Thanks for the awesome project.
