### ISSUE TITLE
Post Format

### ISSUE THREAD

**Issue by nicosli** [jgrossi/corcel#194]
Hi

How to i can to format the post? Wordpress uses get_post_format() function

Thank you in advance

**Comment by rundef** [comment]
Hi, you can try the following :

```php
Post::find(1)->taxonomies()->whereTaxonomy('post_format')->first()->name
```

**Comment by nicosli** [comment]
i am using

`$posts = Post::taxonomy('category', 'inicio')->get();`

and i need to show the post with the format

**Comment by jgrossi** [comment]
Hi @nicosli. Do you want to get the result of the `get_post_format()` function?

**Comment by nicosli** [comment]
@jgrossi that's rigth

**Comment by jgrossi** [comment]
@nicosli I'm gonna create this in `Post.php` class and let you know.

**Comment by jgrossi** [comment]
@nicosli Please, update your composer to use the temporary Corcel version `'dev-feature/post-format`. The `feature/post-format` branch has a method called `getFormat()`, so you can do:

```php
$post = Post::find($id);
echo $post->getFormat(); // should return 'video' for example, like get_post_format()
```

Let me know please. If everything is ok I'm gonna launch another version. Thanks.

**Comment by nicosli** [comment]
@jgrossi thank you for your solution, its ok but i think my problem is other. When i create a new Post in Wordpress the table wp_post (column post_content) has something like this:

`This a test <img src='http://image.png' />`

But when i see the post's html in the wordpress frontend then i see this

`<p>This a test</p> <p><img src='http://image.png' /></p>`

So when i use `{!!$post->post_content!!}` in my frontend the HTML don't have a format like wordpress frontend

I'm a little confused.

**Comment by jgrossi** [comment]
@nicosli if you saved the `post_content` using Corcel you have exactly what you had, without `<p>`. Can you check the database content?

About the "format", it's just a taxonomy `post_format`, so if you want to include it too with Corcel you have to save the corresponding table and row. When you "save" in the WordPress admin panel it might change the `post_content` and the `format` taxonomy too.

Take a look into your database (`post_content` column) *before* and *after* saving using the admin panel, and observe if you're having data change then.

**Comment by nicosli** [comment]
@jgrossi i have a solution, in the backend of wordpress now i'm using a new plugin to format the post, now in the database i can see the html like <p>.

Your last solution it's good for me as well

Thank you a lot!

**Comment by jgrossi** [comment]
@nicosli good to know :-) I'm gonna close this issue and anything you need you reopen it or create a new one! Cheers and thanks for using Corcel ;-)
