### ISSUE TITLE
Set Categorie / term

### ISSUE THREAD

**Issue by jfschubert** [jgrossi/corcel#196]
Hi,
im currently trying to add a specific Categorie to a post but somehow it does not work

i currently have:

```
$post = new Post();
// Adding Post works so skipped
//Saving the post 
$post->save();
//trying to add term with id 247 to the taxonomies:
$post->taxonomies()->sync([247]);
```

The post will be created but the Taxonomy / Categorie will not get set

**Comment by rundef** [comment]
Hi,
The relationship table is `wp_term_relationships`, and it's using the `term_taxonomy_id` column rather than the `term_id`.
Try something like this :

```php
//trying to add term with id 247 to the taxonomies:
$termTaxonomy = TermTaxonomy::whereTermId(247)->first();
$post->taxonomies()->sync([$termTaxonomy->term_taxonomy_id]);
```

**Comment by jgrossi** [comment]
Hi @jfschubert. Did you solve that?

**Comment by jfschubert** [comment]
Hi,
sorry for the late reply.

I had to save the post once more before adding some PostMeta which i was filtering on.

```
$post = Post::where('post_title',$user->name)->get()->first() ?? new Post()
// Setting Data in Post table
$post->save();
//Setting Metadata 
$post->save();
//Setting Taxonomy
$post->taxonomies()->sync([$taxonomyId]);
```
