### ISSUE TITLE
pagination and meta order

### ISSUE THREAD

**Issue by giorgiosaud** [jgrossi/corcel#21]
if you make a paginated query ti never work but if you delete the function that overides the pagination of laravel model it works in L5 and you must extend to Model  and not from Eloquent in L5 other thing is that if you try to make a join to order by some custom taxonomy it never be reorder because you internally ordered it by post date it fix can be solved making other protected variable that said if you want this post be ordered by post date

**Comment by jgrossi** [comment]
Hi @giorgiosaud!
Thanks for the comment. Can you write some tests and send a pull request to the repo?
Thanks ;-)

**Comment by jgrossi** [comment]
#19 and #23
