### ISSUE TITLE
Post format

### ISSUE THREAD

**Issue by SimoneS93** [jgrossi/corcel#216]
In the README you say:

`$videos = Post::type('video')->status('publish')->get();`

but it can't be working, since `post_type` is different from `post_format`, that is what you're referring to.
I'm working on this, but I'd like there's already a solution to this.

From the Wordpress docs, it says that `post_type` can be one of:

- post
- page
- attachment
- revision
- nav_menu_item

**Comment by jgrossi** [comment]
Hi @SimoneS93. The example is for a custom post type called `video`. There's nothing with post format. The example shows you can access *custom post types* using the `type()` method or by extending the `Post` class and setting the `$postType` property. JG

**Comment by jgrossi** [comment]
To search by `post_format` just use `where('post_format', 'foo')`.

**Comment by SimoneS93** [comment]
Sure, I figured out I can use 

`Post::taxonomy('post_format', 'post-format-video')->get();`

Sorry for the silly issue.
