### ISSUE TITLE
Laravel 5

### ISSUE THREAD

**Issue by stubar** [jgrossi/corcel#22]
Hi I'm loading this straight into a Laravel 5 project with composer.  It has automatically picked up my laravel DB settings which is great but it is looking for tables without the wp_ prefix.  I have fixed by editing your source to protected $table = 'wp_posts'; but it would be nice to leave you're source un touched, how can I specify wp_ prefix but still use the laravel config DB?

**Comment by jgrossi** [comment]
Hi @stubar! Thanks for the comment.
You can override the $table variable to load the table you want ;-)

**Comment by stubar** [comment]
Thanks for getting back, is there anyway I can do that without editing your source in /vendor ?

**Comment by jgrossi** [comment]
Sure, you create your class and extend the `Corcel\Post`, like this: https://gist.github.com/jgrossi/b477d97ab350f6b48e63. :-)

**Comment by stubar** [comment]
Hi thanks for that, I was able to get it working, I had to do the same for postmeta as though, then I realised I just needed to do this...

$laravelDB =  Config::get('database.connections')[Config::get('database.default')];
        $params = array(
            'database'  => $laravelDB['database'],
            'username'  => $laravelDB['username'],
            'password'  => $laravelDB['password'],
            'prefix'    => 'wp_' // default prefix is 'wp_', you can change to your own prefix
        );
        Database::connect($params);
        $posts = Post::published()->get();

**Comment by jgrossi** [comment]
Hi @stubar! You can extend the class you want to customize or create a new one and use Corcel as composition instead of inheritance. Just create the methods you want and use Corcel to manage them.

Any questions just ask ;-)

**Comment by janbolat** [comment]
Hello,
I have just installed it on Laravel 5. Works great.
Can't get meta data though.
Can you give me a clue?

Thank you

**Comment by janbolat** [comment]
Nevermind. Retrieved it by guid field

**Comment by jgrossi** [comment]
Hi @janbolat!

Corcel does not provide an unique way to get the URL from a post, for example. You have to get that using Wordpress or even Laravel - like you said. Getting the guid is easy but it's your app rule. 

Thanks for the support. Any question just ask. ;-)
