### ISSUE TITLE
Strict standard notices in ::paginate()

### ISSUE THREAD

**Issue by mikaelengstrom** [jgrossi/corcel#23]
Hi.

The current master branch gives me the following notice:

Strict standards: Declaration of Corcel\PostBuilder::paginate() should be compatible with Illuminate\Database\Eloquent\Builder::paginate($perPage = NULL, $columns = Array, $pageName = 'page') in /wwwroot/vendor/jgrossi/corcel/src/Corcel/PostBuilder.php on line 14

Might be a good idea to redefine PostBuilder::paginate API or rename the function to something else?

**Comment by keyurshah** [comment]
having the same issue in laravel5. thanks.

**Comment by jgrossi** [comment]
Hi @mikaelengstrom and @keyurshah! Maybe the best options is to change the `paginate` method name, because some people use Corcel with Laravel 4 yet and the signature method changed in Laravel 5. I'm gonna change that and let you know. Thanks. Regards.

**Comment by keyurshah** [comment]
Thank you very much!

**Comment by kriskbx** [comment]
+1

**Comment by jgrossi** [comment]
Guys sorry about the late answer. I'm running out of time now and I could not change that yet. If one of you can send a pull request suggesting some changes I'll appreciate that. Thanks!

**Comment by kriskbx** [comment]
I renamed the `paginate` method to `paged` (dd020a1eecf5330400f87fb1310ca2b8ed46962a). This should resolve the issue. Make sure to update your code and pull the latest changes using `composer update`.
