### ISSUE TITLE
Using multiple connections with Corcel

### ISSUE THREAD

**Issue by kummerer94** [jgrossi/corcel#27]
Hey there!

I'm using the newest Corcel together with Laravel 4.2. I installed Wordpress in a seperate database.

I configured Laravel to use this database 

```
'mysql_wp' => array(
	'driver'    => 'mysql',
	'host'      => '127.0.0.1',
	'database'  => 'wordpress',
	'username'  => 'root',
	'password'  => 'mypassword',
	'charset'   => 'utf8',
	'collation' => 'utf8_unicode_ci',
	'prefix'    => 'wp_',
)
```

When I try to use this configuration with `Corcel\Database::connect($params)` it will break my existing database connection.

I want to configure Corcel to use the `mysql_wp` connection. Is this possible?

**Comment by jgrossi** [comment]
H @kummerer94! Does `params` have all these fields you've showed here? You can change connection inside your Model class too, like creating your own `Post` class extending `Corcel\Post` and setting `$connection` to `mysql_up` for example. Any question just ask.

**Comment by kummerer94** [comment]
Thanks for your answer! - No, I've only used the fields that were in the tutorial on the Readme page. I came up with the same solution you are proposing just yesterday.

Seems to work!

**Comment by jgrossi** [comment]
Ok @kummerer94. If any questions just ask :D
