### ISSUE TITLE
Will you be working on Widgets ?

### ISSUE THREAD

**Issue by Geekathon** [jgrossi/corcel#30]
Will this project will have action and hook of wordpress filter ?

**Comment by jgrossi** [comment]
Hi @Geekathon! Thanks for the message ;-)

Corcel is a independent wrapper to allow you to connect the the Wordpress database structure using Eloquent ORM. So, we have no hook or filters. If you want to customize your models you can extend them and make any changes you want to.

You can contribute to the project to and make Corcel better ;-)

Thanks.
