### ISSUE TITLE
Laravel 5 Integration

### ISSUE THREAD

**Issue by jeanpierreb** [jgrossi/corcel#32]
I added the project to my composer require but I'm not able to use `Post::find(31)` Facade. Is there something I should know about Laravel 5 integration or is this a bug?

Here is my Controller

```
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Requests;
use App\Http\Controllers\Controller;
use Corcel;

class WordPressController extends Controller
{
    public function getIndex ()
    {
        // This stuff works
        // $posts = get_posts([
        //     'posts_per_page' => 20,
        //     'order' => 'ASC',
        //     'orderby' => 'post_title',
        //     ]);

       //This stuff does not
        $posts = Post::find(31);
        return $posts;
    }
```

Error Page
![screen shot 2015-09-11 at 1 14 10 pm](https://cloud.githubusercontent.com/assets/5042155/9821242/156a81ce-5887-11e5-8732-1569fbf1ea80.png)

**Comment by rundef** [comment]
Not a bug, it should be `use Corcel\Post;` instead of `use Corcel;`

**Comment by jgrossi** [comment]
heheheheh you're right or you can insert "use Corcel\Post" and use only
Post :-)

**Comment by jeanpierreb** [comment]
Works, thanks @rundef and @jgrossi
