### ISSUE TITLE
Readme issue

### ISSUE THREAD

**Issue by floflock** [jgrossi/corcel#340]
Hey,

i think under https://github.com/corcel/corcel#creating-your-own-model-classes the code example is wrong. It is `use Corcel\Model\Post as Corcel;` instead of `use Corcel\Post as Corcel;`

```php
<?php // File: app/Post.php

namespace App;

use Corcel\Model\Post as Corcel;

class Post extends Corcel
{
    protected $connection = 'foo-bar';

    public function customMethod() {
        //
    }
}
```

**Comment by jgrossi** [comment]
@florianflock you're right! would you like to send a PR to fix that?

**Comment by floflock** [comment]
PR #341 was created.

**Comment by jgrossi** [comment]
Thanks ;-)
