### ISSUE TITLE
"jgrossi/corcel": "dev-master", for laravel 5.0.*

### ISSUE THREAD

**Issue by KyawThuWin** [jgrossi/corcel#342]
I just have composer update with "jgrossi/corcel": "dev-master", for laravel 5.0.*

Right now, I go the problem -

ErrorException in \vendor\jgrossi\corcel\src\Post.php line 516:
Trying to get property of non-object
in Post.php line 516
at HandleExceptions->handleError('8', 'Trying to get property of non-object', '\vendor\jgrossi\corcel\src\Post.php', '516', array('attributes' => array('ID' => '6', 'post_author' => '1',

**Comment by KyawThuWin** [comment]
I tried with -

Post::where('post_type','post')->where('post_status','publish')->with('attachment','gettaxonomiestag','gettaxonomiescat')->get();

**Comment by jgrossi** [comment]
Hey, sorry but Corcel does not work in Laravel 5.0, only from 5.1 to 5.5.

For 5.1 please use Corcel 2.1, for 5.2 Corcel 2.2, ... and for Laravel 5.5 Corcel 2.5.

**Comment by KyawThuWin** [comment]
I just used old version since before !!!  thank you!! I will trace it

**Comment by jgrossi** [comment]
@KyawThuWin how long? Corcel was updated to version 2 on August, so once you're using `master` branch it's updated with the last version.

I suggest you use the last `v1.4.5` then, maybe it works with Laravel 5.0.

**Comment by KyawThuWin** [comment]
Dear @jgrossi,

I just used for long time(it may be first of 2016).I don't remember when I was using. I never updated it before.

**Comment by jgrossi** [comment]
@KyawThuWin we, you've used `master` branch always. Now it's updated. Try to use:
```
"jgrossi/corcel": "v1.4.5"
```
I think it'll work. Cheers.
