### ISSUE TITLE
Laravel User to login to wordpress

### ISSUE THREAD

**Issue by bhazboun123** [jgrossi/corcel#344]
Hi

is it possible with Corcel for a laravel User ( users table in Laravel) to be able to login to wordpress as an author? or any other permission?

**Comment by jgrossi** [comment]
Hi @bhazboun123. Actually Laravel and WP store user's password using different approaches. Corcel doesn't allow that but maybe this package can help you or can be just a start point for you. https://packagist.org/packages/hautelook/phpass
