### ISSUE TITLE
Integrate with Lumen 5.2

### ISSUE THREAD

**Issue by jbalzar** [jgrossi/corcel#345]
Hi, I'm trying to integrate this with Lumen 5.2, is there any guide to make this work?

**Comment by jgrossi** [comment]
Hi @jbalzar actually there's no additional configuration to make it work. Are you having any issue with Corcel and Lumen? Basically, you have to create the WordPress database connection, set it in the configuration file `config/corcel.php` and start getting data from `Corcel\Model\Post` for example.

**Comment by jbalzar** [comment]
I decided to use Laravel instead, thanks
