### ISSUE TITLE
Meta field name with dash

### ISSUE THREAD

**Issue by jbalzar** [jgrossi/corcel#346]
Hi, Is there a way to get post meta field with dash in field name beside using Laravel collection method?

`$post->meta->where('meta_key', 'field-name')->first()->meta_value`

**Comment by Dartui** [comment]
```php
$post->meta->pluck('meta_value', 'meta_key')->get('_your_key');
```

or

```php
$key = '_your_key';
$post->$key;
```

Eventually try this:

```php
$post->{'_your_key'};
```

**Comment by jbalzar** [comment]
Got it, Thank you!

**Comment by jgrossi** [comment]
thanks @Dartui for answering and thanks @jbalzar for the question. anyway, I've just added `getMeta()` method in `HasMetaFields` trait. So @jbalzar you can do something like this (only from `2.5` branch) too:

```php
$post = Post::find(1);
$post->saveMeta('foo', 'bar');
echo $post->getMeta('foo'); // bar 
```
