### ISSUE TITLE
Comments timeline

### ISSUE THREAD

**Issue by mattyglover** [jgrossi/corcel#35]
Is anyone actively working on comments?

**Comment by jgrossi** [comment]
Hi @mattyglover!

We have no ETA to comments feature, but if you want you can contribute to the project. Maybe next days I have some free time and I can start the comments integration and you can contribute too.

Thanks for the interest ;-)

**Comment by mattyglover** [comment]
Ive just implementeded comments using the Facebook comment system - works really well

**Comment by jgrossi** [comment]
Very nice @mattyglover!

**Comment by mattyglover** [comment]
I am wondering what benefit there would be in using native  comments?

**Comment by jgrossi** [comment]
I had used native comments for years, but I moved to Disqus this year. I think when you're creating with Corcel and Wordpress you are developing your project from scratch so you can and cannot use native comments. Services like Disqus are awesome to manage these conversations but I think that would be nice to have native comments implemented with Corcel ;-)
