### ISSUE TITLE
How to generate attachment metadata with Corcel

### ISSUE THREAD

**Issue by bhazboun123** [jgrossi/corcel#350]
https://core.trac.wordpress.org/browser/tags/3.8.1/src/wp-admin/includes/image.php#L72

I am trying to generate this function in Corcel is that possible? this returns and array which gets inserted in wp_post table

**Comment by jgrossi** [comment]
@bhazboun123 hey.. actually Corcel itself cannot do that, you can get the related attachment and get all meta fields you want, but something ready to go there's not yet... this can be implemented, of course...

just to make it clearer, would you like to get all metadata from a given attachment?

**Comment by bhazboun123** [comment]
Hi, its not about getting the metadata attachement from wp_post , its about generating it correctly like how wordpress does and inserting it to the table, 
https://core.trac.wordpress.org/browser/tags/3.8.1/src/wp-admin/includes/image.php#L72

see this function returns an array , I want to create a function like that but in laraval that does the same thing and it returns the array , and then we update the meta data , I am trying to do an upload function in Laravel that puts the data correctly ?

**Comment by jgrossi** [comment]
hm yep, working with upload, in this case, would be complex... maybe implementing an upload using a base64 string or something similar to that.. let's think about that first, but it seems to be a great improvement to Corcel ;-)

**Comment by bhazboun123** [comment]
yep it will be ;)

**Comment by interludic** [comment]
Did this happen?
