### ISSUE TITLE
Compatibilities issues with Lumen 5.5

### ISSUE THREAD

**Issue by dasilvaluis** [jgrossi/corcel#351]
- Corcel Version: 2.5
- Framework Name & Version: Lumen 5.5
- PHP Version: 7.0

Hello, 
I found a couple of issues installing Corcel in Lumen framework.

1) config_path() is not defined like in Laravel. A workaround is to add an helper file like this https://gist.github.com/mabasic/21d13eab12462e596120. I added in a helper file in the Lmen setup, however it would be better to add this solution in the Lumen code base to avoid erros at all.

2) Class 'Auth' from Laravel was not found. I had to comment out the line CorcelServiceProvider:24 regarding the registration of the Auth provider

**Comment by jgrossi** [comment]
@luism-s thanks for reporting this. 

1. yep, you're right. I think this is related to Lumen, not Corcel.
2. maybe creating a config option in `config/corcel.php` to allow user to inform if the auth should be configured or not.

thanks for that.

**Comment by dasilvaluis** [comment]
1. It is definitely related to Lumen
2. But the issue happens before `config/corcel.php` is generated. Maybe a condition could be made in the `boot()` method of `CorcelServiceProvider`, checking if it is a Laravel or Lumen setup, and register AuthProvider if it is Laravel

**Comment by jgrossi** [comment]
Fixed with #353. Thanks @adrianogl.

**Comment by adrianogl** [comment]
;)

**Comment by dasilvaluis** [comment]
Props @adrianogl
