### ISSUE TITLE
Passing Auth Facade to Wordpress

### ISSUE THREAD

**Issue by alvintheodora** [jgrossi/corcel#354]
Hi, 
I use Laravel for my e-commerce, and use wordpress for just the blog module.
I simply want to use auth()->user()->name in Wordpress, and I don't know how to apply this with corcel.
Any suggestion is really appreciated, thank you.
Have a nice day!

**Comment by jgrossi** [comment]
Hi @alvintheodora do you want to use Laravel's user info inside WordPress or WordPress user's info inside Laravel?

**Comment by alvintheodora** [comment]
Hi @jgrossi , I want to use Laravel's User info inside WordPress. Is it possible though?

**Comment by jgrossi** [comment]
@alvintheodora no, Corcel does the opposite. actually you can, but not using Corcel directly. You should have to include composer `autoload` file inside WordPress, like `functions.php` for example. Then you should be able to [use Eloquent outside Laravel](https://github.com/illuminate/database), creating a `User` model, and connecting the database into it. So, inside WordPress you would have a `User` instance referencing the `users` table in Laravel, for example.

This would be just to get a "user" instance inside WP, but you should have to share the cookie in Laravel and then access it in WP, then you could get the logged user inside WP. it's not a easy task I guess, you can do that, but it's a bit of work.

Now, with Corcel, you can use the WP user inside Laravel, exactly the opposite ;-)

**Comment by Dartui** [comment]
This should be noted that Laravel cookies are encrypted, so it will be not so easy to share them between Laravel and WordPress

**Comment by jgrossi** [comment]
@Dartui yep good call. You can of course add a new cookie to make it easier to get, less secure, but it's possible.

**Comment by alvintheodora** [comment]
@jgrossi I see. Your suggestion is really cool, but I think it is not worth the effort for setting the `functions.php` and the cookie, to just pass the auth facade.

I have made the all the database in Laravel, so now, if I want to use Corcel, I just need to import the tables to wordpress db and add wp_prefix, then do the database setup, is it correct?

**Comment by jgrossi** [comment]
@alvintheodora no, actually WP has a very customized database, it's a CMS not a framework. Corcel  allows you to use some models/classes like WP stores posts/pages in the database.

What's your main goal? It seems you have an app running in Laravel and you only want a blog from WP. You have to create the WP blog and let users create posts, then get those posts inside the Laravel app using Corcel.

**Comment by alvintheodora** [comment]
@jgrossi Yes, it is exactly like what you said. I have an app running in Laravel and I only want a blog from WP.
I can think of fetching the posts inside Laravel using Corcel, but I don't know how to insert Comment to the wp_comment using Corcel. Is it possible with Corcel?

**Comment by jgrossi** [comment]
@alvintheodora using only Corcel no, but this is easy using Eloquent:

```php
Corcel\Model\Comment::create(...);
```

**Comment by alvintheodora** [comment]
@jgrossi how about the `comment_author `column? I want to fill that with the logged in user in my Laravel app. Can I fill it with `auth()->user->name`. So it would be like:
`Corcel\Model\Comment::create(['comment_author' => auth()->user()->name, ...])`

Can I do that ? If I do the` auth->user()->name`, does Corcel fetch it from `wp_user` table or the Laravel's default `users` table

**Comment by jgrossi** [comment]
@alvintheodora it depends on the authentication provider you're using. If you're using our `AuthUserProvider` you can even configure the model you want to use in the `config/auth.php` file. Then you can ask for the Laravel `User` model or even Corcel `User` one. 😉
