### ISSUE TITLE
Exception error

### ISSUE THREAD

**Issue by DanDvoracek** [jgrossi/corcel#355]
Getting a weird error after running `php artisan config:clear`.

```
file_put_contents(/Users/myname/Code/corcelapp/storage/framework/cache/data/dd/c7/ddc7b4b589f5dd6ee935c9921cfd3798fea8c459): failed to open stream: No such file or directory
```

Any idea how to get around that?

**Comment by jgrossi** [comment]
This is not related to Corcel, but Laravel. Take a look on Laravel folder permissions.

**Comment by DanDvoracek** [comment]
Hmmm alright.. Never saw that before. I'll have a look then. Cheers

**Comment by jgrossi** [comment]
You're welcome!

**Comment by DanDvoracek** [comment]
I have to say it seems harder to fix than I thought. 

I don't have any files anymore in my `storage/framework/cache` folder and it keeps complaining about it. Worse I can't run any artisan commands. Would you have any hint about it ? It only complains about the corcel files for some reasons.
