### ISSUE TITLE
Thumbnail images URLs

### ISSUE THREAD

**Issue by saimiris** [jgrossi/corcel#356]
- Corcel Version: 1.1.5
- Framework Name & Version:
- PHP Version: 
- Database Driver & Version:

### Description:
Is there a way to simply obtain the URLs of the thumbnail images or a given post?

### Steps To Reproduce:

**Comment by jgrossi** [comment]
Hey @saimiris you can take a look on the `thumbnail` relation in `Post` object:

```php
$post = Post::find(1);
dd($post->thumbnail);
```

Just go to `Post` model, line 179 on `2.5`.

Thanks for sharing! 😉
