### ISSUE TITLE
caching?

### ISSUE THREAD

**Issue by SapneshNaik** [jgrossi/corcel#357]
Does the package provide any way to cache the db queries made?  and does caching on the back-end (WordPress) side yield any benefits? I am looking to improve the page speed by caching, any insights and tips would be really helpful!

**Comment by jgrossi** [comment]
Hi @SapneshNaik actually the cache usage is up to the developers. You can use Memcache or Redis for that, if you want. There's no default cache provider from Corcel but there're many from Laravel you can use. 

Anything just let me know, ok? Thanks! 😉
