### ISSUE TITLE
Help! Corcel automatic data fecth from route

### ISSUE THREAD

**Issue by drosendo** [jgrossi/corcel#364]
Hi,

Hope some one can point me on the right direction here.

Currently all pages are created in WP and I will certainly not register all paths, because they can be whatever the user creates so... what I have so far is, a route that will handle all the requests:

`Route::get('{slug?}/{slug2?}/{slug3?}', 'LayoutsController@index');`

than the controler to get the respective page/post type, but im afraid it may cause some issues later:

```
class LayoutsController extends Controller
{

    public function index($slug = null, $slug2 = null, $slug3 = null)
    {
        
        if ($slug2) {
            $post = Post::type($slug)->slug($slug2)->first(); // IF IS POST TYPE
            if($post == null){ // No post type found so must be PAGE
                $post = Page::slug($slug2)->first(); // GET PAGE
            }
        } else {
            $post = Page::slug($slug)->first();  // GET PAGE
        }
  $fields = unserialize($post->meta->acf_corcel); // https://github.com/corcel/acf/issues/49
dd($post); // Will contain all my page data

}
```

Now, the cases:

- What if it has a locale? /pt, /en etc...
- What if there are more than 3 slugs
- What if is other thing else :P

So on... how can I generalize this and always get the correct page data from WordPress?

Hope someone can help me out here.

Cheers,
David

**Comment by jgrossi** [comment]
Hi @drosendo in Laravel you can create routes using regexp, so you can force a `/{lang?}/...` where `lang` should have just 2 chars, etc.

To make slugs infinity you can use a regex with something like `/{slug}` and set the slug to `(.*)` in route regexp. Take a look at the Laravel documentation about routes with regexp params.

**Comment by Dartui** [comment]
As far as I know Laravel will change address, for example /category/my-category/some-slug, into 3 parameters: `category`, `my-category` and `some-slug`. So in route `/{path}` under `path` variable will be only `category`, not whole address.

**Comment by jgrossi** [comment]
@Dartui even setting the regexp `->where('path', '(.+)')`?

**Comment by Dartui** [comment]
@jgrossi as far as I know, yes. I will try it in a minute and give feedback here

**Comment by Dartui** [comment]
Nevermind, it works like a charm. Maybe in the past I have done something wrong :wink:

**Comment by drosendo** [comment]
Hey guys!

But hte question maintains, how to generalize this and always get the correct page/post_type/whatever data from WordPress with corcel?

Cheers,
David

**Comment by jgrossi** [comment]
@Dartui nice 😉

@drosendo there's no right way to do this, you have to build it according to your logic, you can prefix it with some letter to make easier to identify:

```
/p/* is a post
/c/* is category
```

Just an idea. But the goal here is not to fix this path like WordPress does, but make it customizable, according to your needs.

**Comment by Dartui** [comment]
@drosendo there is no 100% correct answer. Routes with languages are added by plugin to WordPress, so if one plugin can do that then every plugin can modify WP routes. You cannot create universal route for everything.

**Comment by drosendo** [comment]
damm... 👍 

Yeah I have to work it out. thanks @jgrossi @Dartui

**Comment by jgrossi** [comment]
welcome @drosendo 😃
