### ISSUE TITLE
Cannot access logged in WordPress user from Laravel app

### ISSUE THREAD

**Issue by nkrh** [jgrossi/corcel#366]
- Corcel Version: 2.4
- Laravel Version: 5.4
- WordPress Version: 4.6.6

Hi,

I'm going to access logged in WordPress user from Laravel app. This is my hook on WordPress:

```
function corcel_login($user_login, $user) {
    Corcel\Database::connect([
        'database'  => 'test',
        'username'  => 'root',
        'password'  => '',
        'prefix'    => 'wp_' 
     ]);
    
    $userProvider = new Corcel\Laravel\Auth\AuthUserProvider;
    $user = $userProvider->retrieveByCredentials(['username' => 'test']);
	
    if(!is_null($user)) {
        $userProvider->validateCredentials($user, ['password' => 'test']
    }
}
add_action('wp_login', 'corcel_login', 1, 2);
```
The login process is success in WordPress but in my Laravel controller the user, `Auth::user()`, always returns null. 

Am I missing something?

Thanks!

**Comment by rundef** [comment]
Hi,

The `validateCredentials` doesn't actually login the user, it just checks that the password is OK for the given user.  You will have to login the user manually, for example:

```php
if ($userProvider->validateCredentials($user, ['password' => 'test']) {
    \Auth::login($user, true);
}
```

**Comment by jgrossi** [comment]
@nkrh are you on the WordPress app, right? because you cannot use WP hooks inside a Laravel app. Corcel does not support that. If you're inside the Laravel app, you can login a WP user, that's true, but I don't think you can get a logged WP user, because you're using different apps, and different sessions. Did I miss something about your question?

**Comment by nkrh** [comment]
@rundef Tried this, but it still did not log me in to the Laravel app.

@jgrossi Yep, I'm in the WordPress app. You can access WordPress logged in users by writing your own Guard: https://laravel.com/docs/5.5/authentication#adding-custom-guards. Using the Guard with this package is a great combination if you want WordPress manages your users in your Laravel app.

Thanks you all 😺
