### ISSUE TITLE
Post views count

### ISSUE THREAD

**Issue by AubakirovN** [jgrossi/corcel#368]
- Corcel Version: 2.5.x
- Framework Name & Version: Laravel 5.5.x
-WordPress Version: 4.8.3 

### Description:
Hello everyone!

How to do post view counter? I want to display post views count.
I think it is possible with meta data.

Thanks in advance!

### Steps To Reproduce:

**Comment by jgrossi** [comment]
Hi @AubakirovN. Are you using some type of plugin to collect the number of views?

**Comment by AubakirovN** [comment]
Hi!

No. I want to view counter without plugin.
I've heard that it is possible by meta data.
But I can't find solution yet.

For this we need Session and increment count, right?

**Comment by jgrossi** [comment]
@AubakirovN actually you can do this in the Laravel side, creating a database table to store the `post_id` and `counter`. Each time someone reach the "view post" page it increments the counter for that ID. Just that.
