### ISSUE TITLE
WPML

### ISSUE THREAD

**Issue by andreasbakir** [jgrossi/corcel#371]
Hi once again, I have been tinkering around with this awesome package, I am loving it! But I wanted to ask if WPML is supported, if so how does it work? If not I might help to build it :)

**Comment by jgrossi** [comment]
Hi @andreasbakir. There's no support for WPML yet. Would you be interested in creating that?

**Comment by andreasbakir** [comment]
I Will give it a try in January I am to busy at the moment

**Comment by jgrossi** [comment]
👍 let me know and we reopen this issue. Thanks!

**Comment by drosendo** [comment]
@andreasbakir check here what im doing

https://github.com/corcel/acf/issues/49#issuecomment-359013405

You may have to read the begining of issue also

Cheers,
David
