### ISSUE TITLE
Call to a member function connection() on null

### ISSUE THREAD

**Issue by amrokhudair** [jgrossi/corcel#372]
- Corcel Version: #.#.#
- Framework Name & Version:lumen
- PHP Version: 7
- Database Driver & Version:Mysql

### Description:
Hi
I installed the package on lumen ,when I want to use model , I get the error:
Call to a member function connection() on null
I used the below code to get the post info
     $post = \Corcel\Model\Post::find(31);

   echo $post->post_title;

My question is , where I should define the database connection??
### Steps To Reproduce:

**Comment by jgrossi** [comment]
Hi @amrokhudair first so sorry about the late answer. These last weeks were busy, really sorry for let you waiting so long.

Answering your questions just add a new connection on Laravel's `config/database.php` file. You can have more information here: https://laravel.com/docs/5.5/database#configuration
