### ISSUE TITLE
How to find WP User Role using Corcel from Laravel

### ISSUE THREAD

**Issue by adiyya** [jgrossi/corcel#374]
Hi Thanks for this Great Package.

- Corcel Version: 2.5
- Framework Name & Version: Laravel
- PHP Version: 7.0
- Database Driver & Version:

### Description:
How to find WP User Role using Corcel from Laravel

### Steps To Reproduce:
1. Get WP user details with User::find() method of Corcel
2. How to know the role of this user?

Thanks,
- Adi

**Comment by Dartui** [comment]
User details and role are stored in `usermeta` table. Try something like this for role: `$user->meta->get('wp_capabilities')`

**Comment by adiyya** [comment]
Thank you it resolved.

- Adi
