### ISSUE TITLE
How to get author posts, category posts, tag posts, post categories?

### ISSUE THREAD

**Issue by adiyya** [jgrossi/corcel#375]
- Corcel Version: 2.5
- Framework Name & Version: Laravel
- PHP Version: 7.0
- Database Driver & Version:

### Description:
How to get author posts? Means Need to get all posts of a particular posts. How to achieve it?

How to get category posts? I means how to get posts in a particular category.

How to get tagposts? I means how to get posts in a particular tag.

How to get post categories? how to get categories for a particular post

### Steps To Reproduce:

Thanks,
- Adi

**Comment by jgrossi** [comment]
Hi @adiyya thanks for sharing.

Corcel has relationships between its models, so you can do something like this:
```php
$posts = User::find(1)->posts;
echo $posts->first()->title;
```
All categories and tags are related to `Taxonomy` and `Term` classes. So to get all post's taxonomies:
```php
$taxonomies = Post::find(1)->taxonomies; // collection of Taxonomy classes
$taxonomies->first()->term; // Term instance
```
You even have the `$post->terms` array, like you can see in the `Post` class. 
```php
public function hasTerm($taxonomy, $term)
{
    return isset($this->terms[$taxonomy]) &&
        isset($this->terms[$taxonomy][$term]);
}
```

Hope this helps. 😉

**Comment by adiyya** [comment]
Thank you. It helps a lot.

Again saying thanks a lot for this package.

Thanks,
- Adi

**Comment by jgrossi** [comment]
welcome! 🙂
