### ISSUE TITLE
Mysql error

### ISSUE THREAD

**Issue by Giulia007** [jgrossi/corcel#376]
- Corcel Version: the latest
- Framework Name & Version: Laravel 5.5
- PHP Version: 7

Hi, I have just installed Corcel on a Laravel project (on Homestead - Vagrant), where WP and Laravel share the same DB with the default connection 'mysql'. I have to keep a single database, cannot have two of them. 

When running a simple query from the controller to try retrieving posts I get this error:
Base table or view not found: 1146 Table 'shared.posts' doesn't exist (SQL: select * from `posts` where `post_status` = publish)

I tried creating a custom Post model which extends the Corcel one, but it didn't help. 

Any hint on where the issue could be?

Thanks!

**Comment by jgrossi** [comment]
@Giulia007 hi thanks for sharing!

actually you have to set the `table_prefix` to `wp_`. I guess your WP install has `wp_` as prefix. So in your database connection `config/database.php` in the Laravel config you have to set that to make it working.

let me know! thanks!

**Comment by Giulia007** [comment]
I have done it and it works perfectly!! I believe it could be useful to have this hint added to the Github Corcel page.
Thank you soooo much for your help and the super fast reply!!

**Comment by Giulia007** [comment]
PS: since I was asked to add a prefix for Laravel tables, like 'la_' for instance, do you think this is still doable  now?
Thank you again! :)

**Comment by jgrossi** [comment]
the README file has a sample database configuration, but if you're able to, please send a PR adding a quote or note about the `wp_` prefix just below the table:

![](http://snaps.jgrossi.com/2018-01-18-pe7w0o4cfp.png)

Thanks for helping.

**Comment by Giulia007** [comment]
Ok! I will try to do it as soon as possible!

**Comment by jgrossi** [comment]
thanks! I'm gonna close this issue, but fell free to open it again if necessary! thanks
