### ISSUE TITLE
get posts for a certain category

### ISSUE THREAD

**Issue by maxifarcilli** [jgrossi/corcel#377]
- Corcel Version: 2.5.#
- Framework Name & Version: Laravel 5.5
- PHP Version: 7.2

I am new using corcel.
I want to get the posts(title, content) for a certain category to show in a view.

**Comment by Juhlinus** [comment]
https://github.com/corcel/corcel#taxonomies

> # Taxonomies
> 
> You can get taxonomies for a specific post like:
> 
> ```
> $post = Post::find(1);
> $taxonomy = $post->taxonomies()->first();
> echo $taxonomy->taxonomy;
> ```
> 
> Or you can search for posts using its taxonomies:
> 
> `$post = Post::taxonomy('category', 'php')->first();`
