### ISSUE TITLE
I can not search posts from a category

### ISSUE THREAD

**Issue by g3luka** [jgrossi/corcel#378]
- Corcel Version: 2.5
- Framework Name & Version: Laravel 5.5
- PHP Version: 7.1
- Database Driver & Version: 5.6

## Description:

I'm trying to do a category search to get your posts, but to no avail.
I tried two ways:

### Taxonomy::where('taxonomy', 'category')->slug('sports')->posts()->first();
Returns: "Call to undefined method Illuminate\Database\Query\Builder::posts()"

### Category::slug('sports')->posts()->first();
In this way it says that the Category model does not exist.

Could someone give me a hand?

**Comment by Dartui** [comment]
`Taxonomy::where('taxonomy', 'category')->slug('sports')` is still query builder, not taxonomy model. First, you have to get single taxonomy, then you can use `posts` relation.

```php
$category = Taxonomy::where('taxonomy', 'category')->slug('sports')->first();
$posts = $category->posts()->first();
```

**Comment by g3luka** [comment]
It worked!
So good to talk to anyone who knows.

Thank you very much.

And congratulations on the work. Excellent this project.
