### ISSUE TITLE
Laravel 5.6 support

### ISSUE THREAD

**Issue by jilster** [jgrossi/corcel#379]
- Corcel Version: 2.5.4
- Framework Name & Version: Laravel 5.6.0
- PHP Version: 7.1.4
- Database Driver & Version: MySQL 5.6.27

### Description:

I am trying to update Laravel to 5.6.0, but Corcel requires Laravel 5.5.*. I know Laravel 5.6 is very fresh (released yesterday), but could you look into supporting it? Thanks in advance!

### Steps To Reproduce:

- Update the Laravel version in composer.json to 5.6.0
- Run composer update

It wil log:

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - jgrossi/corcel v2.5.4 requires illuminate/support 5.5.* -> satisfiable by laravel/framework[v5.5.34], illuminate/support[v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28, v5.5.33, v5.5.34].`

**Comment by jgrossi** [comment]
Hey @jilster thanks for this. I'm gonna update Corcel soon, probably tomorrow, then we'll be Laravel 5.6 ready 😎

**Comment by jgrossi** [comment]
@jilster @jaggy done! 🍻Release `2.6.0` now supports Laravel 5.6 🎉
All tests are passing, but please let me know any weird behavior.

**Comment by jaggy** [comment]
That was amazing! Hope that wasn't too much pressure. Thanks so much. 🍻

**Comment by jilster** [comment]
Thanks, works like a charm!
