### ISSUE TITLE
How to get the meta_id for a specific meta_key

### ISSUE THREAD

**Issue by pixelpeter** [jgrossi/corcel#381]
- Corcel Version: 2.6.0
- Framework Name & Version: Laravel 5.6
- PHP Version:  7.1.x
- Database Driver & Version: MySQL 5.7.21

### Description:
I want to get the `meta_id` for a specific `meta_key` of the given `post_id`

### Steps To Reproduce:
This is what I'm doing so far:
```
$metas = Post::find($id)->meta;
$meta_id = $metas->firstWhere('meta_key', '_yoast_wpseo_metadesc')->meta_id;
$meta_value = $metas->_yoast_wpseo_metadesc;
```
Getting the `meta_value` is pretty straight forward and very Laravel like 👍🏻

Is there something similiar for getting the `meta_id` or am I missing something?

Thanks for your help

**Comment by jgrossi** [comment]
thanks for the issue @pixelpeter! you're doing it right. after the `firstWhere()` call you must get a `PostMeta` instance, then you have access to `meta_id` value as well.

double check if that records really exist in your database. try to debug it and see the results 💪
