### ISSUE TITLE
I don't really understand the proposal very well

### ISSUE THREAD

**Issue by ezequiel9** [jgrossi/corcel#385]
I don't understand why I would use this package? 

I was wondering, this only is usable for simple websites and blogs.. Using laravel only for routes and views it's a waste (I think would be better use angular or react for a best combination)

The problem with all the cms is when you need to create a big platforms or crm, you probably needs feel free to manage your own code as you want to create a complex features, so choose one framework to do that. 

In this case I found usable only for simple websites and blogs where you can use the data from wordpress. But repeat, I think would be better combination with any js framework.

It was just my opinion, what do you think about this?

Pd: Anyway your I like your idea and your code work really good!.  
Thanks

**Comment by codeserk** [comment]
This package provides a transparent layer between the CMS and your clients. But it's BE layer, you can use any framework you want if you use the laravel project as API and build your JS framework to use it. Or I think you can even use any JS framework you want to be running within the laravel project, injecting js in the blade files? (although not sure if that's ideal).

The point is that this is la layer in the BE and not in the FE, you should design your application with that in mind. And you should you this layer to add Security, Performance and maybe more business logic that you don't want to implement to in Wordpress; but no one disallows you from adding another FE (Vue, angular, react) layer that uses the data coming from the BE to build awesome apps :)

Hope that helped

**Comment by ezequiel9** [comment]
It make sense, thanks!.
