### ISSUE TITLE
Get Page By Full Url

### ISSUE THREAD

**Issue by matthewscalf** [jgrossi/corcel#386]
- Corcel Version: 2.5.4
- Framework Name & Version: Laravel
- PHP Version: PHP 7.1
- Database Driver & Version: 

### Description:

I need to be able to find a page by the full url. The wordpress site currently has page parents which means the url is {parentslug}/{pageslug} Searching by slug returns pages with the slug, no matter the depth. Any ideas here?

### Steps To Reproduce:

**Comment by Juhlinus** [comment]
Add the following method to Corcel\Model\Builder\PostBuilder and you should be good to go, provided that this is what you were hoping for.

**PostBuilder.php**
```
/**
 * @param  string $guid 
 * @return PostBuilder
 */
public function guid($guid)
{
    return $this->where('guid', $guid);
}
```

**Usage**
Passing the _guid_ will return the Post object.

```
$post = Post::find(1)->first();

// Returns post by guid
// Guid looks like this:
// http://wordpress.dev/?p=1
$postByGuid = Post::guid($post->guid)->first();
```

**Comment by matthewscalf** [comment]
Yeah but this doesn't take into account permalink settings. How would you go about doing that?

**Comment by Juhlinus** [comment]
> Yeah but this doesn't take into account permalink settings. How would you go about doing that?

In what way do you need to find a page by it's full url? Do you want to resolve a Post object when the user hits an endpoint? Do you want to be able to search for something using the full url and in turn handle the Post object in a controller?

**Comment by jgrossi** [comment]
Hey thanks for asking. Would you like to get the child page? If you have both parent and child page with the same slug so you want to get the child one, right?

In this case you can create a custom scope that explodes the URL by `/`, then check how deep you are, and then query the `wp_posts` table to find the page. Currently there's no ready to go method for that but you're welcome to send a PR.

ASAP I'm gonna try to implement this and let you know here anyway. 

Thanks.

**Comment by matthewscalf** [comment]
With permalinks for pages, the url is more like parent slug (recursive), then page slug. When searching for them in a controller where you are trying to match url structure, we need a way to find the proper page from the root url.


[Izoox, LLC]<https://www.izoox.com/>

Matthew Scalf / Founder / CEO
matt@izoox.com<mailto:matt@izoox.com> / (970) 497-2351 ext. 1001<tel:(970)%20497-2351;1001>

Izoox, LLC
Office: (855) GO-IZOOX / Fax: (888) 447-1356<tel:(888)%20447-1356>
PO Box 1026<x-apple-data-detectors://9/2>Ridgway, CO 81432<x-apple-data-detectors://9/2>
https://www.izoox.com<http://www.izoox.com/>

[Twitter] <https://twitter.com/IzooxWeb>  [Facebook]  <https://www.facebook.com/IzooxWeb>  [Google +]  <https://plus.google.com/+Izoox>  [LinkedIn]  <https://www.linkedin.com/company/izoox>

On Mar 4, 2018, at 7:12 AM, Junior Grossi <notifications@github.com<mailto:notifications@github.com>> wrote:


Hey thanks for asking. Would you like to get the child page? If you have both parent and child page with the same slug so you want to get the child one, right?

In this case you can create a custom scope that explodes the URL by /, then check how deep you are, and then query the wp_posts table to find the page. Currently there's no ready to go method for that but you're welcome to send a PR.

ASAP I'm gonna try to implement this and let you know here anyway.

Thanks.

**Comment by leafling** [comment]
Any progress on this?  I'm interested in finding a solution for this as well.

**Comment by jgrossi** [comment]
@leafling @matthewscalf @Juhlinus gonna take a look on that this week. sorry about being MIA these last weeks. thanks for the patience!

**Comment by matthewscalf** [comment]
Any news on this?

**Comment by curtisbelt** [comment]
Just passing by - sorry I do not use this project but I thought I may have some related info:

1) Never depend on `guid` for anything but what it is - a unique identifier. The guid is only the URL of the post __when it was created__ because WordPress borrows it, as it serves the purpose of a "globally unique value" well enough for their needs. [The codex recommends never updating the guid, even if you switch domains](https://codex.wordpress.org/Changing_The_Site_URL#Important_GUID_Note).

2) WordPress has a [`get_page_by_path` function ](https://codex.wordpress.org/Function_Reference/get_page_by_path)which is exactly what this issue is asking for, maybe it can be of use for implementing?

**Comment by jgrossi** [comment]
@matthewscalf @Juhlinus @leafling @CurtisBelt closing this issue. open a PR if anyone has a fix for this please. thank you!
