### ISSUE TITLE
create new users

### ISSUE THREAD

**Issue by rayaf** [jgrossi/corcel#387]
- Corcel Version: 2.6
- Framework Name & Version: Laravel 5.6
- PHP Version: 7.2.1

### Description:
I'm a beginner and trying to create users through laravel. Is it possible to do that?
I'd be grateful for the hand.

### Steps To Reproduce:

**Comment by Juhlinus** [comment]
I think you'd be better off reading through the Laravel documentation, seeing as this is not specific to Corcel.

https://laravel.com/docs/5.6/authentication

**Comment by jgrossi** [comment]
@rayaf @Juhlinus thanks for the comment. yes, you can add users using Laravel. it's an easy task, not complicated. just pay attention to the required fields the `wp_users` table requires. thanks!

**Comment by jgrossi** [comment]
and @Juhlinus thanks for answering 💪

**Comment by interludic** [comment]
Pretty sure op means to create  user on wordpress through corcel, for comments and uploading media (meta) etc..
