### ISSUE TITLE
Non posts items being returned 

### ISSUE THREAD

**Issue by vool** [jgrossi/corcel#390]
- Corcel Version: 2.4.1
- Framework Name & Version: laravel 5.4
- PHP Version: 7.1.2
- Database Driver & Version:

### Description:

Hi I dont know if I am doing something stupid but when I try to get all posts, pages and plugin stuff is (ie non published posts) also being returned.  

### Steps To Reproduce:

This returns non post items 

Corcel\Model\Post::published()->newest();

Thanks for a great lib

**Comment by vool** [comment]
Just to provide some more info, this is the query that is being generated: 

``
select count(*) as aggregate from `wp_posts` where `post_status` = 'publish'
select * from `wp_posts` where `post_status` = 'publish' limit 6 offset 0
``

If I add type('post') it works as expected  ie

Corcel\Model\Post::type('post')->published()->newest()

``
select count(*) as aggregate from `wp_posts` where `post_type` = 'post' and `post_status` = 'publish'
select * from `wp_posts` where `post_type` = 'post' and `post_status` = 'publish' order by `post_date` 
``

It's working fine for me now but is this the expected operation ?

**Comment by jgrossi** [comment]
Hi @vool thanks for sharing. Actually the `Post` class is the generic one, so using it you can query any post type. Other classes like `Page` already has a `$postType = 'page'` so it filters the post type.

One thing you could do is to extend `Corcel\Models\Post` class and then set the `$postType = 'post'`so when using it you'd get only posts with `post` type. 😉

**Comment by sagarnasit** [comment]
@jgrossi I would like to resolve this bug and want to do small contribution to this great library. Should we make one `generic` class something like `WPPost` and extend it other `post type models`? this way we can use `Post` model as `post_type='post'` and `WPPost` as base model for all post types. Please let me know your thoughts on this and suggest if you have better approach.

**Comment by jgrossi** [comment]
@sagarnasit thanks for your suggestion. I don't want to attach the `Post` class to a specific post type. I think having the `Post` as a generic class like WP does. actually, we could think on how to set a default post type, but this would impact on other relationships we have in Corcel, like terms, etc.
