### ISSUE TITLE
Does method stripShortcodes of trait Corcel\Concerns\Shortcodes delete shordcodes from content ?

### ISSUE THREAD

**Issue by niknickolas** [jgrossi/corcel#391]
- Corcel Version: v2.5.8
- Framework Name & Version: laravel 5.5
- PHP Version: 7.0

### Description:
Does  `Corcel\Concerns\Shortcodes::stripShortcodes` have the same behavior as php function `stripslashes`, I mean wether it delets any shortcodes from content  as like it does wp function `the_excerpt` when fetches text from `post_content` field if `post_excerpt` is empty   or am I wrong  ?

Thanks in advance.

**Comment by jgrossi** [comment]
Hey, sorry about the late answer! Actually, the `stripShortcodes()` only parses the shortcodes, for both `->post_content` and `->post_excerpt` fields. And if the excerpt is empty is does not return the content one. But this could be done easily 😎

**Comment by niknickolas** [comment]
Hello @jgrossi.
Thanks for the answer, maybe I'm wrong, but as for me, if there is a `strip` in the name of the method or function, then the method or function will delete something in the data it has transferred.

In this case, the `stripShortcodes` method converts` shortcode` to the output of the handler class of this `shortcode`.

Then the question is, how can I make the output of the content with the removal of all the shortcodes added to the post?


Thanks in advance.

**Comment by jgrossi** [comment]
hey @niknickolas sorry about being MIA. you can override the `Post::getContentAttribute()` to return the value without being parsed.

**Comment by jgrossi** [comment]
@niknickolas so you're saying that the `stripShortcodes()` method should be called for example `renderShortcodes()` right?

then you're asking for a method to remove/strip shortcodes in the post content:

```php
$content = 'this is [foo]a text[/foo] with a [bar]text[/bar] color';
$content = $this->stripShortcodes($content);
// $content now is 'this is  with a  color'
```
is this right?

**Comment by jgrossi** [comment]
@niknickolas or would you like to include inner texts too? 

```this is a text with a text color```
