### ISSUE TITLE
Additional paragraph tags <p> with shortcodes

### ISSUE THREAD

**Issue by pixelpeter** [jgrossi/corcel#394]
- Corcel Version: 2.6.1
- Framework Name & Version: Laravel 5.6.15
- PHP Version: 7.1
- Database Driver & Version: MySQL 5.7

### Description:
I get additional inserted `<p>` tags when getting a post with Corcel. 
This breaks the generated HTML when you replace your shortcode with e.g. a `<div>`
Inside wordpress there are no additional `<p>` tags and the shortcodes are replaced correctly so the site is displayed properly.

#### Original post from wordpress
Looks like this
```
Some text

[su_row] [su_column size="1/2"]

#### 1\. Some headline

Some more text

[/su_column] [/su_row] 
```

#### Corcel will return this
Before shortcode replacement
```
<p>Some text</p>

<p>[su_row] [su_column size="1/2"]</p>

<h4>1. Some headline</h4>

<p>Some more text</p>

<p>[/su_column] [/su_row]</p>
```

Will become this after shortcode replacement
```
<p>Some text</p>

<p><div class='flex'> <div class='w-full sm:w-1/2'></p>

<h4>1. Some headline</h4>

<p>Some more text</p>

<p></div></div></p>
```

#### Reformatted post from wordpress
Looks like this
```
Some text [su_row] [su_column size="1/2"]

#### 1\. Some headline

Some more text [/su_column] [/su_row] 
```

Will look like this
```

<p>Some text <div class='flex'> <div class='w-full sm:w-1/2'></p>

<h4>1. Some headline</h4>

<p>Some more text</div></div></p>
```

### There's nothing fancy going on in the Laravel Shortcode Classes
```
class SuRowStart implements \Corcel\Shortcode
{
    public function render(ShortcodeInterface $shortcode)
    {
        return "<div class='flex'>".$shortcode->getContent();
    }
}
```

```
class SuColumnStart implements \Corcel\Shortcode
{
    public function render(ShortcodeInterface $shortcode)
    {
        return "<div class='w-full sm:w-1/2'>".$shortcode->getContent();
    }
}
```

```
class SuRowEnd implements \Corcel\Shortcode
{
    public function render(ShortcodeInterface $shortcode)
    {
        return '</div>';
    }
}
```

```
class SuColumnEnd implements \Corcel\Shortcode
{
    public function render(ShortcodeInterface $shortcode)
    {
        return '</div>';
    }
}
```

```
// config/corcel.php

'shortcodes' => [
        'su_row' => \App\Shortcodes\SuRowStart::class,
        '/su_row' => \App\Shortcodes\SuRowEnd::class,
        'su_column' => \App\Shortcodes\SuColumnStart::class,
        '/su_column' => \App\Shortcodes\SuColumnEnd::class,
],
```

### Question

Is this the expected behavior or am I doing something wrong?

**Comment by pixelpeter** [comment]
Have you had time to look into it?

**Comment by jgrossi** [comment]
hey @pixelpeter sorry about being late! I was busy for a while. you're saying that you created some custom shortcodes, added them to the Corcel configuration file and it's not working? does it not parsing the shortcode? is that true? thanks!

**Comment by jgrossi** [comment]
@pixelpeter gonna take a look deeper into this and let you know. thanks! 😉
