### ISSUE TITLE
property 'meta_value' of non-object   fetchMetadataValue

### ISSUE THREAD

**Issue by iteearmah** [jgrossi/corcel#396]
- Corcel Version: 2.6.1
- Framework Name & Version: Laravel 5.6.15
- PHP Version: 7.2
- Database Driver & Version: Mysql

### Description:
```
ErrorException (E_ERROR)
Trying to get property 'meta_value' of non-object (View: 
/vendor/corcel/acf/src/Field/Image.php

protected function fetchMetadataValue(Post $attachment)
    {
        $meta = PostMeta::where('post_id', $attachment->ID)
                        ->where('meta_key', '_wp_attachment_metadata')
                        ->first();
 
        return unserialize($meta->meta_value);
    }
```

### Steps To Reproduce:

**Comment by jgrossi** [comment]
Hey @iteearmah thanks for the comment. Actually it seems your `$meta` variable is null, I guess you don't have in your database a row with `post_id => $attachment->ID` and `meta_key => _wp_attachment_metadata`. Double check that please 😎
