### ISSUE TITLE
WP Prefix on Tables

### ISSUE THREAD

**Issue by bryannbarbosa** [jgrossi/corcel#401]
- Corcel Version: 2.6.1
- Framework Name & Version: Laravel
- PHP Version: 7.1
- Database Driver & Version: MySQL

### Description:
I'm trying to get some posts in my view, but, without success, the problem seems to be referring to this:

`SQLSTATE [42S02]: Base table or view not found: 1146 Table 'mysqldatabase.posts' does not exist (SQL: select * from posts where post_status = publish)`

Should not I automatically check that there is a wp prefix in every wordpress related table?

Thank you in advance

### Steps To Reproduce:

**Comment by jgrossi** [comment]
Hey @bryannbarbosa thanks for the message. did you configure a new database connection in Laravel `config/database.php`? did you set the `prefix` there?

**Comment by bryannbarbosa** [comment]
@jgrossi Yes, I just forgot about it, I did not notice, everything is working!
