### ISSUE TITLE
Previously installed newer version of hautelook/phpass causing failed install.

### ISSUE THREAD

**Issue by audetcameron** [jgrossi/corcel#408]
Hello.
 I'm looking into trying Corcel for the first time.  Have you ever had an issue with dependencies ?
Is there a way to force Corcel to use the newer version of hautelook/phpass?
Thank you for your plugin / time.

- Corcel Version: #.#.#
- Framework Name & Version:
- PHP Version: 
- Database Driver & Version:

### Description:
using laravel 5.6. Trying a composer require jgrossi/corcel.
looks like an issue with an existing hautelook/phpass.

### Steps To Reproduce:
standard require.

## Console
$ composer require jgrossi/corcel
Using version ^2.6 for jgrossi/corcel
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for hautelook/phpass (locked at 0.3.5) -> satisfiable by hautelook/phpass[0.3.5].
    - jgrossi/corcel 2.6.x-dev requires hautelook/phpass 0.3.4 -> satisfiable by hautelook/phpass[0.3.4].
    - jgrossi/corcel v2.6.0 requires hautelook/phpass 0.3.4 -> satisfiable by hautelook/phpass[0.3.4].
    - jgrossi/corcel v2.6.1 requires hautelook/phpass 0.3.4 -> satisfiable by hautelook/phpass[0.3.4].
    - jgrossi/corcel v2.6.2 requires hautelook/phpass 0.3.4 -> satisfiable by hautelook/phpass[0.3.4].
    - Conclusion: don't install hautelook/phpass 0.3.4
    - Installation request for jgrossi/corcel ^2.6 -> satisfiable by jgrossi/corcel[2.6.x-dev, v2.6.0, v2.6.1, v2.6.2].

Installation failed, reverting ./composer.json to its original content.

#from my lock
            "name": "hautelook/phpass",
            "version": "0.3.5",

**Comment by jgrossi** [comment]
hi @audetcameron thanks for reporting! it seems that your app is requiring `hautelook/phpass#0.3.5`, am I correct? do you have something on your `composer.json` that shows that?

I've just created a laravel 5.6 app and installed `jgrossi/corcel` trying to reproduce your issue, but everything went fine. corcel requires `hautelook/phpass#0.3.4` but maybe some package you're using requires `0.3.5`.

can you double check that please? thanks for reporting! ❤️️

**Comment by jgrossi** [comment]
oh sorry, I missed the part you mention you're already using a newer version of `hautelook/phpass`. I'm gonna push a new release of corcel with `hautelook/phpass: 0.3.*` then. I think that's enough for what you need. hold on!

**Comment by audetcameron** [comment]
Thanks for the response!

unfortunately there is a 
 "name": "hautelook/phpass",
            "version": "0.3.5",

in my composer.lock  but nothing about it in my composer.json.
I have no idea what other require pulled it in or where it's being used.

Ideas on how to move forward?

**Comment by audetcameron** [comment]
Oh I think I found it. I may have a solution....  the mikemclin/laravel-wp-password  is asking for a version "0.3.*".  Maybe I can force an install of 3.4.

**Comment by jgrossi** [comment]
hey @audetcameron I already created the fix, but travis ci is not working well for me at the moment. I even created a PR for that I think may work for you. just waiting for them to fix my build, then I merge and create a new tag 😎

**Comment by jgrossi** [comment]
@audetcameron fixed on `v2.6.3`. update Corcel, please! 👍

**Comment by audetcameron** [comment]
👍 100% working and ready to go :)  @jgrossi   Thank you so much. I look forward to diving into Corcel!
