### ISSUE TITLE
Installing Issue

### ISSUE THREAD

**Issue by Ain477** [jgrossi/corcel#415]
- Corcel Version: #.#.#
- Framework Name & Version: Laravel 5.6.*
- PHP Version: ^7.1.*
- Database Driver & Version: 

### Description:
I'm seeing this error when tried to install, Hope you'll find all the info here
![screenshot_1](https://user-images.githubusercontent.com/26634947/45315327-f0b45d80-b555-11e8-8114-c807fd859ad9.png)

### Steps To Reproduce:
Just followed the instruction mentioned here https://github.com/corcel/corcel

**Comment by jgrossi** [comment]
@AinCoder it seems you're trying to install Corcel 2.7.0 with Laravel 5.6, correct? for Laravel 5.6 you should install Corcel 2.6.*
