### ISSUE TITLE
User Models

### ISSUE THREAD

**Issue by thiagof** [jgrossi/corcel#42]
Hi,

The user table is missing models, but isn't very hard to implement (it is like posts).
There's a Meta Model and Collection already.

Are you planning to get them in Corcel? Would accept PRs?

**Comment by thiagof** [comment]
I've just seen the `dev` branch and it looks promissing, will give a try.

Just thought it would be good to abstract the Meta classes, as they share functionality.

**Comment by rundef** [comment]
Hi,
Yes, you are welcome to make Pull Requests on the dev branch.
If you do, make sure to write the appropriate tests.

Thank you!

**Comment by jgrossi** [comment]
Hi @thiagof! Thanks for the message ;-)
You're welcome to send PR and make Corcel better. User integration is a very useful feature.
Cheers!
