### ISSUE TITLE
woocommerce

### ISSUE THREAD

**Issue by miladgh71** [jgrossi/corcel#432]
Hi Jgrossi 
Thank you for your awesome plugin
I created coecel plugin and when I want to use product model it doesn't work properly 
Sorry, I'm new in laravel

**Comment by jgrossi** [comment]
hey, @miladgh71 welcome 💪 the `corcel/woocommerce` plugin is still in development and has no documentation for now. but you are free to visit the source code and what you can do on https://github.com/corcel/woocommerce/

to install it just run `composer require corcel/woocommerce`. cheers! 👏🔥

**Comment by ManukMinasyan** [comment]
Hello, I am using "corcel / corcel". Created a "product" model. and I want to sort products by price. how can I do it ?
Thanks.

```php 
namespace App\Http\Models;

use Corcel\Model\Post as Corcel;
use Illuminate\Database\Eloquent\Builder;

class Product extends Corcel
{
    /**
     * The "booting" method of the model.
     *
     * @return void
     */
    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::addGlobalScope('post_type', function (Builder $builder) {
            $builder->where('post_type', '=', 'product');
        });
    }
}
```

**Comment by jgrossi** [comment]
take a look on corcel/woocommerce package. it has all models you need

**Comment by ManukMinasyan** [comment]
Can I use these 2 packages together?
corcel/corcel and  corcel/woocommerce
Thanks.

**Comment by jgrossi** [comment]
sure. corcel/corcel is the core, and corcel/woocommerce is an extension to provide you the necessary models for the woocommerce plugin. it's still in dev and missing docs, but works fine

**Comment by ManukMinasyan** [comment]
Thanks.
I have suggestions. Let's open the chat for this package.
There can discuss alto real time. I think it will be convenient

**Comment by jgrossi** [comment]
please open issues and we will be discuss as soon as possible for everyone

**Comment by ManukMinasyan** [comment]
```php
Symfony \ Component \ Debug \ Exception \ FatalErrorException (E_UNKNOWN)
Trait 'Corcel\Traits\AliasesTrait' not found
```

How I can fix it?

**Comment by ManukMinasyan** [comment]
```php
Model\Product.php

use Corcel\Concerns\Aliases;

 use Aliases;
```

working for me.

**Comment by Dartui** [comment]
Hi guys, really sorry that I have not maintained corcel/woocommerce for so long, but I am coming back! :) @ManukMinasyan if you have any suggestions feel free to open new issues on https://github.com/corcel/woocommerce/issues. Soon I will push some fixes and minor improvements, so in the near future it can be tagged as stable 1.0 version
