### ISSUE TITLE
Convert existing Laravel users to WordPress users

### ISSUE THREAD

**Issue by mboisvertdupras** [jgrossi/corcel#434]
- Corcel Version: 2.7
- Framework Name & Version: Laravel 5.7
- PHP Version: 7.2
- Database Driver & Version: MySQL 5.7

### Description:
I have an existing Laravel app I'd like to migrate to use WordPress as the backend CMS. I'm wondering if it would be possible to import all of my existing users from Laravel into WordPress.

**Comment by jgrossi** [comment]
@aft3rlife yes you can, but probably it's more a Eloquent task than Corcel's. you have to use `User` class with `create()` method, creating one by one. 

1. first get your users from Laravel db table;
2. map your local table fields to WP users fields (take a look in DB table in WP)
3. call `User::create($data)` after mapped all the user data you need

probably there's more work related to roles, etc, but this is a start point ;-)
