### ISSUE TITLE
Fetch posts by Tag

### ISSUE THREAD

**Issue by jeromie** [jgrossi/corcel#440]
- Corcel Version: 2.7
- Framework Name & Version: Laravel 5.7
- PHP Version: 7.1

### Description:
I am able to get posts by category using the below code:

`$cat = Taxonomy::where('taxonomy', 'category')->slug($category)->first();`

However, I need to get posts by tag. Can't figure out how to achieve this. Some help please?

**Comment by JmRy** [comment]
@jeromie A tag is a taxonomy so Post::taxonomy('post_tag', 'hello')->first()
