### ISSUE TITLE
PHP Notice:  compact(): Undefined variable: operator in /vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php on line 1229

### ISSUE THREAD

**Issue by peratik** [jgrossi/corcel#442]
- Corcel Version: 2.5
- Framework Name & Version: Laravel 5.5
- PHP Version: 7.3.1
- Database Driver & Version: MySQL, 5.7

### Description:
code:
`		$posts = \Corcel\Model\Post::type('post')->taxonomy('category', 'reportage')->published()->newest()->with('attachment')->paginate(10);
`
error: 

> PHP Notice:  compact(): Undefined variable: operator in /vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php on line 1229

### Steps To Reproduce:
If a query has taxonomy() filter the error is displayed.

**Comment by jgrossi** [comment]
@peratik can you debug this deeper to find where is the issue in Corcel's side? it's failing on Eloquent layer, so probably some code in Corcel is wrong when filtering taxonomies like you said. let me know please.
