### ISSUE TITLE
upload and Save Feature Image

### ISSUE THREAD

**Issue by amigogobara** [jgrossi/corcel#446]
- Corcel Version: 2.7
- Framework Laravel 5.7:
- PHP Version 7.2: 
- Database mysql & 5.7:

I want to save and upload feature image by corcel package and don't know how I make it by this package

**Comment by jgrossi** [comment]
@amigogobara you can do that for sure. Corcel is built on top of Laravel's Eloquent ORM, so I suggest you to read more about Eloquent on how to insert rows with/without relations:

https://laravel.com/docs/5.8/eloquent
