### ISSUE TITLE
Retrive all Available Post Types In Wordpress

### ISSUE THREAD

**Issue by oluomotoso** [jgrossi/corcel#447]
- Corcel Version: 2.7
- Framework Name & Version: Laravel 5.7
- PHP Version: 7.2
- Database Driver & Version:
Mysql 5.7
### Description:

I need to get all post types. I know there's a method to access types from post but what I need is something like PostType::all(); or any equivalent
### Steps To Reproduce:

**Comment by namnguyen2091** [comment]
Oh my God.

**Comment by jgrossi** [comment]
hi @oluomotoso! in this case you have to build your own query, something like:
```php
$allTypes = Post::select('post_type')->groupBy('post_type')->get()->pluck('post_type')->toArray();
```
of course, there are many other ways to do that, but that's first coming in my mind ;-)
