### ISSUE TITLE
laravel 5.8 ? 

### ISSUE THREAD

**Issue by breizhwave** [jgrossi/corcel#449]
Hi updating to laravel 5.8 gives me dependency error

 Problem 1
    - Conclusion: remove laravel/framework v5.8.3
    - Conclusion: don't install laravel/framework v5.8.3
    - Conclusion: don't install laravel/framework v5.8.2
    - Conclusion: don't install laravel/framework v5.8.1
    - Conclusion: don't install laravel/framework v5.8.0
    - jgrossi/corcel 2.7.x-dev requires illuminate/support 5.7.* -> satisfiable by laravel/framework[5.7.x-dev], illuminate/support[5.7.17, 5.7.18, 5.7.19, 5.7.x-dev, v5.7.0, v5.7.1, v5.7.10, v5.7.11, v5.7.15, v5.7.2, v5.7.20, v5.7.21, v5.7.22, v5.7.23, v5.7.26, v5.7.27, v5.7.28, v5.7.3, v5.7.4, v5.7.5, v5.7.6, v5.7.7, v5.7.8, v5.7.9].
    - jgrossi/corcel v2.7.0 requires illuminate/support 5.7.* -> satisfiable by laravel/framework[5.7.x-dev], illuminate/support[5.7.17, 5.7.18, 5.7.19, 5.7.x-dev, v5.7.0, v5.7.1, v5.7.10, v5.7.11, v5.7.15, v5.7.2, v5.7.20, v5.7.21, v5.7.22, v5.7.23, v5.7.26, v5.7.27, v5.7.28, v5.7.3, v5.7.4, v5.7.5, v5.7.6, v5.7.7, v5.7.8, v5.7.9].
    - jgrossi/corcel v2.7.1 requires illuminate/support 5.7.* -> satisfiable by laravel/framework[5.7.x-dev], illuminate/support[5.7.17, 5.7.18, 5.7.19, 5.7.x-dev, v5.7.0, v5.7.1, v5.7.10, v5.7.11, v5.7.15, v5.7.2, v5.7.20, v5.7.21, v5.7.22, v5.7.23, v5.7.26, v5.7.27, v5.7.28, v5.7.3, v5.7.4, v5.7.5, v5.7.6, v5.7.7, v5.7.8, v5.7.9].
    - jgrossi/corcel v2.7.2 requires illuminate/support 5.7.* -> satisfiable by laravel/framework[5.7.x-dev], illuminate/support[5.7.17, 5.7.18, 5.7.19, 5.7.x-dev, v5.7.0, v5.7.1, v5.7.10, v5.7.11, v5.7.15, v5.7.2, v5.7.20, v5.7.21, v5.7.22, v5.7.23, v5.7.26, v5.7.27, v5.7.28, v5.7.3, v5.7.4, v5.7.5, v5.7.6, v5.7.7, v5.7.8, v5.7.9].
    - jgrossi/corcel v2.7.3 requires illuminate/support 5.7.* -> satisfiable by laravel/framework[5.7.x-dev], illuminate/support[5.7.17, 5.7.18, 5.7.19, 5.7.x-dev, v5.7.0, v5.7.1, v5.7.10, v5.7.11, v5.7.15, v5.7.2, v5.7.20, v5.7.21, v5.7.22, v5.7.23, v5.7.26, v5.7.27, v5.7.28, v5.7.3, v5.7.4, v5.7.5, v5.7.6, v5.7.7, v5.7.8, v5.7.9].
    - jgrossi/corcel v2.7.4 requires illuminate/support 5.7.* -> satisfiable by laravel/framework[5.7.x-dev], illuminate/support[5.7.17, 5.7.18, 5.7.19, 5.7.x-dev, v5.7.0, v5.7.1, v5.7.10, v5.7.11, v5.7.15, v5.7.2, v5.7.20, v5.7.21, v5.7.22, v5.7.23, v5.7.26, v5.7.27, v5.7.28, v5.7.3, v5.7.4, v5.7.5, v5.7.6, v5.7.7, v5.7.8, v5.7.9].
    - Can only install one of: laravel/framework[5.8.x-dev, 5.7.x-dev].
    - don't install illuminate/support 5.7.17|don't install laravel/framework 5.8.x-dev
    - don't install illuminate/support 5.7.18|don't install laravel/framework 5.8.x-dev
    - don't install illuminate/support 5.7.19|don't install laravel/framework 5.8.x-dev
    - don't install illuminate/support 5.7.x-dev|don't install laravel/framework 5.8.x-dev
    - don't install illuminate/support v5.7.0|don't install laravel/framework 5.8.x-dev
    - don't install illuminate/support v5.7.1|don't install laravel/framework 5.8.x-dev
    - don't install illuminate/support v5.7.10|don't install laravel/framework 5.8.x-dev
    - don't install illuminate/support v5.7.11|don't install laravel/framework 5.8.x-dev
    - don't install illuminate/support v5.7.15|don't install laravel/framework 5.8.x-dev
    - don't install illuminate/support v5.7.2|don't install laravel/framework 5.8.x-dev
    - don't install illuminate/support v5.7.20|don't install laravel/framework 5.8.x-dev
    - don't install illuminate/support v5.7.21|don't install laravel/framework 5.8.x-dev
    - don't install illuminate/support v5.7.22|don't install laravel/framework 5.8.x-dev
    - don't install illuminate/support v5.7.23|don't install laravel/framework 5.8.x-dev
    - don't install illuminate/support v5.7.26|don't install laravel/framework 5.8.x-dev
    - don't install illuminate/support v5.7.27|don't install laravel/framework 5.8.x-dev
    - don't install illuminate/support v5.7.28|don't install laravel/framework 5.8.x-dev
    - don't install illuminate/support v5.7.3|don't install laravel/framework 5.8.x-dev
    - don't install illuminate/support v5.7.4|don't install laravel/framework 5.8.x-dev
    - don't install illuminate/support v5.7.5|don't install laravel/framework 5.8.x-dev
    - don't install illuminate/support v5.7.6|don't install laravel/framework 5.8.x-dev
    - don't install illuminate/support v5.7.7|don't install laravel/framework 5.8.x-dev
    - don't install illuminate/support v5.7.8|don't install laravel/framework 5.8.x-dev
    - don't install illuminate/support v5.7.9|don't install laravel/framework 5.8.x-dev
    - Installation request for laravel/framework 5.8.* -> satisfiable by laravel/framework[5.8.x-dev, v5.8.0, v5.8.1, v5.8.2, v5.8.3].
    - Installation request for jgrossi/corcel 2.7.* -> satisfiable by jgrossi/corcel[2.7.x-dev, v2.7.0, v2.7.1, v2.7.2, v2.7.3, v2.7.4].

**Comment by andreacivita** [comment]
I've just forked this project. 
Laravel 5.8 doesn't introduce so many changes, so you just need to update dependencies in composer.json
I'm submitting a pull request.

**Comment by carusogabriel** [comment]
Looks like the v2.8 now supports Laravel 5.8.

**Comment by jgrossi** [comment]
@andreacivita exactly like @carusogabriel said (thanks mate!) we do have a 2.8 branch that has native support to laravel 5.8. let me know if you need any other help please. cheers
