### ISSUE TITLE
ThumbnailMeta exception

### ISSUE THREAD

**Issue by benrolfe** [jgrossi/corcel#452]
- Corcel Version: 2.4.1
- Framework Name & Version:
- PHP Version: 7.2
- Database Driver & Version: MySQL

### Description:
When a Post is missing a thumbnail it throws an exception when looping over posts with `foreach`.

`(1/1) FatalErrorException
Method Corcel\Model\Meta\ThumbnailMeta::__toString() must not throw an exception, caught ErrorException: Trying to get property of non-object`

### Steps To Reproduce:
```
$posts = App\Post::type('post')->published()->orderBy('post_date', 'desc')->search(request('q'))->simplePaginate(9);

@foreach ($posts as $post)
@endforeach
```

**Comment by jgrossi** [comment]
hey @benrolfe thanks for reporting. it seems the only point we use `ThumbnailMeta` in `Post` class it's in `thumbnail()` relation. are you calling it anywhere? just trying to get more information about that. cheers
