### ISSUE TITLE
How to Implement Common Shortcode

### ISSUE THREAD

**Issue by ospira** [jgrossi/corcel#466]
- Corcel Version: v2.8.0
- Framework Name & Version: Laravel v5.8.19
- PHP Version: 7.2.17 
- Database Driver & Version: mysql

### Description:

Firstly, thank you so much for this package. It is proving quite helpful in a project of mine! 

However, the [shortcode example ](https://github.com/corcel/corcel#-shortcodes) is quite unintelligible to me 😪. How would I implement a common shortcode, such as this standard one in WordPress:

https://codex.wordpress.org/Caption_Shortcode

I really would appreciate help on this!

I've created a class, CaptionShortcode.php in my App directory.

```
<?php
class CaptionShortcode implements \Corcel\Shortcode
{
    /**
     * @param ShortcodeInterface $shortcode
     * @return string
     */
    public function render(ShortcodeInterface $shortcode)
    {
        return sprintf('<figure %s%s%sclass="%s">%s%s</figure>',
1	                        $id,
	                        $describedby,
	                        $style,
	                        esc_attr( $class ),
                       sprintf(
                               '<figcaption %sclass="wp-caption-text">%s</figcaption>',
	                                $caption_id,
	                                $atts['caption']
	                        )
	                );

    }
}
?> 
```

But I'm not sure what to put in the render statement, and more importantly, how to test that statement by calling it into my post that I'm fetching.

In the docs, the example is this:

```
Post::addShortcode('gallery', function ($shortcode) {
    return $shortcode->getName() . '.' . $shortcode->getParameter('id');
});
$post = Post::find(1);
echo $post->content;
```

What does `gallery` refer to in this case? And the argument `$shortcode`  and the methods on it, where do those come from? I've added my shortcode in the config, but again, this step doesn't make sense to me. I'd really appreciate an end-to-end implementation of the captions shortcode in Corcel. Thanks so much!

**Comment by ospira** [comment]
never mind! I figured it out 😅😅

**Comment by jgrossi** [comment]
@ospira if you can share the solution it would be nice for the future! thanks

**Comment by JmRy** [comment]
@jgrossi and @all 

Basic example of the [caption][/caption] shortcode implementation

**config/corcel.php**

    'shortcodes' => [
        'caption' => App\Shortcodes\CaptionShortcode::class,
    ],

 **App\Shortcodes\CaptionShortcode.class**

 ```
<?php
  
  namespace App\Shortcodes;
  
  use Corcel\Shortcode;
  use Thunder\Shortcode\Shortcode\ShortcodeInterface;
  
  class CaptionShortcode implements Shortcode
  {
    
    public function render(ShortcodeInterface $shortcode)
    {
      $atts = [
        'align' => 'alignnone',
        'caption' => '',
        'class' => '',
        'style' => ''
      ];
      
      $params = $shortcode->getParameters();
      
      if (preg_match('#((?:<a [^>]+>\s*)?<img [^>]+>(?:\s*</a>)?)(.*)#is',  
        $shortcode->getTextContent(), $matches)) {
        $content = $matches[1];
        $atts['caption'] = trim($matches[2]);
      } else {
        $content = $shortcode->getTextContent();
      }
      
      $atts['width'] = (int) $params['width'];
      
      if ($atts['width'] < 1 || empty($atts['caption'])) {
        return $content;
      } elseif ($atts['width'] >= 1) {
        $atts['style'] = sprintf(' style="width:%dpx" ', $atts['width']);
      }
      
      $atts['class'] = sprintf('wp-caption %s', $params['align'] ? $params['align'] : $atts['align']);
      
      return sprintf(
        '<figure %sclass="%s">%s%s</figure>',
        $atts['style'],
        $atts['class'],
        $content,
        sprintf('<figcaption class="wp-caption-text">%s</figcaption>', $atts['caption'])
      );
      
    }
  }
```
**Post content**
```
[caption id="attachment_1244" align="alignright" width="450"]<img class="wp-image-1244 size-full" src="http://blog.local/media/DFR66.jpg" alt="Collioure" width="450" height="244" /> © PIL - Fotolia[/caption]
```

**Render**
```
   <figure style="width:450px" class="wp-caption alignright">
       <img class="wp-image-1244 size- full" src="http://blog.local/media/DFR66.jpg" 
       alt="Collioure" width="450" height="244">
       <figcaption class="wp-caption-text">© PIL - Fotolia</figcaption>
    </figure>
```
I deleted the id and aria attributes but just re-read the code function in the codex [Caption_Shortcode](https://codex.wordpress.org/Caption_Shortcode)  to put them back

;-)
