### ISSUE TITLE
Gravity Forms support?

### ISSUE THREAD

**Issue by coccoinomane** [jgrossi/corcel#468]
Hello!

First of all, thank you for developing this great tool... WordPress is such an evolved ecosystem and being able to use it with Laravel is fantastic.

Here's my question: has anybody had success using the Gravity Forms plugin with Corcel?
This is an awesome plugin to create even very complex forms in a few steps directly in the admin panel. 
It is IMO more user-friendly than Contact Forms 7 and it has many available integrations: Zapier, MailChimp, PayPal, Stripe...

In particular, I am wondering if the email notification system works and if using complex fields such as product fields is allowed in Corcel.

Thank you for your time,
Guido

- Framework Name & Version: Laravel 5.6
- PHP Version: 7.1
- Database Driver & Version: MySql 5.6

**Comment by Mghobadid** [comment]
Gravity Forms is a plugin , so use custom table and function , in back end and front,
yo need implement all this functions and tables  . 
in fact you must write a new Gravity Forms in laravel 😐

**Comment by coccoinomane** [comment]
Ok I see, thank you Mghobadid!
I am closing the issue.
Guido
