### ISSUE TITLE
Let's move Corcel up!!!

### ISSUE THREAD

**Issue by jgrossi** [jgrossi/corcel#47]
Hi guys!

First thank you for all contributions Corcel had last months :D

I'd like to propose the creation of a Slack channel. What do you think? We can add contributions (and followers) and get discussions about new improvements and features, what they want, etc.

What do you think about it? It'll be nice to add more administrators too, merging pull request, checking code, etc.

Cheers :-)

CC: @yoramdelangen @jeffersonsouza @thiagof @ashwin-sureshkumar @kriskbx @bruno-barros @rundef

**Comment by kriskbx** [comment]
Count me in!

**Comment by thiagof** [comment]
There is a roadmap?
Not sure how the package can grow.. The use case sounds simple.

**Comment by jgrossi** [comment]
Thanks @kriskbx!
Hi @thiagof! There's a good opportunity to create the roadmap :D

**Comment by jeffersonsouza** [comment]
This will be great! I want to return to contribute in open source projects! 

Count me in!

**Comment by josec89** [comment]
Is there a slack channel already :O?

**Comment by jgrossi** [comment]
Hi @josec89 I'm gonna add you in Slack channel. But it's not active yet, but you can help us ;-)

**Comment by josec89** [comment]
@jgrossi how can I help with that? Let me know :)

**Comment by jgrossi** [comment]
You are already helping us @josec89 hehe. I think the next move to corcel is to integrate front end features (rewriting the code, of course), to work with database collected data.

Another point is to convert the PHPUnit tests using Sqlite and not MySQL, but I'm already working in this feature.

I think would be nice to improve the README file to include all new features you've developed to Corcel. I think with this finished and all tests ok we change `dev-master` to our first release :-)
