### ISSUE TITLE
get popular posts

### ISSUE THREAD

**Issue by jumper01** [jgrossi/corcel#471]
- Corcel Version:  2.8
- Framework Name & Version: laravel 5.8
- PHP Version: >7.1
- Database Driver & Version: mysql

### Description:
how can i get popular posts like this php code  in cocrel plz :

$popularpost = new WP_Query( array( 'posts_per_page' => 4, 'meta_key' => 'wpb_post_views_count', 'orderby' => 'meta_value_num', 'order' => 'DESC'  ) );

Thank you

**Comment by Mghobadid** [comment]
first , yo need to save post view in a meta , 
so  in post page , count the view and then save in in meta filed.
then order the posts by meta.

**Comment by jgrossi** [comment]
@jumper01 let me know if you need any help here, but since it has been some months after @Mghobadid suggestion I guess you have fixed the problem. cheers
