### ISSUE TITLE
Laravel 6.0 support and semver

### ISSUE THREAD

**Issue by roelofr** [jgrossi/corcel#477]
- Corcel Version: latest (5.8)
- Framework Name & Version: Laravel 6.0
- PHP Version: 7.3.9-1+ubuntu19.04.1+deb.sury.org+1
- Database Driver & Version: PDO_MySQL @ 7.3.9-1+ubuntu19.04.1+deb.sury.org+1

### Description:
There is currently no support for Laravel 6 due to the new version constraints (`^6.0`). Bumping the version seems to work just okay, but maybe this is the moment to open a small discussion:

**Should Corcel join with Laravel's switch to Semantic Versioning?** I'd recommend bumping the version to `3.0`, since switching to semver is a breaking change in and of itself.

Just an opinion, but it seems like a good moment to poll this.

**Comment by jgrossi** [comment]
hey, agree! it's a good time to move to v3 in this case. can you work on a PR for that please?

**Comment by roelofr** [comment]
Done, the pull request is available in #478.

**Comment by roelofr** [comment]
Merged in #478,
