### ISSUE TITLE
Dependencies in composer.json

### ISSUE THREAD

**Issue by wateryoma** [jgrossi/corcel#48]
Hey, thanks for awesome package.
This part
```json
 "php":  ">=5.3.0",
"illuminate/database": "*"
```
is a bit confusing in your [composer.json](https://github.com/jgrossi/corcel/blob/master/composer.json#L16), since latest illuminate/database require php >=5.6.4

**Comment by jgrossi** [comment]
Hey @wateryoma! Thanks for the support. The `illuminate/database` requires php `5.5.9` and you're right :-) I'm gonna change to a previous version of illuminate/database, but I think we should change that to at least php `5.4`.  Thanks :D

**Comment by wateryoma** [comment]
agree for 5.4
hope my dev speed with your package will be as lightning speed as your answer to this issue xD

**Comment by jgrossi** [comment]
Hahahah @wateryoma! I was on Github checking some infos and just received your message hehe ;-) Welcome!

**Comment by wateryoma** [comment]
thanks!)
btw 
```json
"illuminate/database": "5.0.*"
```
fixed issues this php version for me

**Comment by jgrossi** [comment]
Done! ;-) Changed PHP version at least to `5.4.0` and `illuminate/database` to `5.0.*`.
Thanks @wateryoma :-)
