### ISSUE TITLE
Integrity constraint violation with PostBuilder where clause

### ISSUE THREAD

**Issue by zeroiszero** [jgrossi/corcel#483]
- Corcel Version: 3.0.0
- Framework Name & Version: Laravel version 6
- PHP Version: >= 7.2
- Database Driver & Version: MariaDB 10.3.14

### Description:
With the default where clause for post_type in PostBuilder. #326

Integrity issue will occur when using complex query. 
This is the error i get when using with [TNTSearch](https://github.com/teamtnt/laravel-scout-tntsearch-driver):
<img width="1440" alt="Screenshot 2019-09-24 at 3 38 00 PM" src="https://user-images.githubusercontent.com/20971727/65492283-3a62b280-dee3-11e9-87c2-96f00596df15.png">

### Steps To Reproduce:
using with [TNTSearch](https://github.com/teamtnt/laravel-scout-tntsearch-driver):
```
$post = \App\TntSearchPostModel::search($request->q)->paginate(5);
```

### Fixes

To fix this, has to add table name to the where clause:
```
    /**
     * @param string $type
     * @return PostBuilder
     */
    public function type($type)
    {
        return $this->where( $this->model->getTable() . '.post_type', $type);
    }
```

Let me know if I can do a pull request for this.

**Comment by jgrossi** [comment]
@zeroiszero hey you're welcome to send a PR to fix this 🎉 thank you!
