### ISSUE TITLE
Displaying video embeds

### ISSUE THREAD

**Issue by LarryBarker** [jgrossi/corcel#488]
- Corcel Version: 2.5
- Framework Name & Version: Laravel 5.5
- PHP Version: 7.3
- Database Driver & Version: MySQL 5.7

### Description:
Our wordpress sites are using the gutenberg editor (😠 ) and I'm having issues displayed youtube video blocks within my Laravel site. The only thing that is coming thru is the url:

https://www.youtube.com/watch?v=aVSp46nI_7E&amp;feature=youtu.be

I've tried changing the block type, editing as html, and even inserting the raw iframe from YouTube, but the Wordpress editor keeps converting it to a different format.

I looked thru the issues and did not see anything related to this so I'm opening a new issue in hopes that someone with a little more experience can provide some suggestions.

### Steps To Reproduce:

1. Create a new post in Wordpress 5 (with Gutenberg)
2. Embed a youtube video
3. View the post in a laravel blade template
4. See the url is output and not the video

**Comment by janboddez** [comment]
Pretty sure Corcel just fetches whatever post content is in the database, and does not apply any Gutenberg-related filters (or any other filters, for that matter, like `wpautop()` if you used the classic editor). I'm afraid this really is WordPress's own editor at work.

A solution would be to write your own Laravel accessor. Something like `getContent()` inside a child class of `Corcel\Model\Post`, and use regex or a similar solution to replace the link with a proper embed, or resort to JavaScript to do the same on the front end.

**Comment by LarryBarker** [comment]
@janboddez Yeah, I was afraid of that. Thanks for the follow up.
