### ISSUE TITLE
Plan for releases ?

### ISSUE THREAD

**Issue by jvelo** [jgrossi/corcel#49]
Hi ! 
Corcel looks pretty sweet ; is there any plan for making release(s) in the future so that we don't have to depend on ```dev-master``` ?

Thanks

**Comment by jgrossi** [comment]
Hey @jvelo! Thanks for the message ;-) 
The `dev-master` branch is running well. We're finishing tests and we're going to merge into `master` branch soon, maybe the next days. Any question just ask :D

**Comment by arifr007** [comment]
hey jgrossi good work you help me a lot,
how about you make function/model to handle wp user auth? it will be really good feature i think :D

**Comment by jgrossi** [comment]
That's a very interesting suggestion @arifr007! We already have User model working well to get data from Wordpress databases. The point here is about Auth. Wordpress has it's own way to make authentication, using it's own functions.

I don't know how we can implement this feature. I think maybe we'll have to rewrite the Wordpress auth feature to make this possible, but that's a very good point :-)

Let's think about it and make Corcel better and better. Thanks for the support.

**Comment by josec89** [comment]
Hmm...

Maybe the simplest way to do this is creating a new *Middleware* which checks if the user is authenticated; and then a method that checks if a pair user/password is stored in the db (`sha1(password)` ?). Or even remove the Middleware and check manually in the controllers, or whatever middle layer you have implemented on your project.

**Comment by jgrossi** [comment]
Nice @josec89! We can implement Corcel Middleware using Wordpress features, not Laravel, for example. Corcel is not only for Laravel and can be used with any framework, so the implementation has to be more focused on Wordpress code. Nice job ;-)

**Comment by rundef** [comment]
In my case, I included `wp-load.php` and I auth the users using the wp_authenticate function.
And I created a middleware that verify is the user is connected by using WordPress `is_user_logged_in` function.

But yeah, that could all be handled by Corcel :)

**Comment by hootlex** [comment]
+1 for a release! :)

**Comment by jgrossi** [comment]
Hey guys! Now we have our first release :-)

Corcel now is `v1.0.0`.

I'd like to thank all contributos and everyone that in someway support this project. Thanks a lot.
