### ISSUE TITLE
Question about using with different post types

### ISSUE THREAD

**Issue by LarryBarker** [jgrossi/corcel#491]
- Corcel Version: 2.5
- Framework Name & Version: Laravel 5.5
- PHP Version: 7.3
- Database Driver & Version: MySQL 5.7

### Description:
This is more of a general question, but I'm interested in using Corcel to retrieve different types of posts. Specifically, the WP site I'm integrating with uses The Events Calendar. I would like to display these events in our Laravel site, with as much information as possible.

I'm not having any issues connecting to the WP database or even pulling the posts,
`Event::newest()->published()->first()` works fine: 
![image](https://user-images.githubusercontent.com/28734844/66514814-85fc8b00-eaa3-11e9-9dd4-96e3937fe0f0.png)

I'm more interested in better understanding how the event data is available in this model. For example, the WP site outputs this event like this:
![image](https://user-images.githubusercontent.com/28734844/66515487-d4f6f000-eaa4-11e9-81db-68141c6dd354.png)

Apologies for the redacted screen shot, the event has some sensitive information my manager dos not want shared publicly. 

Any feedback or suggestions are greatly appreciated, thank you!

**Comment by jgrossi** [comment]
hi @LarBearrr an event, using your case, is a simple post managed by WP. once you get an event you will get a post with all information. how "the events calendar" stores data I don't know, but if it's not at post level for sure it's using metadata, so you can use `$event->meta` for that, where you should get all custom fields for that post. hope it helps. cheers 💪
