### ISSUE TITLE
Using Policies. 

### ISSUE THREAD

**Issue by audetcameron** [jgrossi/corcel#492]
SOLVED

jgrossi/corcel": "^3.0
Laravel 6.0
- 7.3
-mysql

### Description:
I have created some laravel models.  I am trying to create policies so the user->can('view', SomeModel);  but, when using the corcel user model I get this error 

```
Call to undefined method App\User::can()
```

If I change the corcel user model to 
```
use Illuminate\Foundation\Auth\User as Authenticatable;
class User extends Authenticatable implements  CanResetPassword

```

it works, however I feel like now I would be missing all of the use Corcel\Model;  methods.
Has anyone had success getting laravel policies to work with the Corcel user model?

______________________________
Solved
I created my own user model extending Corcel User and implementing the AuthorizableContract

**Comment by jgrossi** [comment]
@audetcameron thanks for the message. if you take a look on `Illuminate\Foundation\Auth\User` you will notice that that class does not have a body, but only the usage of fours traits:

```php
class User extends Model implements
    AuthenticatableContract,
    AuthorizableContract,
    CanResetPasswordContract
{
    use Authenticatable, Authorizable, CanResetPassword, MustVerifyEmail;
}
```
to keep using Corcel's model class I suggest you to implement those same interfaces and use the same traits, but keeping extending Corcel's base model class.

if you just need the `can()` method you can just use the `Authorizable` trait in your own `App\User` class.

hope it helps 🎉

**Comment by audetcameron** [comment]
> @audetcameron thanks for the message. if you take a look on `Illuminate\Foundation\Auth\User` you will notice that that class does not have a body, but only the usage of fours traits:
> 
> ```
> class User extends Model implements
>     AuthenticatableContract,
>     AuthorizableContract,
>     CanResetPasswordContract
> {
>     use Authenticatable, Authorizable, CanResetPassword, MustVerifyEmail;
> }
> ```
> 
> to keep using Corcel's model class I suggest you to implement those same interfaces and use the same traits, but keeping extending Corcel's base model class.
> 
> if you just need the `can()` method you can just use the `Authorizable` trait in your own `App\User` class.
> 
> hope it helps 🎉

I ended up creating a model extending your model. It's working well.  Thank you for all the hard work on the Corcel package!  Also included examples for anyone integrating passport.
```

use Corcel\Model\User as CorcelUser;
use Illuminate\Auth\MustVerifyEmail as VerifyEmail;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Laravel\Passport\HasApiTokens;
use Corcel\Services\PasswordService;
use Illuminate\Contracts\Auth\Access\Authorizable as AuthorizableContract;
use Illuminate\Foundation\Auth\Access\Authorizable;


class User extends CorcelUser implements MustVerifyEmail, AuthorizableContract
{
    use HasApiTokens, Notifiable, VerifyEmail, SoftDeletes, Billable, Authorizable;
    protected $connection = 'my_wordpress_connection';



    ////////////////////////
    //PASSPORT OVERWRITES //
    ////////////////////////
    /**
     * Find the user instance for the given username.
     *
     * @param  string  $username
     * @return \App\User
     */
    public function findForPassport($username)
    {
        return $this->where('user_email', $username)->first();
    }

    /**
    * Validate the password of the user for the Passport password grant.
    *
    * @param  string $password
    * @return bool
    */
    public function validateForPassportPasswordGrant($password)
    {
        return (new PasswordService())->check($password, $this->user_pass);
    }


}
```
