### ISSUE TITLE
I can't understand the documentation 

### ISSUE THREAD

**Issue by ghost** [jgrossi/corcel#494]
- Corcel Version: ~2.7.0
- Framework Name & Version: Laravel Framework 5.7.15
- PHP Version: 7.3.9
- Database Driver & Version:

###( I'm New in LARAVEL ) Please I can't understand the documentation would you please Make a video to explain the documentation or to show me the steps  or if you already have one give me the link.

Thank you 

### Steps To Reproduce:

**Comment by andrewmclagan** [comment]
This is an issues board for an open source project. Not a free education learning service.

**Comment by jgrossi** [comment]
hey @di7aaa I suggest you to take a look on Laravel's documentation page. it's so much better than Corcel's, and once it's totally based on Eloquent you will understand exactly how Corcel works 👍
