### ISSUE TITLE
How to query taxonomy using meta ?

### ISSUE THREAD

**Issue by Blair2004** [jgrossi/corcel#498]
- Corcel Version: ^3.0
- Framework Name & Version: Laravel 6.2
- PHP Version: 7.2
- Database Driver & Version: MySQL 5.7

### Description:
Since there is a way to query post using meta... is there a way to query Category using their meta ?

**Comment by jgrossi** [comment]
hi @Blair2004 I don't know if I got your idea here, but it seems you are trying to query `Taxonomy` (for category) using their meta value, correct? 

if so you can use the `Taxonomy` class which has its own builder class: `TaxonomyBuilder`. it contains a scope method for `category()` and if you need to query using different names you can also use the `name(string $name)` method.

cheers 💪
