### ISSUE TITLE
Hello, How I retrieve type and category from post?

### ISSUE THREAD

**Issue by dannylank** [jgrossi/corcel#502]
- Corcel Version: #.#.# last
- Framework Name & Version: laravel 6
- PHP Version:  7,2
- Database Driver & Version: 5,7

### Description:
I know how get taxonomies from post like:

### Steps To Reproduce:

$post = Post::where('post_status','publish')->orderBy('post_date','desc')->take(1)->get();
      foreach($post as $p)
      {
        $cat = $p->taxonomies->first(); 
        echo $cat->name; 
      }

console: Politics;

How I get the type?

console: News

I get Taxonomy type from taxonomy table: 
  $cat = Taxonomy::where('taxonomy', 'type')->get();

**Comment by jgrossi** [comment]
hey @dannylank if you take a look we have a `PostBuilder` class, and there you can find a `taxonomy()` scope. so you can just:
```php
$post = Post::taxonomy($name, $value)->get();
```
and you will have all related posts. cheers 💪
