### ISSUE TITLE
Settings

### ISSUE THREAD

**Issue by josec89** [jgrossi/corcel#51]
Is there something planned for getting the WP settings?

This should be as easy as connecting to the settings table and parsing some rows in case of `json` isn't it? Maybe I can try and make `pull request`

**Comment by jgrossi** [comment]
Hi @josec89! That's a very nice suggestion ;-)
You can go ahead and send us a pull request! That will be nice :D

**Comment by josec89** [comment]
Hey, I'm having some issues executing the tests, is there some special command or `phpunit` call I have to execute? 

Thanks :)

**Comment by jgrossi** [comment]
Hi @josec89! About the Corcel tests, they are being remade. Currently you must use a fake database (MySQL) just to collect information from Wordpress tables, but they're going to be made using Sqlite instead of MySQL to facilitate tests. You're welcome to help too :D

**Comment by jgrossi** [comment]
@josec89 This is the `sql` file where the database is `https://github.com/jgrossi/corcel/blob/master/tests/config/database.sql`. But tests with Corcel will be facilitated using Sqlite to do that :P

**Comment by josec89** [comment]
Yep, I saw the .sql file, created a database with that dump, and set the settings in the `autoload.php` file

But I'm getting this error and maybe I'm doing something wrong (I'm quite newbie at testing composer packages):

```
Fatal error: Call to a member function connection() on null in /home/vagrant/projects/corcel/vendor/illuminate/database/Eloquent/Model.php on line 3335
```

I'm using `homestead` for this I don't know if this might be the problem

**Comment by josec89** [comment]
Okay, finally solved it, wasn't loading the `autoload.php` file for some reason.. I've added a `phpunit.xml` file so as to ease the testing process (running `phpunit` works without any other parameter)

**Comment by jgrossi** [comment]
Awesome @josec89 :-)
