### ISSUE TITLE
Laravel 7 support

### ISSUE THREAD

**Issue by xewl** [jgrossi/corcel#510]
- Corcel Version: ^3.1
- Framework Name & Version: Laravel 7.0
- PHP Version: ^7.2 (7.4 in my setup)
- Database Driver & Version: /

### Description:
The inevitable; adding support for Laravel 7

### Steps To Reproduce:
`composer update` with requirement `"laravel/framework": "^7"`
results in:
```
Problem 1
    - Conclusion: don't install laravel/framework v7.0.2
    - Conclusion: don't install laravel/framework v7.0.1
    - Conclusion: don't install laravel/framework v7.0.0
    - jgrossi/corcel v3.1.0 requires illuminate/support ^6.0 -> satisfiable by laravel/framework[v6.18.0, 6.x-dev], illuminate/support[6.x-dev, v6.0.0, v6.0.1, v6.0.2, v6.0.3, v6.0.4, v6.1.0, v6.10.0, v6.11.0, v6.12.0, v6.13.0, v6.13.1, v6.14.0, v6.15.0, v6.15.1, v6.16.0, v6.17.0, v6.17.1, v6.18.0, v6.2.0, v6.3.0, v6.4.1, v6.5.0, v6.5.1, v6.5.2, v6.6.0, v6.6.1, v6.6.2, v6.7.0, v6.8.0].
...
```

**Comment by jgrossi** [comment]
hey! added support to L7 on branch 4.0. please update your `jgrossi/corcel` to `4.0.0` 🎉
