### ISSUE TITLE
ErrorException Notice: unserialize(): Error at offset 0 of 14 bytes

### ISSUE THREAD

**Issue by OmarRobinson** [jgrossi/corcel#512]
- Corcel Version: 2.8.0
- Framework Name & Version: Laravel 5.8
- PHP Version: 7.2
- Database Driver & Version: MySQL 5.7

### Description:
The system is returning a notice on every page load for unserialize(): Error at offset 0 of 14 bytes

### Steps To Reproduce:

Create a **app/Providers/BlogServiceProvider.php** as show in example below:

```   
public function boot()
{
	$list = ['siteurl', 'home', 'blogname', 'blogdescription'];
        $options = Option::asArray($list); // <---- This is the line error occurs on
        config(['blog' => $options]);
}
```

Nothing complicated, but I can't seem to get rid of that error.

**Comment by bellwood** [comment]
I too am using 2.8.0 on L5.8 and this works fine for me on PHP 7.4:

```
use Corcel\Model\Option as Option;
```
...
```
$list = ['siteurl', 'home', 'blogname', 'blogdescription'];
$options = Option::asArray($list);
dd($options);
```

**Comment by OmarRobinson** [comment]
Thanks for the follow-up @bellwood. It's working for me now also. I wish I could remember how I resolved this issue.

**Comment by scajal** [comment]
Hi, I'm having the same issue using Corcel in a WP plugin. When I try to return all the posts using Post::all() in a custom endpoint, it gives me the error. Any idea?
