### ISSUE TITLE
Create post from corcel within external wordpress site

### ISSUE THREAD

**Issue by marcpre** [jgrossi/corcel#519]
- Corcel Version: `"3.0.0"`
- Framework Name & Version: `Laravel Framework 6.16.0`
- PHP Version: `PHP 7.4.1`

### Description:

How to create a new post in corcel. I found this issue [301](https://github.com/corcel/corcel/issues/301) where a create method is mentioned in the Eloquent class `Post`. 

![image](https://user-images.githubusercontent.com/30902582/84437981-2fe57600-ac36-11ea-8f6a-b9370a323778.png)

Furthermore, I haven`t found anything in the documentation.

Appreciate your replies!

**Comment by ajgentile** [comment]
I use:
$post = new Post();
$post->post_title = $new_title;
...
$post->save()
$the_new_post_id = $post->ID;
$post->saveMeta($meta_array);
etc.

Might be kinda hacky but works for me. I have a lot of helper functions I've written to keep all the wp tables in sync. Wordpress is spaghetti code but it's the one we've got.
