### ISSUE TITLE
Not working with Laravel 8

### ISSUE THREAD

**Issue by alagaccia** [jgrossi/corcel#529]
- Corcel Version: 4.0.1
- Framework Name & Version: Laravel 8
- PHP Version: 7.3

### Description:
This package seems not to be working with Laravel 8.

Problem 1
    - Conclusion: don't install jgrossi/corcel v4.0.1
    - Conclusion: don't install jgrossi/corcel v4.0.0
    - Conclusion: remove laravel/framework 8.x-dev
    - Installation request for jgrossi/corcel ^4.0 -> satisfiable by jgrossi/corcel[4.0.x-dev, v4.0.0, v4.0.1].
    - Conclusion: don't install laravel/framework 8.x-dev
    - jgrossi/corcel 4.0.x-dev requires illuminate/database ^7.0 -> satisfiable by laravel/framework[7.x-dev], illuminate/database[7.x-dev, v7.0.0, v7.0.1, v7.0.2, v7.0.3, v7.0.4, v7.0.5, v7.0.6, v7.0.7, v7.0.8, v7.1.0, v7.1.1, v7.1.2, v7.1.3, v7.10.0, v7.10.1, v7.10.2, v7.10.3, v7.11.0, v7.12.0, v7.13.0, v7.14.0, v7.14.1, v7.15.0, v7.16.0, v7.16.1, v7.17.0, v7.17.1, v7.17.2, v7.18.0, v7.19.0, v7.19.1, v7.2.0, v7.2.1, v7.2.2, v7.20.0, v7.21.0, v7.22.0, v7.22.1, v7.22.2, v7.22.3, v7.22.4, v7.23.0, v7.23.1, v7.23.2, v7.24.0, v7.25.0, v7.26.0, v7.26.1, v7.27.0, v7.3.0, v7.4.0, v7.5.0, v7.5.1, v7.5.2, v7.6.0, v7.6.1, v7.6.2, v7.7.0, v7.7.1, v7.8.0, v7.8.1, v7.9.0, v7.9.1, v7.9.2].
    - Can only install one of: laravel/framework[7.x-dev, 8.x-dev].
    - don't install illuminate/database 7.x-dev|don't install laravel/framework 8.x-dev

### Steps To Reproduce:
composer require jgrossi/corcel

**Comment by asjsrep** [comment]
The only failing test I can see is the pagination regex. I'm not familiar with the new tailwind implementation. Would:

`        $this->assertRegExp('/\<nav role="navigation/', $paginator->toHtml());`

be robust enough?

Apart from that the legacy factory package is required for the tests along with version bumbps:

`    "require": {
        "php": ">=7.2.5",
        "illuminate/database": "^8.0",
        "illuminate/filesystem": "^8.0",
        "illuminate/support": "^8.0",
        "fzaninotto/faker": "^1.9",
        "hautelook/phpass": "0.3.*",
        "thunderer/shortcode": "^0.7.3"
    },
    "require-dev": {
        "orchestra/testbench": "^6.0",
        "symfony/thanks": "^1.0",
        "mockery/mockery": "^1.0",
        "dms/phpunit-arraysubset-asserts": "^0.1.0",
        "laravel/legacy-factories":"^1.0.4"
    },

`

**Comment by jchimene** [comment]
More problems:

Error 

  Call to undefined method Illuminate\Support\Facades\Auth::provider()

  at vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php:261
    257▕         if (! $instance) {
    258▕             throw new RuntimeException('A facade root has not been set.');
    259▕         }
    260▕ 
  ➜ 261▕         return $instance->$method(...$args);
    262▕     }
    263▕ }
    264▕

  1   /Users/jeffreychimene/git/corcel/src/Laravel/CorcelServiceProvider.php:47
      Illuminate\Support\Facades\Facade::__callStatic("provider")

  2   /Users/jeffreychimene/git/corcel/src/Laravel/CorcelServiceProvider.php:27
      Corcel\Laravel\CorcelServiceProvider::registerAuthProvider()
Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 1
`

**Comment by jchimene** [comment]
Thanks! I think that worked

**Comment by jgrossi** [comment]
`v5.0.0` tagged and compatible with Laravel 8

**Comment by thecapablecoder** [comment]
Hi,

Sorry, but i am experiencing the same problem on a fresh installation of Laravel v8.12.3:

Problem 1
    - Conclusion: don't install jgrossi/corcel v5.0.0
    - Conclusion: remove fakerphp/faker v1.10.1
    - Installation request for jgrossi/corcel ^5.0 -> satisfiable by jgrossi/corcel[5.0.x-dev, v5.0.0].
    - Conclusion: don't install fakerphp/faker v1.10.1
    - jgrossi/corcel 5.0.x-dev requires fzaninotto/faker ^1.9 -> satisfiable by fakerphp/faker[1.9.x-dev, v1.9.1], fzaninotto/faker[1.9.x-dev, v1.9.0, v1.9.1].
    - Can only install one of: fakerphp/faker[1.9.x-dev, v1.10.1].
    - Can only install one of: fakerphp/faker[v1.9.1, v1.10.1].
    - fzaninotto/faker 1.9.x-dev conflicts with fakerphp/faker[v1.10.1].
    - fzaninotto/faker v1.9.0 conflicts with fakerphp/faker[v1.10.1].
    - fzaninotto/faker v1.9.1 conflicts with fakerphp/faker[v1.10.1].
    - Installation request for fakerphp/faker (locked at v1.10.1, required as ^1.9.1) -> satisfiable by fakerphp/faker[v1.10.1].

Any idea how to fix this?

**Comment by thecapablecoder** [comment]
I fixed it by specifically requiring Faker v1.9.1 (essentially downgrading it). But this might still be interesting for you.
