### ISSUE TITLE
starter site

### ISSUE THREAD

**Issue by DeeJaVu** [jgrossi/corcel#53]
please create a simple starter site for beginners

**Comment by jgrossi** [comment]
Hi @DeeJaVu! Can you tell me more about the "starter site"? Corcel is a library to get data from Wordpress databases. You should use Corcel with Laravel, Slim, Silex, CakePHP, Zend, or even without framework ;-)

**Comment by DeeJaVu** [comment]
a sample site to get started, anyway do i need to install laravel and wordpress together to use corcel ?

**Comment by jgrossi** [comment]
@DeeJaVu If you want to use Laravel with Wordpress using Corcel, first you have to install Laravel and Wordpress :-) you can follow my post about this to get an idea of directories structure: http://blog.jgrossi.com/2014/working-with-laravel-4-and-wordpress-together

After both installed you should include `Corcel` package in `composer.json`. After that you will be ready to use Corcel model classes inside Laravel ;-)
