### ISSUE TITLE
Laravel API routes

### ISSUE THREAD

**Issue by dmitry-voronoff** [jgrossi/corcel#533]
- Corcel Version: 5.0.0
- Framework Name & Version: Laravel 8.12.3
- PHP Version: 7.4.1
- Database Driver & Version: MySQL 5.7.26

### Description:
Work fine:
`Route::get( '/posts/{id}', [Post::class, 'find'] );`
`Route::get( '/posts', [Post::class, 'all'] );`

But if i need to get only published posts I have to write:
`Route::get( '/posts', function(Request $request) {
    return Post::published()->get();
});`

My question is:
Is there is a way to write something to:
`Route::get( '/posts', [Post::class, 'published'] );`

Best regards,
Dmitry

**Comment by jgrossi** [comment]
hey man! no that's not possible. this way we would need to create "controllers" and I think this is more your app's responsibility, not the library's.
