### ISSUE TITLE
Package fzaninotto/faker is abandoned

### ISSUE THREAD

**Issue by loiemilio** [jgrossi/corcel#534]
- Corcel Version: 5.0.0
- Framework Name & Version: Laravel 8.13.0
- PHP Version: 7.3.24
- Database Driver & Version: Not relevant

### Description:
fzaninotto/faker is among Corcel's dependencies but the package has been abandoned in October as explained here
https://marmelab.com/blog/2020/10/21/sunsetting-faker.html

While not officially suggested by fzaninotto, a possible replacement for the package is fakerphp/faker
https://github.com/FakerPHP/Faker

### Steps To Reproduce:
`composer require jgrossi/corcel`
you will receive this message from composer
`Package fzaninotto/faker is abandoned, you should avoid using it. No replacement was suggested.`

**Comment by atomtigerzoo** [comment]
This should be merged because corcel renders unusable for now 😳
