### ISSUE TITLE
Question: Use Corcel to create posts with featured image and ACF

### ISSUE THREAD

**Issue by mauthi** [jgrossi/corcel#536]
- Corcel Version: #.#.#
- Framework Name & Version:
- PHP Version: 
- Database Driver & Version:

### Description:
Your package looks really nice. A played around a little bit today.
If I understand your README correctly the main purpose is READING from wordpress.
For a project I would need the other way around and create posts (custom post type with ACF).
Use case: I have an existing customer database and would like to create one post for each customer with images and logo.

I managed already to create a new post but I can't find a way to:
- add a featured image? (image is not in media library and I need to generate it)
- add another image(s) which are defined as ACF with type "Image"

It would be nice if you can tell me if this is possible somehow with your package.
(FYI: I am not an user - I have many years of experience in web development - maybe I overlooked something in your documentation :))

Thx in advance for your help.

### Steps To Reproduce:

**Comment by jgrossi** [comment]
hey @mauthi yep Corcel's main use is to READ from WP DBs, but once it's built on top of Eloquent ORM you're free to `create()` anything. what you need to do is to identify how the "featured image" is created in your db, then with the relationships we already you might be able to add a featured image. I'd say that probably it's another post with a different post type, then linked to the original post ID.

if this is a default behaviour WP has would be good to have a method or something at `Post` level to "create a featured image". feel free to raise a PR for that or suggest something we can work with 👍

**Comment by mauthi** [comment]
Thx - I switched to using WP Rest API for my project - updating database directly was too dangerous.
