### ISSUE TITLE
Beautify model arguments

### ISSUE THREAD

**Issue by josec89** [jgrossi/corcel#54]
Hello guys, I've just started using this awesome package, but I found out the WP fields are quite awful :(

```
  "ID" => 3
    "post_author" => 1
    "post_date" => "2016-01-30 16:50:25"
    "post_date_gmt" => "-0001-11-30 00:00:00"
    "post_content" => ""
    "post_title" => "Auto Draft"
    "post_excerpt" => ""
    "post_status" => "auto-draft"
    "comment_status" => "open"
    "ping_status" => "open"
    "post_password" => ""
    "post_name" => ""
    "to_ping" => ""
    "pinged" => ""
    "post_modified" => "2016-01-30 16:50:25"
    "post_modified_gmt" => "-0001-11-30 00:00:00"
    "post_content_filtered" => ""
    "post_parent" => 0
    "menu_order" => 0
    "post_type" => "post"
    "post_mime_type" => ""
    "comment_count" => 0
    "meta" => []
  ]
```

The `post_title` field instead of `title` kills me a little bit.

Would you approve something generic to translate this ugly field names into something more legible? Maybe an array located on every model with a trait to make the conversions?

If you agree with me I can work on this :)

**Comment by jgrossi** [comment]
Hi @josec89! I agree with you and this is something that make me fell bad hehe. `post_title` sounds bad. These fields are default from Wordpress but I think we can change it. We must provide both field names because compatibility purposes (`post_title` and `title`).

We can work on this  together. Any help is welcome. Thanks!

**Comment by josec89** [comment]
Hmmm I think this won't be as easy as I firstly though:

I think we need to use Eloquent accessors (https://laravel.com/docs/5.1/eloquent-serialization#appending-values-to-json) 
So we'd need to add `$append = [<all the new field names>]` and one method for every new field.

Something like:

```
    protected $appends = ['title'];

    public function getTitleAttribute()
    {
        return $this->post_title;
    }
```

What do you think?

**Comment by jgrossi** [comment]
Yes, accessors  is the best fit  with `append` properties. I think now we can map all post fields (and authors, etc) the original names and what's the best replace for each one. I'm on mobile now, sorry :-(

**Comment by jgrossi** [comment]
Done! #58
Thanks for the support @josec89
