### ISSUE TITLE
Can not auth with wordpress email and password

### ISSUE THREAD

**Issue by jensej** [jgrossi/corcel#550]
- Corcel Version: #.#.# 4.00
- Framework Name & Version: 7.29
- PHP Version: 7.2
- Database Driver & Version: wordpress

### Description:
Hi.
I added in config/database.php
wordpress connection

in config/auth.php

```
'providers' => [
        'users' => [
            'driver' => 'corcel',
            'model'  => Corcel\Model\User::class,
        ],

        // 'users' => [
        //     'driver' => 'database',
        //     'table' => 'users',
        // ],
    ],
```
I get success post data, 
but when I try to login like:

```
 $res = \Auth::validate([
            'email' => 'test132', // or using 'username' too
            'password' => 'password123',
        ]);
  dd($res)
```
result is false.
Could someone tell me why?
Thanks
### Steps To Reproduce:

**Comment by bellwood** [comment]
Are you using `Auth` within Corcel's namespace at the top of your controller?

**Comment by jensej** [comment]
> Are you using `Auth` within Corcel's namespace at the top of your controller?
good point.
Also I would like to use JWT tokens to login, How exacly I should do this?
Thanks a lot
