### ISSUE TITLE
Use "bordoni/phpass": "0.3.*" on Corcel 4 too please

### ISSUE THREAD

**Issue by DamienCegos** [jgrossi/corcel#580]
- Corcel Version: 4.*
- Framework Name & Version:
- PHP Version: 
- Database Driver & Version:

### Description:

Could it be possible to use "bordoni/phpass": "0.3.*", in the version 4 too please, we still have some old version of laravel ;)

**Comment by jgrossi** [comment]
sure thing @DamienCegos have plans to work on that between today and tomorrow 👍 I will keep you posted here

**Comment by jgrossi** [comment]
fixed on #582 👍 new tag `v4.1.0`
