### ISSUE TITLE
Class 'Corcel\Model\Product' not found

### ISSUE THREAD

**Issue by kitojazz** [jgrossi/corcel#583]
- Corcel Version: 4.1.#
- Framework Laravel & 7:
- PHP Version: 7.2
- Database Driver & Version:

### Description:
Este es mensaje de error que obtengo

Symfony\Component\ErrorHandler\Error\FatalError: Class 'Corcel\Model\Product'

este es mi modelo producto que se extiende de corcel 

<?php

namespace App;

use Corcel\Model\Product as Corcel;

class Productos extends Corcel
{
    protected $connection = 'wordpress';

    public function customMethod() {
        //
    }
}

y este es mi controlador

<?php

namespace App\Http\Controllers\Admin;

use App\Productos;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class ProductosController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        
        $productos = Productos::all();
        dd($productos);
    }

}

sin embargo cuando quiero acceder al modelo product de corcel no lo encuentra que puede estar pasando?

**Comment by jgrossi** [comment]
@kitojazz can you add some examples of how your code looks like, please?
