### ISSUE TITLE
Corcel 5.0 with Laravel 9

### ISSUE THREAD

**Issue by fh32000** [jgrossi/corcel#602]
- Corcel Version: 3.3.0
- Framework Name & Version:Laravel 9
- PHP Version: 8.0.2
- Database Driver & Version:mysql 8

### Description:
Please upgrade to work with Laravel
### Steps To Reproduce:

**Comment by fh32000** [comment]
@DougSisk @jakejohns @thiagof @bartjuh4

**Comment by atmonshi** [comment]
I opened a PR #603  I hope it will be aaccebted

**Comment by jgrossi** [comment]
hey 👋 support to Laravel 9 added on the new tag `v6.0.0`
