### ISSUE TITLE
Project abandoned?

### ISSUE THREAD

**Issue by benrowe-chuffed** [jgrossi/corcel#635]
Seems like there's been no development activity on this project for over a year now? Is there any plans to continue supporting this?

**Comment by jgrossi** [comment]
Hey no the project is not abandoned. Just the time for maintaining it that has been a challenge during the last few months specially. Happy to add more people to the organisation so we can help more the project together. Ideas?

**Comment by MiMEKiZ** [comment]
> Ideas?  

Could you approve a request for support for version 10?  This will help the community a lot.
https://github.com/corcel/corcel/pull/632

**Comment by lucamago** [comment]
@jgrossi  Any update on merging PR for Laravel 10 compatibility? Please 🙏🏻
