### ISSUE TITLE
Laravel 11 and PHP 8.2 support

### ISSUE THREAD

**Issue by junamai2000** [jgrossi/corcel#648]
### Description:

v7.0.0 does not support latest laravel 11. Can you fixed dependency to support laravel 11?

**Comment by interludic** [comment]
Problem 1
    - Only one of these can be installed: illuminate/filesystem[v5.5.0, ..., v5.5.44, v9.0.0, ..., v9.52.16, v10.0.0, ..., v10.48.2, v11.0.0, ..., v11.0.5], laravel/framework[v11.0.0, ..., v11.0.5]. laravel/framework replaces illuminate/filesystem and thus cannot coexist with it.
    - jgrossi/corcel v7.0.0 requires illuminate/filesystem ^10.0 -> satisfiable by illuminate/filesystem[v10.0.0, ..., v10.48.2].
    - Root composer.json requires jgrossi/corcel ^7.0 -> satisfiable by jgrossi/corcel[v7.0.0].
    - Root composer.json requires laravel/framework ^11.0 -> satisfiable by laravel/framework[v11.0.0, ..., v11.0.5].

What is the ETA on this as my project is heavily dependent on this package, i need to know if i need to start working on alternatives or just temporary work arounds?

**Comment by junamai2000** [comment]
#645

**Comment by interludic** [comment]
> #645

Did you try require in a laravel 11 install?

after running:
composer require jgrossi/corcel:^7.0

get

 Problem 1
    - Root composer.json requires jgrossi/corcel 7.0 -> satisfiable by jgrossi/corcel[v7.0.0].
    - jgrossi/corcel v7.0.0 requires illuminate/database ^10.0 -> found illuminate/database[v10.0.0, ..., v10.48.4] but these were not loaded, likely because it conflicts with another require.

**Comment by lucamago** [comment]
Please @jgrossi it's really important for many of us! <3

**Comment by interludic** [comment]
Need to know if i am working on alternatives or just temporary work arounds?

**Comment by jgrossi** [comment]
fixed by #645
