### ISSUE TITLE
Laravel / Corcel ignoring $connection set in model

### ISSUE THREAD

**Issue by DeanWard** [jgrossi/corcel#77]
I've added a Post model to my app directory that looks like this

    <?php

    namespace App;

    use Corcel\Post as Corcel;

    class Post extends Corcel
    {
        protected $connection = 'wordpress';
    }

I've added a custom connection to my database.php file:

    'wordpress' => [
        'driver'    => 'mysql',
        'host'      => env('DB_HOST', ''),
        'database'  => env('DB_DATABASE', ''),
        'username'  => env('DB_USERNAME', ''),
        'password'  => env('DB_PASSWORD', ''),
        'charset'   => 'utf8',
        'collation' => 'utf8_unicode_ci',
        'prefix'    => 'wp_',
        'strict'    => false,
        'engine'    => null,
    ],    

Yet when requesting posts like so:

    $posts = App\Post::all();

I'm getting an error because it's using the wrong connection and not adding the wp_ prefix.

    SQLSTATE[42S02]: Base table or view not found: 1146 Table 'cms.terms' doesn't exist (SQL: select * from `terms` where `terms`.`term_id` in (1))

Thanks for the awesome work you're all doing on this!

**Comment by jgrossi** [comment]
@DeanWard Fixed in the PR #79! Thanks @rundef for the support!

**Comment by DeanWard** [comment]
Awesome Thanks guys

**Comment by jgrossi** [comment]
@DeanWard did the PR #79 fix the issue #77? I've found here the `connection` problem.. when making relationships other classes use default connection...

One solution is create your own Taxonomy model, extending and setting the connection, but this is not the best one. The solution gave by @rundef solve the solution but only for a specific model. I'm working on do this from `Post` model and expanding to all relations.

Please, give any information you have about this issue. I'm opening it again. Thanks.

**Comment by DeanWard** [comment]
The whole thing is confusing to me as all I'm trying to do is run the example code from the readme. I'm thinking it may have something to do with the fact that I'm using the test content I mentioned in #80 ?

**Comment by jgrossi** [comment]
@DeanWard that's not the problem. When extending `Corcel\Post` the connection name is set only for `Post` class, not the relations, like `Term`, `User`, etc. What we should do is when set the connection name link all classes that depend of the `Post`. One good solution is to create a `Corcel\Model` class and set all relations there and so all classes extend it :-)

**Comment by wolfius** [comment]
Hi!
I already updated to 1.0.1 but I'm not sure if I'm doing something wrong. I'm using Laravel and extending Corcel\Post to set connection to 'wordpress', but when do something like this:

```
$post = Post::find($post)->first();
$post->image;
```
I get a "table not found" error because it's trying to select it from Laravel's default connection. Any other functions to get Post information or meta, work fine. The error seems to come up when using Attachment::find() to get the image but I find it strange since Attachment extends Post.

**Comment by jgrossi** [comment]
Thanks for reporting this @wolfius. This should be fixed in the last version. We're going to check about this database connection and write the update here. Thanks for contributing.

**Comment by vgomes** [comment]
Using 1.0.3 keeps happening.

I've defined my connection as 
`'wordpress' => [ // this is your Corcel database connection, where WordPress tables are
            'driver' => 'mysql',
            'host' => env('DB_HOST', 'localhost'),
            'port' => env('DB_PORT', '3306'),
            'database' => env('DB_DATABASE', 'forge'),
            'username' => env('DB_USERNAME', 'forge'),
            'password' => env('DB_PASSWORD', ''),
            'charset' => 'utf8',
            'collation' => 'utf8_unicode_ci',
            'prefix' => 'wp_',
            'strict' => false,
            'engine' => null,
        ],`

and my Post model as
`<?php

namespace App;

class Post extends \Corcel\Post
{
    protected $connection = 'wordpress';
}`

but when I'm trying to do a simple `$posts = Post::published()->get();` I get an error `Base table or view not found: 1146 Table 'bar.postmeta' doesn't exist`

If I put the **protected $connection = 'wordpress';** into the file **vendor/jgrossi/corcel/src/Model.php**, all seems to work properly, but I assume that after a **composer update** this change could be potentially gone.

**Comment by jgrossi** [comment]
Hi @vgomes! Sorry for that! We're gonna check what is happening.

**Comment by victorhguillen** [comment]
It happens to me, the only different it was, that I change 
`class Post extends \Corcel\Post`
to
`class Blog extends \Corcel\Post`
And use anothe class extends name, maybe some Laravel class cache, is breaking the class name.

When I use 
 `$posts = Post::published()->paginate(10); `

It breaks Laravel. 

So I use it like this:
 `$posts = Blog::published()->paginate(10); `
@jgrossi @vgomes

**Comment by jgrossi** [comment]
I this case I think is better to use it inside your own namespace like `App\Post`. But the connection is being applied to the relationships, right?

**Comment by victorhguillen** [comment]
@jgrossi can you give me a relationship example to test?

**Comment by jgrossi** [comment]
Like `App\Post::find(1)->author->user_nicename`

**Comment by victorhguillen** [comment]
Yes, perfect!. `Blog::find(2)->author->nickname;`

**Comment by jgrossi** [comment]
Thaks @victorhguillen So, I'm gonna close this issue for now. Any problem open it again. I think @DeanWard solved his problem too ;-)

**Comment by niko-afv** [comment]
Hi, i have try use Corcel in my project Laravel 5.3 and throw this error:

`Base table or view not found`

with query:

`select * from `postmeta` where `post_id` = 7 and `meta_key` = banners limit 1`

Corcel doesn't use my wordpress connection, but use my laravel default connection.

This problem isn't revolve it yet?

@jgrossi , Can you helpe with that?
