### ISSUE TITLE
Capitalize "P" of WordPress on title

### ISSUE THREAD

**Issue by leocaseiro** [jgrossi/corcel#87]
Sorry for opening this Issue, but while I was [posting on my twitter](https://twitter.com/leocaseiro/status/706986627604680704), I've notice the `P` on WordPress in your title is not capitalized.

The WordPress Community really cares about that, that would be nice to capitalize it.

If you are interested why: https://clarkwp.wordpress.com/2014/04/30/why-is-the-p-in-wordpress-important/

Thanks.

**Comment by jgrossi** [comment]
Hi @leocaseiro! Thanks for the support! The package description had to be changed to something more clear, so I changed it to `Use WordPress backend with any PHP framework`, with capitalized `P` :-) 
Thanks for helping!

**Comment by leocaseiro** [comment]
Thats awesome! No worries!
