### ISSUE TITLE
Menu class

### ISSUE THREAD

**Issue by johannesfosseus** [jgrossi/corcel#9]
Hi

This is great and open lots of interesting things!
One thing, I would love to have a simple menu class.
Menu::name('header')->get();

**Comment by rundef** [comment]
I'm closing this issue, it has been merged onto the dev branch.

**Comment by codemonkeynorth** [comment]
I have pages and category items in my menu. The title / post_title only gives me a value if I change the label from the original value to something else

please advise?

thanks
J

Wordpress 4.6
laravel/framework: 5.2.*
jgrossi/corcel: ^1.1
,
