### ISSUE TITLE
AuthServiceProvider Class not found

### ISSUE THREAD

**Issue by suresh-kumar** [jgrossi/corcel#91]
Hi 

I've added the authenication service provider in config/app.php

The following error occured

FatalErrorException in ProviderRepository.php line 146:
Class 'Corcel\Providers\Laravel\AuthServiceProvider' not found

Please advise us

Thanks
suresh

**Comment by rundef** [comment]
Hi,

Are you using Corcel 1.0.1 ? I see that the readme wrongly suggests installing the 1.0.0 version.
Which version of Laravel are you using ? (`php artisan --version`)
Regenerating the autoloaded classes might help: `composer dump-autoload -o`

**Comment by suresh-kumar** [comment]
Hi 

Thanks for the  quick reply. I updated the corcel to 1.0.1 

"require": {
     
        "jgrossi/corcel": "1.0.1"
    },

Compose update:
  - Installation request for jgrossi/corcel 1.0.1 -> satisfiable by jgrossi/corcel[v1.0.1].

Unfortunately the error still exist.

php artisan --version
Laravel Framework version 5.2.22

Please let me know if you need more info

Thanks
suresh

**Comment by rundef** [comment]
Hi,

Did you get an error during the composer update ? Because you have to remove the corcel auth service provider line in `config/app.php` while you're running composer update (the service provider didn't exists in 1.0.0)

Then you can re add the service provider config.
If it's still not working, try deleting the file `bootstrap/cache/services.php`, and running `composer dump-autoload -o`

**Comment by suresh-kumar** [comment]
yes i removed  the class from config/app.php and run composer update

> php artisan clear-compiled
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - hautelook/phpass 1.0.0 requires php >=5.6.0 -> your PHP version (5.5.12) does not satisfy that requirement.
    - jgrossi/corcel v1.0.1 requires hautelook/phpass ^1.0 -> satisfiable by hautelook/phpass[1.0.0].
    - Installation request for jgrossi/corcel 1.0.1 -> satisfiable by jgrossi/corcel[v1.0.1].

Also bootstrap/cache/services.php deleted and run composer dump-autoload -o

The error still exists

Thanks
suresh

**Comment by rundef** [comment]
Well, I'm guessing that if the file `vendor/jgrossi/corcel/src/Providers/Laravel/AuthServiceProvider.php` doesn't exists, it means that composer didn't update corcel to v1.0.1 because phpass needs php>=5.6.0. Maybe you should try installing a newer version of php ?

**Comment by mattKendon** [comment]
If corcel requires phpass, which in turn requires `"php":  ">=5.6.0"`, then corcel's `composer.json` requirement for `"php":  ">=5.4.0"` should be changed to be `"php":  ">=5.6.0"` to reflect that.

**Comment by suresh-kumar** [comment]
cool thanks will update my php version and try 

Thanks matt and rundef

Thanks
suresh
