### ISSUE TITLE
Database [wordpress] not configured.

### ISSUE THREAD

**Issue by Thovalot** [jgrossi/corcel#93]
My settings look like this, and still I can't get it to work...

'wordpress' => [
            'driver'    => 'mysql',
            'host'      => 'localhost',
            'database'  => '********',
            'username'  => '********',
            'password'  => '********',
            'charset'   => 'utf8',
            'collation' => 'utf8_unicode_ci',
            'prefix'    => 'blei_',
            'strict'    => false,
            'engine'    => null,
        ],

**Comment by jgrossi** [comment]
Hi @Thovalot are you using Laravel, right? Did you configure your models to use wordpress connection?

**Comment by Thovalot** [comment]
Yes, sorry there was something wrong with the server, locally it worked, I deleted everything and git pushed again and it worked, thanks.

**Comment by jgrossi** [comment]
you're welcome @Thovalot! any problem just ask :-)
