### ISSUE TITLE
Featured image not found

### ISSUE THREAD

**Issue by Thovalot** [jgrossi/corcel#94]
I have this post with a featured image and it's not showing, am I doing something wrong?

$post = Post::slug($slug)->with('attachment')->first();
dd($post->attachment->first());

And I get this:

Collection {#190 ▼
  #items: []
}

the $post->ID is correct...

**Comment by jgrossi** [comment]
@Thovalot as you're using Laravel maybe there is about #77. The relationships for a post are not loading the connection you've set in the Post model. we're trying to fix that... sorry about that... try to use the `dev-master` version `jgrossi/corcel: "dev-master"` and try :-( sorry again

**Comment by josec89** [comment]
The `featured image` is automatically loaded.

try this:
```
$post = Post::slug($slug)->first();
dd($post->image);
```

**Comment by jgrossi** [comment]
you are the man @josec89 hahaha

**Comment by Thovalot** [comment]
Thanks @jgrossi && @josec89, it's working now :D
